### ISSUE TITLE
Can't start app in Portrait if device is Landscape - iPhone6+ only

### ISSUE THREAD

**Issue by BrainFeverMedia** [cocos2d/cocos2d-objc#1001]
If app is configured to start in portrait mode and iPhone6+ is in landscape mode, window_ is misaligned. (See below)

To reproduce, must include 6 and 6+ launch screens, enable Portrait support, put iPhone6+ sim in Landscape mode, and launch in Portrait in AppDelegate.m

```
[self setupCocos2dWithOptions:@{
            CCSetupDepthFormat: @GL_DEPTH24_STENCIL8,
            CCSetupScreenOrientation: CCScreenOrientationPortrait,
            CCSetupTabletScale2X: @YES,
        }];
```

To fix, add setFrame to end of CCAppDelegate setupCocos2dWithOptions

```
[window_ makeKeyAndVisible];
---> ADD --->  [window_ setFrame:[[UIScreen mainScreen] bounds]];
```

This fix doesn't work in cocos2d v2, btw, still researching that...

![ios simulator screen shot sep 27 2014 4 05 11 pm](https://cloud.githubusercontent.com/assets/232037/4432010/86efbb5c-4681-11e4-8db2-bb2a36141b6e.png)

**Comment by s1ddok** [comment]
Problem is no more present.
