### ISSUE TITLE
CCEffect on a CCDrawNode

### ISSUE THREAD

**Issue by viveleroi** [cocos2d/cocos2d-objc#1003]
I was eager to apply a glow effect to a `CCDrawNode`, only to find it's not possible.

I'd like to suggest that `CCDrawNode` should support `CCEffect` (nodes/stacks as well) as the sprites do.

**Comment by slembcke** [comment]
Unfortunately CCEffect only works with nodes that draw a bitmap and have finite bounds (like sprites). It should be pretty easy to add the CCDrawNode to a CCEffectNode (which renders it's children to a render texture) and apply the effect to that.

**Comment by viveleroi** [comment]
I had tried that, and maybe I did something wrong, but the following code and variations of it crashed the app with no helpful error:

```
CCEffectNode *effectNode = [[CCEffectNode alloc] init];
effectNode.effect = [CCEffectBlur init];
[effectNode addChild:shields]; // shields is a CCDrawNode
[self addChild:effectNode];
```

**Comment by slembcke** [comment]
Two problems there. You need to create the effect node with a size, or set it's content size sometime before using it. You also need to do alloc then init on the blur effect or use the autorelease constructor method.

```
    CCDrawNode *shields = [CCDrawNode node];
    [shields drawDot:ccp(20, 20) radius:10 color:[CCColor redColor]];

    CCEffectNode *effectNode = [CCEffectNode effectNodeWithWidth:100 height:100];
    effectNode.effect = [CCEffectBlur effectWithBlurRadius:5];
    [effectNode addChild:shields];
    [self.contentNode addChild:effectNode];
```
