### ISSUE TITLE
git checkout develop-v3

### ISSUE THREAD

**Issue by issamux** [cocos2d/cocos2d-objc#1022]
error: pathspec 'develop-v3' did not match any file(s) known to git ... ??

**Comment by issamux** [comment]
plz update the documentation and remove this line .
the correct instruction are in the web site : 

git clone https://github.com/cocos2d/cocos2d-iphone.git
cd cocos2d-iphone
git submodule update --init --recursive

**Comment by slembcke** [comment]
Fixed. Thank you.
https://github.com/cocos2d/cocos2d-swift/blob/v3.2/README.md#download-from-github
