### ISSUE TITLE
Changing affectedByGravity to YES does not have the body affected by gravity unless force is applied

### ISSUE THREAD

**Issue by LearnCocos2D** [cocos2d/cocos2d-objc#1030]
I'm trying to find a way to make physics bodies sleep until I can wake them up. In Issue #738 it was already determined that the sleeping flag isn't currently working as expected.

I found that for my purposes I can simply set affectedByGravity to NO. However upon setting the value back to YES the body still won't move. I have to either touch it with another body or apply an ever-so-small impulse to wake it up, as in this code:

```
-(void) setSleeping:(BOOL)sleeping node:(CCNode*)node
{
    CCPhysicsBody* body = node.physicsBody;
    if (body.type == CCPhysicsBodyTypeDynamic)
    {
        body.affectedByGravity = !sleeping;

        if (!sleeping)
        {
            // give the body a slight nudge to force it to "wake up"
            [body applyImpulse:CGPointMake(0.000001, -0.000001)];
        }
    }

    for (CCNode* child in node.children)
    {
        [self setSleeping:sleeping node:child];
    }
}
```

Note: test case is in this repo/revision: https://github.com/LearnCocos2D/sbcc/commit/cde947273f923e38fa439b1ba19b143d4ae35bc1
Code is in WakeUpPhysicsBodyWhenTriggered class. Game instantly starts with a level where you only need to move ~100 points to trigger the above code.

**Comment by slembcke** [comment]
Fixed + tests here:
https://github.com/cocos2d/cocos2d-swift/commit/985467a6ec62547419b5fe4c8f317f777ba00044
