### ISSUE TITLE
Toggle the debugDrag of a physicsNode

### ISSUE THREAD

**Issue by ypmits** [cocos2d/cocos2d-objc#1037]
I'm wondering if I'm doing something wrong with the reading/writing of the debugDraw.
In my debug-menu I want to toggle the debugDraw and I'm using the following:
<code>_physicsNode.debugDraw = !_physicsNode.debugDraw;</code>
It toggles the debug on and off only once. Is this intended behavior or a bug?

**Comment by slembcke** [comment]
Fixed: https://github.com/cocos2d/cocos2d-swift/commit/5707baa6a287073e85ee9121169a643039eb06b5

An easy one for a change. Thanks.
