### ISSUE TITLE
Upgrading Spritebuilder to latest (MAS) now crashes project on a modified CCB.

### ISSUE THREAD

**Issue by ghost** [cocos2d/cocos2d-objc#1073]
I just upgraded SB to the latest on the MAS (1.3.5). 

I made a little change to one ccb file and now the app is crashing when I try to navigate to that scene. Pretty sure it is related to the effects property. 

 Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: '[PROPERTY] effects.

I haven't yet upgraded to the latest Cocos2d. My project is using 3.2.1. 

Has backwards compatibility broke? Was it marked in the release notes and perhaps I missed it? I will eventually upgrade to the latest. I just upgraded the project from v2 to 3.2.1 not too long ago so I need a break from Cocos2d upgrading on this project for awhile (lol). 

Thanks in advance.

**Comment by ghost** [comment]
So I just updated the CCBReader class manually to the newest version. I was a bit worried about it not being compatible but apart from using a new physics method (which I think was just a typo correction) I think it works fine with 3.2.1. 

I guess I'll have to do a little more testing because I remember customizing my CCBreader awhile ago to workaround a bug that caused didLoadFromCCB to get called too early if a scene had normalized coordinates set.

**Comment by NickyWeber** [comment]
CCBReader's format to encode/decode ccb files is versioned. A new version of cocos2d will not necessarily introduce a new format version. As soons as Spritebuilder provides a new format version upon publishing it'll break as long as cocos2d's CCBReader is not up to date. There is no backwards compatibility regarding CCBReader. 

In this case I could even imagine that the version was not incremented when adding effects leading to this out of sync behaviour otherwise it should usually crash with a more meaningful exception: 

> `CCBReader: Incompatible ccbi file version (file: %d reader: %d)`

The only remedy is to upgrade Cocos2d(or CCBReader only) as soon as you update Spritebuilder.

**Comment by ghost** [comment]
Yeah, I ended up having to do that. Unfortunately, I had modified my CCBReader awhile ago so I could access a node's positionInPoints property inside of the didLoadFromCCB method when using loadAsScene:

When using normalized coordinates in sprite builder it still isn't safe to access positionInPoints in didLoadFromCCB because didLoadFromCCB is called before the node is added to the empty scene. I think I opened a ticket awhile ago on that issue. I think when using loadAsScene, it would be better if the "node" in SB was added to the empty scene first. But I guess I'll end up moving that code to onEnter so future SB versions don't require me to keep digging in the CCBReader.

**Comment by NickyWeber** [comment]
I am uncertain if those ideas will make it any time soo to SB. Please close this ticket if this issue is resolved. BTW: Use Spritebuilder's github issues for SB related topics.

**Comment by ghost** [comment]
For sure. Upgrading only CCBReader has indeed resolved the crashing issue (without upgrading to the newest Cocos2d). Sorry if i went a little off-topic. Since SB is now tightly integrated with Cocos2d, it kind of blurs the line a bit as to what is a Cocos2d issue or a SB issue since subsequent Cocos2d versions are submitted through the MAS through Spritebuilder. 

Again my bad. Just throwing it out there. When loading a scene through SB, positionInPoints is known at design time so didLoadFromCCB should really be called once the root node that is being wrapped in the empty scene is set up. I'm pretty sure positionInPoints will work if you use any other position type besides normalized coordinates on the "scene". With all these different screen sizes, normalized coordinates is probably the best way to go most of the time on a scene initially, but I think most people prefer calculating relational layout programmatically in points after, which is why I imagine that the positionInPoints property exists. It actually isn't too hard to have didLoadFromCCB be called before the scene returns but after the root node is added as a child to the empty scene when using the loadAsScene: method.  But I guess positionInPoints is part of the Cocos2d api, and didLoadFromCCB is sprite builder. 

The reason why I posted here instead of SB, because well, I wasn't sure where to post it. In hindsight, I guess crashes that result from upgrading Spritebuilder should be posted in Spritebuilder issues. I added this side note just to maybe explain why some developers may not want to upgrade a project every time. But I guess I should be more careful in how I implement my solutions when using SB. 

As always, thanks for replying!

**Comment by NickyWeber** [comment]
All good, it's just that we may miss one or two tickets if it's not in the right place. 
We really appreciate your feedback!
