### ISSUE TITLE
Custom Fonts on iOS 6

### ISSUE THREAD

**Issue by DonomaGames** [cocos2d/cocos2d-objc#1098]
Everything works properly on iOS 7 and iOS 8.

When I run the project on iOS 6.1.3, I get this error:
dyld: lazy symbol binding failed: Symbol not found: _CTFontManagerCreateFontDescriptorsFromURL
  Referenced from: /var/mobile/Applications/04EB18E3-28FD-4608-94C4-58CDBCD6A370/LetThePigFly.app/LetThePigFly
  Expected in: /System/Library/Frameworks/CoreText.framework/CoreText

dyld: Symbol not found: _CTFontManagerCreateFontDescriptorsFromURL
  Referenced from: /var/mobile/Applications/04EB18E3-28FD-4608-94C4-58CDBCD6A370/LetThePigFly.app/LetThePigFly
  Expected in: /System/Library/Frameworks/CoreText.framework/CoreText

From this link https://developer.apple.com/Library/ios/releasenotes/General/iOS70APIDiffs/index.html, it appears that this method (CTFontManagerCreateFontDescriptorsFromURL) is not available in iOS 6? Has iOS 6 been dropped from cocos2d 3.3?

**Comment by osinoleg** [comment]
Just pushed a pull request to fix this issue - https://github.com/cocos2d/cocos2d-swift/pull/1105

**Comment by DonomaGames** [comment]
Thanks Oleg. I didn't even notice the block checking for version number. 

It looks like the check for version 7.0 is incorrect thus causing the failure?

#if __CC_PLATFORM_IOS
        BOOL needsCGFontFailback = [[[UIDevice currentDevice] systemVersion] compare:@"7.0" options:NSNumericSearch] != NSOrderedAscending;
#else

Changing it from 

!= NSOrderedAscending;
to 
== NSOrderedAscending;

appears to work correctly.

**Comment by slembcke** [comment]
This was fixed in develop a few weeks ago.
