### ISSUE TITLE
Some Cards vanish when user taps them in Positioning Test

### ISSUE THREAD

**Issue by sana20** [cocos2d/cocos2d-objc#1114]
1. Launch Github.
2. Open this link: https://github.com/cocos2d/cocos2d-swift
3. Clone project in desktop. 
4. Open the project in finder.
5. Open Cocos2d-tests.xcodeproj.
6. Set Target Cocos2d-tests-ios > iPhone 4s.
7. Run the project.
8. Select Positioning Test.
   -- Observe: Move Cards around screen is displayed. (Expected)
9. Tap Cards.
   
   -- Result:Some Cards vanish when user taps them in Positioning Test.
   Xcode: 6.0
   Mac OS X:10.10.1
   Link: https://drive.google.com/a/werplay.com/file/d/0B3iZC1SKU48yRUpkSWpMMTM1NDg/view?usp=sharing

**Comment by andykorth** [comment]
Thanks for the report, this was fixed in the referenced issue and can be closed now.
