### ISSUE TITLE
Swift: missing array initializer for CCActionSequence, CCActionSpawn

### ISSUE THREAD

**Issue by LearnCocos2D** [cocos2d/cocos2d-objc#1116]
There is no Swift equivalent for this code because the array initializer is missing from Swift:

```
id sequence = [CCActionSequence actionWithArray:@[move, wait, spawn, block, remove]];
```

The sequence (or spawn) action needs to be constructed via repeat use of the `one:two:` initializer:

```
let sequenceActions = [move, wait, spawn, block, remove]
var sequence = sequenceActions[0]
for var i = 1; i < sequenceActions.count; i++
{
    sequence = CCActionSequence(one: sequence, two: sequenceActions[i])
}
```

**Comment by s1ddok** [comment]
It wasn't a cocos2d problem, everything seems to work fine with latest version of Swift.
