### ISSUE TITLE
EXC_ARITHMETIC error on CCTiledMapLayer

### ISSUE THREAD

**Issue by njt1982** [cocos2d/cocos2d-objc#1118]
This is my TMX file:

```
<?xml version="1.0" encoding="UTF-8"?>
<map version="1.0" orientation="orthogonal" renderorder="left-up" width="32" height="32" tilewidth="128" tileheight="128">
 <tileset firstgid="1" name="TrackTerrain" tilewidth="128" tileheight="128">
  <tile id="0">
   <image width="128" height="128" source="Tiles/InnerCornerBL.png"/>
  </tile>
  <tile id="1">
   <image width="128" height="128" source="Tiles/InnerCornerBR.png"/>
  </tile>
  <tile id="2">
   <image width="128" height="128" source="Tiles/InnerCornerTL.png"/>
  </tile>
  <tile id="3">
   <image width="128" height="128" source="Tiles/InnerCornerTR.png"/>
  </tile>
  <tile id="4">
   <image width="128" height="128" source="Tiles/OuterCornerBL.png"/>
  </tile>
  <tile id="5">
   <image width="128" height="128" source="Tiles/OuterCornerBR.png"/>
  </tile>
  <tile id="6">
   <image width="128" height="128" source="Tiles/OuterCornerTL.png"/>
  </tile>
  <tile id="7">
   <image width="128" height="128" source="Tiles/OuterCornerTR.png"/>
  </tile>
  <tile id="8">
   <image width="128" height="128" source="Tiles/TileHorizontalBottom.png"/>
  </tile>
  <tile id="9">
   <image width="128" height="128" source="Tiles/TileHorizontalTop.png"/>
  </tile>
  <tile id="10">
   <image width="128" height="128" source="Tiles/TileNone.png"/>
  </tile>
  <tile id="11">
   <image width="128" height="128" source="Tiles/TileTrack.png"/>
  </tile>
  <tile id="12">
   <image width="128" height="128" source="Tiles/TileVerticalLeft.png"/>
  </tile>
  <tile id="13">
   <image width="128" height="128" source="Tiles/TileVerticalRight.png"/>
  </tile>
 </tileset>
 <layer name="Tile Layer 1" width="32" height="32">
  <data encoding="base64" compression="zlib">
   eJzt1jkOgDAMBdHPvgS4/3FxmQ6UmOBiiqks+VWWnCSln1usvXFr5p/W0bgLP7Q/WJtTY4Gfz2t72o+Pj4+Pj4+PH8Hv5Pfr9wX+1+HH8Sf5/fpvm+V3XzXdYdYtqQ==
  </data>
 </layer>
</map>
```

For some reason, `tilesPerSheetRow` == 0 (in CCTiledMapLayer / `-(void)draw:(CCRenderer *)renderer transform:(const GLKMatrix4 *)transform`)...
![screen shot 2014-12-10 at 23 39 42](https://cloud.githubusercontent.com/assets/384976/5386626/e23d8132-80c5-11e4-8420-d906320b2b60.png)

I suspect this line of code:

```
    int tilesPerSheetRow = (_tileset.imageSize.width - tilesetMargin*2 + tilesetSpacing) / (_tileset.tileSize.width + _tileset.spacing);
```

My tileset image width is 32. Margin and spacing is zero... Therefore the math ends up being `(32 - 0 + 0) / (32 + 0)`... Now this should be 1, not zero... Shouldn't it?!

**Comment by njt1982** [comment]
If I hardcode that line to 1, then I no longer get this error...

**Comment by njt1982** [comment]
![screen shot 2014-12-10 at 23 42 46](https://cloud.githubusercontent.com/assets/384976/5386653/481fcf82-80c6-11e4-9092-1d74bd706e0e.png)

**Comment by njt1982** [comment]
Thats what I get if I breakpoint the `int tilesPerSheetRow....` line (hence it having an unexpected value).

**Comment by njt1982** [comment]
hmm interesting...

```
    CCLOG(@"test: %.5f", (_tileset.imageSize.width - tilesetMargin*2 + tilesetSpacing) / (_tileset.tileSize.width + _tileset.spacing));
```

produces:

```
2014-12-10 23:44:28.814 GridRacer[22861:8759733] test: 0.50000
```

That explains why its zero...

**Comment by njt1982** [comment]
Ohhh the second part of the formula is tile size :) That explains the 0.5...

Now How do we fix this bug? When I set it to 1, although it runs the map is not rendered properly....

**Comment by njt1982** [comment]
I cant find the code in https://github.com/cocos2d/cocos2d-iphone-classic that does this... Has tile handling been completely rewritten?!

**Comment by njt1982** [comment]
Seems to have been reported before:
- http://www.raywenderlich.com/forums/viewtopic.php?f=20&t=4205&start=20#p28503
- http://forum.cocos2d-swift.org/t/how-do-i-put-a-tilemap-into-my-cocos2d-project/4944/3

**Comment by andykorth** [comment]
There are some oddities here. Your tileset doesn't have an image tag. Instead, you seem to have separate images for each tile. This mode isn't supported in cocos2d. 

Mine looks like this:

```
<?xml version="1.0" encoding="UTF-8"?>
<map version="1.0" orientation="orthogonal" width="50" height="25" tilewidth="32" tileheight="32">
 <tileset firstgid="1" name="entireTileMap" tilewidth="32" tileheight="32">
  <image source="entireTileMap.png" width="512" height="1024"/>
 </tileset>
 <layer name="Tiles" width="50" height="25">
  <data encoding="csv"> ... 
```

Please note the "limitations" section of CCTiledMap.h, which states: "It only supports one tileset image per layer." It looks like you have 14 images in one... well, in one tileset. 

Generally, the purpose of using tilemaps is to group all your artwork into one image, so the entire tilemap can be drawn without forcing the graphics card to switch textures. You should have one image, and it should look something like this: http://kortham.net/temp/upshot_nZYHgrdS.png

After some more testing, it does appear you can create files like the one you have using the "New Tileset" > "Collection of Images" mode. This isn't supported by Cocos2d. Sorry.

**Comment by andykorth** [comment]
Scott suggested there are assertions to catch multiple images in one tileset, but not an assertion to catch these "collection of images" tilesets. (Or tilesets without images in their xml tags, more generally). 

We should add an assertion for this.

(sidenote: collection tilesets are listed as a new feature of Tiled as of 14 September 2014)
