### ISSUE TITLE
CCTextField action callback behavior is inconsistent

### ISSUE THREAD

**Issue by thayerandrews** [cocos2d/cocos2d-objc#1128]
The documentation for CCTextField says that the action callback (either block or selector) will be called when the user hits the return key or taps outside the control, but this is not the implemented behavior on iOS. On iOS, the callback is only called when the user presses the return key. Tapping outside the control dismisses the keyboard but does not call the callback.

The behavior is different on the Mac build. On the Mac, the completion callbacks behave as specified by the documentation.

The completion callback behavior should be consistent across platforms and should match the documentation so the iOS implementation should be fixed.

**Comment by jonnyijapan** [comment]
I'm just wondering why the same action is called on return and tap outside CCTextField. How do we know which action the user performed? A return tap would indicate "send this message" etc, whereas a tap outside the textfield in most cases do not. The dev should decide this.

**Comment by andykorth** [comment]
Agreed, those are very different actions and should be somehow differentiated. Although, the callback behavior makes sense if you think of it as a "finished editing" callback. If there's not a way to tell the difference between those actions on iOS, I think that's something we should address.

**Comment by jonnyijapan** [comment]
It could maybe be circumvented by using the textField platform specific subproperty, but maybe it's better to keep it abstracted to ensure same behavior on all platforms.

2015/02/05 12:45$B!"(BAndy Korth notifications@github.com $B$N%a%C%;!<%8(B:

**Comment by jonnyijapan** [comment]
Btw original poster's issue is fixed, isn't it? When I tap outside the field or enter, the action is called on iOS. I'm using 1.34 hmm or something. I actually have no idea what version number is with SB 1.4 (beta?).
