### ISSUE TITLE
CCScrollView doesn't work in Mac target

### ISSUE THREAD

**Issue by cocojoe** [cocos2d/cocos2d-objc#1134]
Create a simple project with CCScrollView, scrolling doesn't work in OS X.

**Comment by andykorth** [comment]
Which branch is this? CCScrollView was rewritten in v4 recently.

**Comment by thayerandrews** [comment]
In cocos2d-tests-mac I see CCScrollViewTest responding to swipes on the magic mouse but not responding to click-drags. And, come to think of it, before you even get that far you need to use swipes in the test's initial menu screen to select the test. Click-drags also don't work there.

This is in the develop branch (commit 009410ee60eb36f0b4f1e19bf04f1256624320d9).

**Comment by slembcke** [comment]
Hmm. It works in the UI tests in the develop branch.

**Comment by andykorth** [comment]
Mac isn't supposed to respond to click-drags. Finder windows and safari doesn't. (even though we, as developers, get used to that behavior when using the simulator)

But the scroll wheel should work.

**Comment by thayerandrews** [comment]
Good point. I was definitely thinking of this from a simulator-centric perspective but, in hindsight, it doesn't make sense to click-drag to scroll in a Mac app.

**Comment by cocojoe** [comment]
Ah yes, fair point, I generally just treat the Mac target as a fast simulator. Will close.
