### ISSUE TITLE
If I create a pull request, do I have to use the develop branch?

### ISSUE THREAD

**Issue by Ricardo1980** [cocos2d/cocos2d-objc#1139]
If I create a pull request, do I have to use the develop branch?
I don't see docs about this.
dev or dev-4?
Thanks.

**Comment by cocojoe** [comment]
Typically it will be develop branch

On Friday, 26 December 2014, Ricardo Ruiz notifications@github.com wrote:

> If I create a pull request, do I have to use the develop branch?
> I don't see docs about this.
> dev or dev-4?
> Thanks.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/cocos2d/cocos2d-swift/issues/1139.

## 

Martin

**Comment by Ricardo1980** [comment]
Thanks.
