### ISSUE TITLE
CCTouch: previousLocationInNode and previousLocationInWorld are missing

### ISSUE THREAD

**Issue by LearnCocos2D** [cocos2d/cocos2d-objc#1203]
The "previous" variants for these two methods are missing:

```
- (CGPoint)locationInNode:(CCNode*) node;
- (CGPoint)locationInWorld;
```

Needed for when you want to get the direction of motion. Currently have to work around this with previousLocationInView() and manually convert the coordinate.

**Comment by s1ddok** [comment]
Gone with CCTouch. We now use UITouch natively since Android support is over.
