### ISSUE TITLE
CCScrollView issues on Android.

### ISSUE THREAD

**Issue by slembcke** [cocos2d/cocos2d-objc#1206]
v4 only. Probably due to theCCViewportNode changes.

**Comment by andykorth** [comment]
Yeah, that's almost certainly due to my changes. Lots of ifdefs in CCScrollView.

**Comment by slembcke** [comment]
Moving this to 3.4. Turns out most of the bugs exist in that branch.
- onScroll seems to exclusively receive move events, onFling seems to exclusively receive end events. Most of the code paths in these methods seem unreachable.
- There is no touch end event to trigger the bounce animations other than the fling event. Scroll past a boundary, stop your finger and lift. There is no event to end the scroll gesture.
- The Android code path does some coordinate space conversion that seems wrong. I think that is what causes the snapping bugs on the first touch, or a touch after a bounce animation.

The underlying Google OnGestureListener API seem to be mostly to blame, and is surprisingly incomplete. I'm not really sure how it's possible to make anything useful with them.

This pull request is relevant as well: #1154

**Comment by s1ddok** [comment]
Closed due to Apportable death.
