### ISSUE TITLE
Change WARNING: Image is flipped. Regenerate it using PVRTexTool

### ISSUE THREAD

**Issue by lrrrs** [cocos2d/cocos2d-objc#1215]
Since 3.1 you have to use flipped PVR textures (Took me quite a while to figure out...),
but when you use them you get a warning that's confusing:

CCTexturePVR.m:

if( flipped )
    CCLOGWARN(@"cocos2d: WARNING: Image is flipped. Regenerate it using PVRTexTool");

This needs to be changed into the opposite:

if( !flipped )
    CCLOGWARN(@"cocos2d: WARNING: Image is NOT flipped. Regenerate it using PVRTexTool");

This way I would have found the issue way earlier. So please think of other developers which will run into the same "strange" issues ;)

**Comment by s1ddok** [comment]
Edited warning in 3.5
