### ISSUE TITLE
Using many small textures results in black sprites

### ISSUE THREAD

**Issue by Birkemose** [cocos2d/cocos2d-objc#1262]
While adding several smaller sprites to a project, sprites suddenly start being rendered as full black.
Changing the file to a previous used file, makes the sprite show correct.

Add all the files to a sprite sheet, also makes the sprites show correct.

**Comment by Birkemose** [comment]
The problem is not using many small textures, but creating sprites in callbacks.

If ex. sprites are created in completion handlers, it will screw up the textures.

**Comment by slembcke** [comment]
What video API is the callback for? Is it happening on a background thread? As long as the callback happens on the main thread I don't know of anything that would cause it to break.

**Comment by Birkemose** [comment]
The functions called are ex.  
requestAVAssetForVideo  
generateCGImagesAsynchronouslyForTimes  
Everything seems to work, apart from (as far as I can tell), random sprites turning up as black squares. They always have the right size though, so I guess it must be a texture issue.

**Comment by slembcke** [comment]
That won't be calling on the main thread if it's asynchronous. Definitely not safe to call Cocos code in that.

**Comment by Birkemose** [comment]
A shame. There seems to be so much more async functionality in iOS8
