### ISSUE TITLE
CCLabelTTF shadow offset 'y' flipped on Android

### ISSUE THREAD

**Issue by rsfuller** [cocos2d/cocos2d-objc#1292]
It appears the y value of the shadow offset on a CCLabelTTF node is flipped on Android.

So if I set the shadow offset to {0,2}, it will be {0,-2} on Android (but correct on iOS).

Cocos2d v3.4 (SB v1.4.7)
Android v4.4.2
Device - Nexus 7

**Comment by s1ddok** [comment]
Android support is dropped.
