### ISSUE TITLE
Blurry CCLabelBMFont

### ISSUE THREAD

**Issue by sridenour** [cocos2d/cocos2d-objc#1321]
CCLabelBMFont appears blurry on non-Retina devices (such as nearly all Macs). I suspect that this is because the positions of the characters aren't lining up to whole pixels, and probably has something to do with the anchorPoint of each character sprite being (0.5, 0.5), so that if you have a glyph that's 29 pixels tall it will always be blurry.

**Comment by Birkemose** [comment]
Head over to the forum, and check this out

http://forum.cocos2d-objc.org/t/blurry-font-rendering-is-it-a-bug/10120

**Comment by sridenour** [comment]
Thank you for that link. I added a little code to detect non-Retina screens and automatically apply that fix. Will create a pull request for it.
