### ISSUE TITLE
Duplicates of existing methods?

### ISSUE THREAD

**Issue by gerchicov-bp** [cocos2d/cocos2d-objc#1327]
https://github.com/cocos2d/cocos2d-objc/blob/d00a7eca674f79e12e3d690c0f315cc689d7fd41/cocos2d/Support/CGPointExtension.m
for example oobjective c already contains `valueWithCGPoint:`. Could you explain what is the difference?

**Comment by slembcke** [comment]
OS X does not have that method. It's for cross-compiling compatibility.

**Comment by gerchicov-bp** [comment]
Thanks for explanation but it seems you include this code in both OSX and iOS

**Comment by slembcke** [comment]
That's a mistake then, is it causing a compiler warning in a particular Xcode version?

**Comment by gerchicov-bp** [comment]
sorry, I haven't a possibility to check it. I needed some inline functions only. But usually if the sources are for one platform only then usually they are surrounded with an appropriate macro in the same file. But I see such check for CGGeometry.h/Foundation.h files only.

**Comment by gerchicov-bp** [comment]
I've checked it by placing these two files into my project (not the whole cocos2d library). No warnings. Even the analyzer shows no warnings. But this code is called instead of the system one and it is incorrect.
As I understand at least this whole category over the `NSValue` class is extra for iOS.

**Comment by slembcke** [comment]
What's incorrect about the code? It should produce the exact same results as the implementation in Foundation. It really should have some #ifs around it though.

**Comment by gerchicov-bp** [comment]
It should produce the same code but these methods exist with system methods at once and this may cause unexpected behaviour even now:
1)nobody warrants that these methods will always work as now;
2)if you want to replace the existing methods you should use method swizzling not simply redeclare the same methods

Finally I agree with you that #if is the best solution

**Comment by s1ddok** [comment]
Fixed in 3.5
