### ISSUE TITLE
CCLayoutBox doesn't take into account transform of the node

### ISSUE THREAD

**Issue by s1ddok** [cocos2d/cocos2d-objc#1333]
As I see it CCLayoutBox ignores transform of the node such as scale property, for example.

Wouldn't it be better if instead of this 
    `float height = child.contentSizeInPoints.height`
We'd use something like 
    `float height = [child boundingBox].size.height`
?

**Comment by Birkemose** [comment]
It sounds reasonable that it should take scale into consideration, but I simply do not know what implications this would have on SpriteBuilder, so I am afraid we will have to leave it as this for now.

**Comment by s1ddok** [comment]
Fixed now in 3.5
