### ISSUE TITLE
Memory leaks

### ISSUE THREAD

**Issue by jezzmemo** [cocos2d/cocos2d-objc#1342]
I find the memory leaks very seriously,I run the very simple hello world project,the memory always increase ,i find the result by the instruments,if you run the simple demo half hour,the demo will crash by the memory warning.

Test the demo on the iOS8.4.1 and cocos2d v3.4.9 rc1 version.

**Comment by hgchrre** [comment]
Hi,

I haven't checked the demo but I've noticed big memory leaks in my project after upgrading to cocos2d 3.4.9 not long ago (iOS 9.1) and the allocated memory keeps increasing over time as you said. I'm no expert but according to Instruments, it seems to be coming from OpenGL buffers in my case. Not sure if it has something to do with what you're experiencing but it looks similar. I wasn't able to trace the issue back to my code, I'm kind of stuck right now.

What I get when I use Zombies :

<img width="1283" alt="fullscreen_27_10_15_22_26" src="https://cloud.githubusercontent.com/assets/8337591/10773673/0b79917e-7cfd-11e5-8ab2-79abbc20fcc6.png">
<img width="1283" alt="fullscreen_27_10_15_22_27" src="https://cloud.githubusercontent.com/assets/8337591/10773681/1b9ffd18-7cfd-11e5-9f48-c39b6c45b098.png">

And when using the OpenGL tool, the number of "Uninitialized buffer data" warnings keeps increasing too (400000 after a minute or so) :

<img width="1300" alt="fullscreen_27_10_15_22_30 2" src="https://cloud.githubusercontent.com/assets/8337591/10773728/585beec4-7cfd-11e5-868c-ec2d800e90da.png">

**Comment by jezzmemo** [comment]
@hgchrre You analyze very clearly,I thank it is big bug,please cocos2d-objc's author value this problem,give us some solution.

**Comment by nader-eloshaiker** [comment]
I suspect Lars might be too busy with preparing the kickstarter for Cocos2D-Swift to dedicate time for this. Fixing this might have to come from the community.

**Comment by richardgroves** [comment]
@lijie250 you say 'I run the very simple hello world project' can you post a ZIP of that? More recent versions of the library have been a bit variable at making the template project.

@hgchrre - is there anyway you can isolate out an example project that exhibits the behaviour you are capturing in instruments. I've checked and my code goes through that same CCGraphicsBufferGLUnsynchronized path that you show, but I don't get zombie's showing up.

**Comment by jezzmemo** [comment]
@richardgroves I uploaded the simple zip project,
the zip link:https://www.dropbox.com/s/5r2ai8rgazl2qzd/hello.zip?dl=0
I just test the project by the instruments,the memory always increase,I thanks it is really leaks.

**Comment by hgchrre** [comment]
@richardgroves False alarm, my bad — everything except my project works fine, in my case the issue appeared because I broke something, I upgraded my Spritebuilder project from cocos2d 3.4.something to latest 3.4.9 without actually changing the cocos2d.xcodeproj project file. I just replaced the "cocos2d", "cocos2d-ui" and "external" folders (I followed [these instructions](https://www.makeschool.com/tutorials/update-cocos2d-for-xcode-7-and-ios-9)).

@lijie250 I ran your example project on an iPhone 6s with iOS 9.1 and memory remains stable. Maybe it's iPad specific?

**Comment by richardgroves** [comment]
@lijie250 I'm seeing the same as @hgchrre with that Hello project. A tiny single leak on the simulator iPad2@ios9.1:
![screen shot 2015-10-29 at 11 17 07](https://cloud.githubusercontent.com/assets/715058/10816989/bc8b4bf6-7e2e-11e5-8b6b-a09089657172.png)

And nothing on an iPad3 running iOS9.0:

![screen shot 2015-10-29 at 11 16 51](https://cloud.githubusercontent.com/assets/715058/10817002/d322751a-7e2e-11e5-827c-488f7b696c16.png)

Can you upload some screenshots from instruments showing the leaks and the backtrace for them?

**Comment by jezzmemo** [comment]
First screenshot:
![1002bb86-3124-439c-ad78-c9557a904657](https://cloud.githubusercontent.com/assets/492962/10817164/162133e4-7e73-11e5-83d1-97e7a8788ddc.png)

Two minutes later：
![f8cb0659-4d67-4c42-a118-2b2b764c79f2](https://cloud.githubusercontent.com/assets/492962/10817180/3814d9ec-7e73-11e5-9b9b-b8308fea5b69.png)

**Comment by richardgroves** [comment]
Thanks for the quick response @lijie250 

Your screenshots don't show any leaks though - look at all the nice green ticks in the 'Leak Checks' row.

The 'persistent bytes' column nudges up a little, but that is normal, and it will fluctuate around as you go from scene to scene, and as the engine caches stuff in.

The 'total bytes' column has gone up - but that is not a leak, it is just a record of all the memory allocated by the app - subtract the 'persistent bytes' from it and you can see how much is freed.

So if the code does:

[start]
A = allocate 1k
B = allocate 2k
C = allocate 4k

[total persistent bytes = 7k, total bytes = 7k]
free A
[total persistent bytes = 6k, total bytes = 7k]
A = allocate 1k
[total persistent bytes = 7k, total bytes = 8k]

free A
free B
free C
[total persistent bytes = 0k, total bytes = 8k]

nothing leaked, just an indication of how much 'churn' there was in the memory.

[side track: on 32 bit systems it can (very very rarely) be an issue to churn the memory as the virtual memory space gets fragmented, and the OS can have problems mapping free pages back into a space for the process. Given objective-C has lots of small allocations of roughly the same size this is even more unlikely to happen on iOS: or rather the total_bytes count can get very very high before you'll have an issue]
