### ISSUE TITLE
Can‘t find CCWaves in cocos2d-objc v3.x

### ISSUE THREAD

**Issue by amitkumar3968** [cocos2d/cocos2d-objc#1357]
I can't find something like CCWaves(or CCLiquid etc) class in cocos2d v3.x.

but they are exist in cocos2d 

so, is it really disappear in cocos2d v3.x? and are there some replaceable class i can use？

thanks！ ;)

**Comment by s1ddok** [comment]
Those are gone, we use shaders now. Take a look at shaders cookbook.

https://github.com/slembcke/Cocos2DShaderCookbook
