### ISSUE TITLE
ios9 Chipmunk physics breakdown (release build only)

### ISSUE THREAD

**Issue by clickstan** [cocos2d/cocos2d-objc#1358]
Update (I'm using cocos2d 3.4.9 latest): I've notices that the physics breaks down in ios9 RELEASE BUILD (nan positions, random duplicated incorrect collision calls, NOT due to errors in my code!, on 64bit devices ONLY, NOT on the simulator/32bit devices) only after compiler optimization for the Chipmunk7 project, turning it off fixes it! (Good enough until better solution arrives) 

There must be something in ios9 compiler optimization that broke something in chipmunk, because the same app compiled for ios8 work perfectly. (I've debugged it down to _body.transform turning Nan after a collision)

If a fix in the meantime is impossible, at least maybe turn off the complier optimization in chipmunk so newbs dont get trolled on app release. Thanks. I'll happily provide more info on this if needed, reference thread: http://forum.spritebuilder.com/t/solved-bug-with-physics-only-for-release-scheme/16396/5)

**Comment by s1ddok** [comment]
As far as I remember it is related to fast math optimizations. Somebody should create a PR into Chipmunk repo to fix this.

Chipmunk won't be bundled by default in 3.5 and is served separately, so I will close this one as there is no solution related to cocos2d.
