### ISSUE TITLE
How to create two separate views respectively according to different scenarios？

### ISSUE THREAD

**Issue by fengyecsg** [cocos2d/cocos2d-objc#1389]
We want to use two independent view in the APP to show animation content, but now there is only one singleton CCDirector, excuse me is there a way to solve our needs?

**Comment by s1ddok** [comment]
Unfortunately not.

We have this implemented in v4 (see `develop` branch), but you have to be power user to use it.  And you will also likely need to port your game code to a newer version + fix bugs when you catch them. 

I use v4 in some of my projects, but that's a different story.
