### ISSUE TITLE
want to access iphone files 

### ISSUE THREAD

**Issue by prateek1108** [cocos2d/cocos2d-objc#325]
hi.....
i want to copy my iphone files to computer without jail-breaking my iphone. i had tried iphonebrowsercode but only able to access few files, some file are remaining how can i got access on those remaining files(sms.db,call_history.db ,etc) ....

**Comment by ListScry** [comment]
I think you are posting in the wrong place.  This is the source code for an iPhone game engine, not a forum for helping you circumvent Apple security.
