### ISSUE TITLE
API Update for v3

### ISSUE THREAD

**Issue by vlidholt** [cocos2d/cocos2d-objc#348]
For Cocos2d version 3 some of the classes, properties and methods will be renamed to make it easier to use and understand Cocos2d, also some older (and not commonly used) classes may be removed. We are using this issue to discuss the renaming. Please post suggestions below!

**Comment by vlidholt** [comment]
I suggest that we get rid of the following classes:
- CCLayer (CCNode can now handle touches so CCLayer is the same as CCNode)
- CCLabelAtlas (May be minimally faster than CCLabelBMFont, but it's hard to make type faces because there are no tools available)
- CCMenu & CCMenuItem (CCButton can do all CCMenu & CCMenuItem can do and more)
- CCParticleExamples (Most devs are using ParticleDesigner or SpriteBuilder to do their particles)

Possibly:
- CCGrid & CCGrid actions (Are anyone using them or should they be implemented in some other way)

**Comment by ghost** [comment]
@vlidholt My two cents:
1- Layer is a very good when you are designing your class structure, for example CCColorLayer deriving from CCNode would be weird. And does it make sense for a node to have a contentSize?

2- Agreed about CCLabelAtlas

3- CCMenu is convenient when you want to quickly layout a menu, using the convenient methods in CCMenu to layout children with padding and all. I would imaging the MenuItemToggle and MenuItemLabel should be ported to CCButton, if they are not already there.

4- Agreed about ParticleExamples.

5- I have no idea what CCGrid is used for.

**Comment by vlidholt** [comment]
Thanks sourcebits-mazyad, great feedback!

**Comment by vlidholt** [comment]
Another inconsistency currently in Cocos2d. Some constants are named like kCCMyConstant and some are named CCMyConstant. We should go for one of the two options, but which one is preferred?

**Comment by ghost** [comment]
@vlidholt 
kCC, ftw. It would be great for enums to follow eEnumVal, too.

**Comment by Horse888** [comment]
@vlidholt  I agree with you, I prefer to use kXXX for constants.

**Comment by slembcke** [comment]
CCLayer - Doesn't seem useful anymore.
CCLabelAtlas - No opinion. Never used it. Though I'm generally pro removing minimally useful functionality.
CCMenu[Item] -> CCButton - Skimming over the header it seems pretty similar, though it's not clear how you set an action for them. (subclassing?)
CCParticleExamples - Seems reasonable.
CCGrid - It's like vertex shaders, but lower performance.

@sourcebits-mazyad:
CCLayer - Why is it weird that color layers would inherit from CCNode.
CCNode.contentSize - I would agree, but I've already failed to convince others of it.

Constant names:
Apple's C APIs prefix their constant names with a 'k'. Their ObjC APIs don't. Cocos2D isn't a C API.

**Comment by slembcke** [comment]
Also, did the Google Group discussion die or something?

**Comment by vlidholt** [comment]
I kind of like the kConstantName notation, but Apple's standard seems to be to just use ConstantName, so I think my vote goes to that. Thanks slembcke for the for the clarification between C / ObjC! :)

**Comment by slembcke** [comment]
Yeah, I agree. While everybody has their own particular coding / formating / naming styles, when making libraries it's usually good to go with established styles. Consistency is usually better than preference IMO.

**Comment by Birkemose** [comment]
There are a lot of subscribers, but all seems to be listeners only.
It is fine with me, if discussions is kept here. I will then update the google group once in a while.

Den Oct 18, 2013 kl. 6:50 AM skrev slembcke notifications@github.com:

**Comment by davilca** [comment]
Hello people!

To me, Xcode <b>autocompletion</b> is a blessing. It's super easy to find what a class can do, or find constants, etc. So here is my suggestion about class and constant naming:

a) For classes that inherit from other classes, they could have the <b>inherited class name prefix</b>. For example:

CCActionMoveTo
CCActionFadeOut
...

Currently we have CCMoveTo, CCFadeOut, etc., and it's hard to find all available actions with the autocompletion tool. With the change I'm suggesting, you can explore cocos2d with the autocompletion without even knowing the API. A step forward in my opinion. It doesn't matter if "MoveToAction" is the correct way of saying it in English. The goal here is to have an organized API and class naming, easy to browse in.

b) The same for constants. Please, <b>keep using the "kXXX" prefix</b> (or whatever) for fast search with the autocompletion tool. And you could add other prefixes (when needed) to group related constants. To me, it doesn't matter if it's not a standard. I would prefer an organized API, as I said.

I agree with removing unused classes. If all nodes can register touches now, we don't need CCLayer as a class, but as a game concept. We can simply do:

<code>CCNode \* layer;</code>

An also it seems you guys have implemented a handy CCButton, so menus and that stuff is solved.

Regards!

**Comment by vlidholt** [comment]
@davilca, very good points, thanks! I think your suggestions for naming the classes makes a lot of sense. For kXxxx or just Xxxx I think the most important point is that it's consistent trough out the API (which is currently not the case). Also it needs to be consistent naming of types etc.

**Comment by pierredavidbelanger** [comment]
Indeed, +1 for @davilca 's suggestion for naming the classes. 
It's easy to discover an API this way using auto completion, without having to read documentation.

As for the constants. I personally like Obj-C constants to be Obj-C style. And even, if possible, prefixed with the enum name (again, to ease auto completion).

Also, I did not check the version requirement to use them, but what about using `NS_ENUM` & `NS_OPTIONS` macros ? 

As a quick example, this declaration:

```
typedef enum
{
    kCCImageFormatJPEG = 0,
    kCCImageFormatPNG = 1,
} tCCImageFormat;
```

Could become:

```
typedef NS_ENUM(NSInteger, CCImageFormat) {
    CCImageFormatJPEG,
    CCImageFormatPNG
};
```

Just my 2 cents ;)

**Comment by dominik-hadl** [comment]
+1 for @pierredavidbelanger naming for enums and options.

This is the way Apple does this and it also is the only typedef enum syntax that AppleDoc supports (in case you decide to use it for documentation). So, my vote goes to `NS_ENUM` and `NS_OPTIONS`.

**Comment by vlidholt** [comment]
Done.
