### ISSUE TITLE
CCScheduler improvements.

### ISSUE THREAD

**Issue by slembcke** [cocos2d/cocos2d-objc#354]
Due to adding integrated physics, it's a necessity to add fixed update methods now. It's _possible_ to do without them, but SpriteKit makes a pretty good case study for why it's an _awful_ idea. (SpriteKit uses variable timesteps exclusively. Your simulations tend to break if the framerate drops.)

That by itself could be patched into the existing CCScheduler, but I think it might be time for some upgrades:
- CCNodes with an "update" method defined should work without needing to manually add and remove them from the scheduler. This could be done by making it an optional method in a Protocol. Same for fixedUpdate methods.
- The API is not block friendly. IMO, the target/selector API should be replaced in favor of blocks. Maybe that's a little extreme, but it's trivial to just call a method from the block if that's all you want, and it would solve the ever present "How do I pass an argument to a timer?" question. Several of Apple's APIs (like CoreAnimation) have deprecated their target/selector variants in favor of block based APIs.
- Should nodes inherit their parent's scheduler instead of the director's scheduler? Otherwise the use case for multiple schedulers seems harder to use correctly than it needs to be.
- It's not possible to schedule a timer to be invoked more often than the framerate (which is not fixed).
- CCScheduler doesn't track the current time, time since the last update method, etc.
- Timers are mildly expensive to have waiting to be invoked. Having a thousand of them ticking uses a fair amount of CPU time.
- While timers can be scheduled for a fractional frame time, there is no way to access what time they were supposed to be invoked at. A really basic use case is firing 50 evenly spaced bullets per second when. At 60 fps with no inter-frame time available, you'll end up with either 10 gaps or bullets fired at not-quite 30 times a second.
- Scheduling methods don't return the timer object they are based around. This is quite useful in the NSTimer API.

I have some existing code for timers based around a heap structure that solves the last 5 issues in particular.

**Comment by vlidholt** [comment]
I think this can be a good idea! Some things that might be needed to take into consideration:

1) What happens if the code is too slow to be processed at the specified time step?
2) Will all callbacks be on the main thread? (it probably should)
3) I think it would be a good idea to cache which classes implements the update method as the 'respondsToSelector' call may be slow and it would be better not call it every update cycle.
4) I don't think there is a need for multiple schedulers. Just visit all childs with the update method implemented which are currently in the scene graph. Current implementation is unnecessarily complicated and could use a rewrite.

My suggestion is to just have the user override 'update' and/or 'updateFixedTimestep' (or if someone can come up with a better name) and add the possibility of setting the framerate for the fixed timestep in CCDirector.

**Comment by slembcke** [comment]
1) The general solution to that is to have a maximum allowed timestep at the gameloop level.

```
// CCScheduler update: method pseudocode
-(void)update:(ccTime)deltaTime
{
    // Clamp the maximum time allowed in a timestep.
    // That way the game slows down if there's too much work to keep up.
    deltaTime = MIN(deltaTime, maxTimestep);

    _currentTime += deltaTime;

    // Keep invoking timers until the top timer is fired in the future.
    while(_heap.top.invokeTime < _currentTime){
        // A timer may reschedule itself to run again.
        // So a single timer may be processed multiple times in this loop.
        CCTimer *timer = [_heap removeTop];
        [timer invoke];
    }

    // Fixed updates would simply be implemented as a timer above.
    // That way other timers could be invoked correctly in between them.

    // Finally
    [self callUpdateMethods:deltaTime];
}
```

If there is too much to process in a single update, the game will slow down instead of the framerate getting progressively worse.

2) Callbacks should absolutely be on the main thread. Anything else is asking for trouble and extreme confusion from inexperienced users (and experienced ones too).

3) My thought was to schedule node instances that implement the update:/fixedUpdate: methods in onEnter like a user would do anyway. Priority would be set by overriding a method that defaults to returning 0. 

4) Multiple schedulers is a very good idea IMO. The use case that has come up nearly once per game for me is pausing the game while animating a UI. Very difficult to do with a single global object for managing time. Unity has the same problem.

**Comment by slembcke** [comment]
It might be worth refactoring CCActionManager to be a part of CCScheduler though. Since action managers are scheduled with a scheduler, it doesn't make a lot of sense to allow them to be set separately per-node. Action managers are really a user-ended class though so this could be done whenever.

**Comment by MKGitHub** [comment]
For example; if some frames are dropped say we are running at 60 fps, but got just 55 frames the for the last second – will these 5 frames be run for their logic before getting back to main loop/rendering?
This way the logic must always run 60 times, but the drawing is allowed to suffer at a lower rate due to some frames taking to much time to complete.

**Comment by slembcke** [comment]
@MKGitHub Pretty close. If there is too much happening on the CPU, first the framerate will begin to drop to free up some CPU time to run the fixed updates at the correct speed. If the framerate falls below a minimum value, then it will start slowing down the fixed updates as well.

This is coming along pretty well. Most of the functionality is working now, and I've been writing unit tests. I pushed my branch to GitHub if anybody has time and wants to take a look at it:
https://github.com/cocos2d/cocos2d-iphone/blob/ccscheduler/cocos2d/CCScheduler.h
https://github.com/cocos2d/cocos2d-iphone/blob/ccscheduler/cocos2d/CCScheduler.m

At this point it's basically a complete rewrite. I made the CCNode methods mostly backwards compatible (as close as possible since behavior of short timers is changing). Anyone have thoughts if I should reimplement the CCScheduler methods? I was thinking I should and mark them as deprecated, although I think it's pretty rare to use the CCScheduler API directly.

**Comment by vlidholt** [comment]
I think rather than having multiple schedulers exposed to the user, there would be useful to be able to set a paused property on a node, which would disable all actions on that node and its children. That would make it very easy to pause the game, while the UI continues to run.

**Comment by vlidholt** [comment]
Also, if we are rewriting this, we should move away from the 'imp'-stuff, according to the engineers here that is not a good solution. Either use objc_msgSend or even better just call the 'update' selectors.

**Comment by slembcke** [comment]
Can't run unit tests on device, but can get a rough performance number anyway. One test schedules 1000 timers each repeating on a random interval 1000 times over 1000 seconds. Time was stepped at 60Hz (so 60k timesteps). On my i7 Air it took 12 seconds to schedule and step through all 60k timesteps. I'll set up a test against the original version to compare later.

It's interesting to note that the according to the profiler, > 75% of the CPU time is spent doing reference counting, and near as I can tell, almost all of that is redundant ARC checks due to shuffling timers around in the heap. I might attempt to rewrite it using a strong CCTimer C array, but I don't suspect that will help very much. Rewriting the file using MRC might seriously quadruple the performance if it's an issue.

**Comment by slembcke** [comment]
Children being paused by their parent is problematic. The two options I can think of:
1) Set the paused property recursively, overwriting any value it had previously.
2) Check recursively somehow if an ancestor is paused. Not sure how do do this efficiently really.

#1 breaks things, and #2 seems like it can't be implemented efficiently. Thought: I guess paused could be a count instead and called in pairs like retain counting. That would solve #1's problems maybe?

What's wrong with using method implementations? I already use them pretty heavily in Chipmunk to interact with ObjC from C. They are a standard part of the runtime, enough so that NSObject even has them in it's API. I was already using them in the rewritten scheduler, but they could be taken out easily enough if there is a good reason.

Since you already have to do funky pointer casting of objc_msgSend()/objc_msgSend_stret(), I don't see why one wouldn't just cache the IMPs and cast those instead.

**Comment by phausler** [comment]
Caching imps is generally a bad idea (there are only certain points where I consider that the right thing to do) since it can easily have a disassociation from the receiver; the target may get deallocated and then another pointer in the exact same spot (of a different class) will be allocated and you will get a improper invocation very easily. Ideally this should be messaged directly to it's common class/protocol. I.E CCNode pointers. The objc_msgSend casts are just there to simulate what it would do naturally without any direct type information. Primarily this is due to the fact that the uthash backing this is not typed to that currently. Which I would strongly suggest NSMutableDictionary instead (even though it is technically slightly slower, it is much more safe).

**Comment by vlidholt** [comment]
Ok, I have given this some serious thought and had long discussions with the other engineers around the office. This is what I suggest for how the CCScheduler could work: The CCScheduler itself would be a private class and not commonly called directly by API users. The API would look similar to this:

**CCNode**

```
- (void) update:(dt)
```

This method is called on every frame or time step, if the node is in the current scene graph. The order of which the nodes are called is not defined.

```
@property (nonatomic,assign) BOOL paused
```

If set to YES, this node and all it's children/descendants are paused and _update:_ will not be called and animations/particle systems will not be run. (Default value is NO)

**CCScene**

```
@property (nonatomic,assign) BOOL useFixedTimestep
```

If set to YES, calls to physics, actions and update methods will be called at a fixed interval and frames will be dropped if the CPU cannot keep up. (Possibly this property could be on CCDirector.)

```
@property (nonatomic, readonly) ccTime secondsPerTimestep
```

Sets the length of the fixed time steps (ignored if useFixedTimestep is NO)

```
- (void) didEvaluateActions
```

Called after actions have been evaluated, but before the physics simulation.

```
 - (void) didSimulatePhysics
```

Called after the physics simulation.

Callback order would be similar to SpriteKit; update, run actions, didEvaluateActions, simulate physics, didSimulatePhysics, render the scene (unless useFixedTimestep is set and a frame needs to be dropped).

If the user needs to call something after a delay, NSObject's performSelector:withObject:afterDelay can be used (there is no need to duplicate this functionality in Cocos2d).

Implementation
CCScheduler maintains a list of nodes that has overridden the update: method. This list is updated when a node is added or removed, when a new scene enters/exits or when the paused property is being modified (when changed it only needs to go through it's children and remove/add them from the list). A similar list is maintained for nodes that are using actions.

To check if the update: method has been overridden code similar to this can be used:

```
if([node methodForSelector:@selector(update:)] == [CCNode instanceMethodForSelector:@selector(update:)])
```

We need to ensure this works with transitions too when two scenes can be running simultaneously (maybe there should be a scheduler per scene or more of the scheduling logic should be in the scene).

**Comment by slembcke** [comment]
@phausler
If you are passing a dangling pointer to an IMP function because you didn't retain it, then passing it to objc_msgSend() is just as bad. The only real difference is that in the unlikely case that the address does get reused by another object, you'll get a confusing exception to accompany the crash.

On the other hand, going from this:
scheduledTarget->_fixedUpdate_IMP(scheduledTarget->_target, FIXED_UPDATE_SELECTOR, timer.repeatInterval);

To this:
[scheduledTarget->_target fixedUpdate:timer.repeatInterval];

That does seem like a good enough reason. It's not as though caching the IMP was for the performance really... So good riddance I say!

Already switched to using CFDictionaries (to avoid NSCopying issues with NSDictionary keys). Was more than happy to get rid of the uthash code. If you are implementing templated types using C macros you might be using the wrong language. O_o

@vlidholt
It's already pretty close to being a private API. I think it's pretty rare to interact with it directly. On the rare occasion I've used it to schedule timers on things that aren't CCNodes, but otherwise people seem to just use the CCNode convenience methods exclusively I trimmed down it's API and implementation to be pretty minimal, but cover most of what it did before. There were some really odd methods with limited utility there.

The protocol for scheduled objects I made looks like so:

```
@protocol CCSchedulerTarget<NSObject>

/// Used to break ties for scheduled blocks, updated: and fixedUpdate: methods.
/// Targets are sorted by priority so lower priorities are called first.
@property(nonatomic, readonly) NSInteger priority;

@optional

/// update: will be called automatically every frame if implemented, and the node is "live".
-(void) update:(ccTime)delta;

/// fixedUpdate: will be called automatically every tick if implemented, and the node is "live".
-(void) fixedUpdate:(ccTime)delta;

@end
```

(More in the links I posted above. Pretty close to done already.)

If the methods are implemented, they are scheduled. If not, then they aren't. Using either, neither or both is entirely optional. Can't get much straightforward than that. No need to have an empty update: implementation in CCNode. As for a property to force using a fixed update that is coupled to the framerate, that generally works poorly. While you can get away with having only variable time steps for a lot of games, having only a fixed time step isn't very useful unless it's locked to the rendering which makes for a lot of other problems. It ends up being a lot like "racing the beam", but you get unpredictable amounts of CPU time.

The SpriteKit style -didEvaluateActions and -didSimulatePhysics methods are a pretty good idea though. I suppose we could just add more optional methods to the CCSchedulerTarget protocol.

There is no physics engine I've ever heard of that encourages using variable time steps, yet that is what Apple has done with SpriteKit. I would not emulate their update loop. Currently the new scheduler works roughly like this:
- Call fixedUpdate: methods. (These update logic or physics values)
- update physics. (actually a fixedUpdate: method with NSIntegerMax priority so it runs last)
- Could call a didSimulatePhysics event method here.
- Go back to step 1 if necessary.
- Run actions (Currently implemented as a regular update: method with NSIntegerMin priority so it runs first)
- Could call a didEvaluateActions event method here.
- Call update: methods. (Used for updating animation or things that don't need to be deterministic)
- Render

My personal experience is that splitting up the fixed/variable updates this way works best. Structuring it this way also automatically limits the frame rate without doing any real work. Unity and Unreal's main loops work the same way.

The relevant code is here:
https://github.com/cocos2d/cocos2d-iphone/blob/ccscheduler/cocos2d/CCScheduler.m#L405

(updateTo: is what calls the timers, the fixedUpdate: methods and ticks the physics. Actions are run as an update: method.)

NSTimers and games don't really mix. You can't pause them, you can't apply a timescale to them, they can't be properly sequenced with other timed events in the game (such as fixed updates), and perhaps most importantly they run on wall time and not the game's time. NSTimers have no way to know if the game stuttered due to loading some textures or because a notification popped up. That will cause timers to get out of sync with the game.

Implementation: Already works that way except for pausing. After thinking about it I've definitely warmed up to the idea of pause counters. It solves the overwriting issue. Pausing a child and parent node separately will work more or less as expected. Both will need to be unpaused for the game to continue. I would not mind merging CCActionManager into CCScheduler, but that is perhaps for another day. That looks to be as many changes as I've done already. (Definitely not time for that.)

One scheduler per scene: I was thinking the exact same thing actually. It doesn't really make sense to have a global scheduler. The downside is that you can't schedule timers before adding something to a scene. The only thing it prevents is having timers persist across scenes, which is quite awkward right now anyway.

Also of note, I somewhat randomly noticed there was a CFBinaryHeap type (Who knew?!) and used that instead of my own heap code. Swapped that in quick and it runs many times faster now since it avoids all of the ARC hullabaloo.

Can't think of anything else. Will work a bit more on unit tests before going to bed tonight. Seems to be pretty solid already. Will merge it into the CCPhysics branch tomorrow unless there are problems.

**Comment by vlidholt** [comment]
I had a quick look right now, overall the changes look pretty good. Some feedback:

1) As far as I can tell, adding a node currently changes the paused property, this is not a good solution. A programmer should be able to first set the paused property then add it to the node graph and expect it to be paused.

2) In some places in the code C-functions are being called. In _very_ rare cases this can be necessary for optimizations, but generally Obj-C methods should be used to make the code more readable.

Might have some more feedback after continuing to review the code/concepts.

**Comment by slembcke** [comment]
1) Was recently pondering that. That's how it worked before, and it's problematic. In the old code, timers/actions are added as paused before onEnter is caused and it then resumes them in onEnter. So there are multiple things controlling the "paused" state of actions/timers in conflicting ways... My changes to that haven't proven better.

2) I disagree. There are a lot of C functions in Apple's ObjC APIs. Using a static helper function in ObjC is akin to using a static helper method in Java/C++/C#. If it doesn't access any ivars or change any object state it shouldn't be a method. Of the three functions in CCScheduler.m, all of them are helper functions for operating on a list. Methods aren't inherently more readable than small functions as part of a private API.

**Comment by vlidholt** [comment]
1) This needs to be fixed one way or another before the release.

2) This is more a matter of coding style. Personally, I think that it is more readable if everything is written in Obj-C, for methods/functions that should be static, there is a + sign for that. But, not a big deal.

**Comment by slembcke** [comment]
On the topic of #1, I've been thinking about that in the back of my mind. I feel like the solution might be to change the definition of the isRunning property slightly. Right now, isRunning is true only while a node is added to a running scene. To me that's a poor naming choice since a paused node can still be considered running if it's in a scene.

Instead, if isRunning was true only when:
- The node is added to an active scene.
- The node nor any of it's ancestors is paused.

This is really what I would expect a property named isRunning to mean (with or without the ancestor paused part). The implementation is simple enough, internally the ivar for isRunning would be a counter that starts with the value 1. Decrement the value in onEnter, and increment it in onExit. When setting a node to paused, increment the isRunning ivar on the node and all of it's descendants. When unpausing decrement it. If the value is changed from 1 to 0, the the node has just began running again due to either unpausing it or adding it to an active scene. Unpause the node's actions, updates and timers. If the value is changed from 0 to 1, then the node has either been removed from a scene or paused and is no longer running. Pause the actions, updates and timers for the node. Any other changes would be ignored. For example, unpausing a node that isn't in the scene shouldn't do anything. This would fix the existing bug where cocos will unpause a node node when adding it to a scene even if you explicitly paused it.

The only real question is, should we:
- Change the behavior of isRunning.
- Add a new property (ex: isActive) with the new behavior.
- Add the new property and remove isRunning.

I'm sort of leaning towards the third option. Since the behavior is new, and the existing isRunning behavior seems slightly broken to me I feel like it's better to simple replace it. Binary compatibility isn't that big of a deal since Cocos is never dynamically linked. Otherwise I think this is the last issue that is blocking merging that I know of.

One more thing to think about. I never made the 1:1 scheduler to scene change. It has the side effect of preventing you from adding actions or timers in an init method since there is no way to access the scene of an node that has never been added to one. It would make it mandatory to add them in the onEnter method. Encouraging people to move some initialization to onEnter is a good idea (for several reasons), but it's not always practical as a hard rule.

**Comment by vlidholt** [comment]
I also think the isRunning property naming is mis-leading, maybe we should rename it to 'addedToActiveScene' or something (or even remove it's public interface). A paused property could definitely be very useful, and the implementation that you propose sounds like it would work.

**Comment by slembcke** [comment]
Just wrapping that up now. Went pretty well without any more unexpected issues. The basic change can be seen here:
https://github.com/cocos2d/cocos2d-iphone/commit/9cd0fa605ca421e23cf71e4f989a1c65f5b30806#diff-d927d24cfedfefe08730e96a9ccb9e56

The _isRunning ivar was renamed to _isInActiveScene. The isRunning property now includes reflects the paused state of a node and it's ancestors. Which I think does more or less exactly what you would expect.
