### ISSUE TITLE
Shader based transitions

### ISSUE THREAD

**Issue by vlidholt** [cocos2d/cocos2d-objc#361]
Add support for a number of new transitions based on the new shaders.

**Comment by Birkemose** [comment]
I paused work on this, as I wanted to wait until we had agreed on how to implement shaders.

**Comment by vlidholt** [comment]
Moving to 3.2

**Comment by slembcke** [comment]
Looks like this is getting bumped again. I think somebody just needs to take a "workation" week, have some fun making a couple dozen simple transitions and make an API that they can all use. Might not ever be high enough priority to get done otherwise.

**Comment by slembcke** [comment]
Issue #518 suggests customizing the transition easing curve. A simple, but good idea.

**Comment by s1ddok** [comment]
It is possible now in 3.5.
