### ISSUE TITLE
Updated tutorials

### ISSUE THREAD

**Issue by vlidholt** [cocos2d/cocos2d-objc#363]
Update (some) of the Cocos2d tutorials on raywenderlich.com to Cocos2d v 3.

**Comment by Birkemose** [comment]
One of the things I really want to do, is to make a demo game - like SK's Adventure - to demonstrate cocos2d, and how to use V3.

**Comment by cocojoe** [comment]
It would be great for the future cocos2d site to have a tutorial section similar to Unity 3D 'learn' section with a range of tutorials, a showcase demo game tutorial would be great.  I would rather have more eyeballs on the cocos2d site.

Having actual cocos2d engineers contribute tutorials/videos is great for community engagement. Something I will be doing as well.

**Comment by Birkemose** [comment]
With the chance of repeating myself, top of my “would like todo” list, is to make a small game demo, like SK’s Adventure.

I would call it “Big Adventure” …
