### ISSUE TITLE
CCScrollView delegate?

### ISSUE THREAD

**Issue by diegorozen** [cocos2d/cocos2d-objc#380]
Is there a way to get notified about the scrolling start/end of a CCScrollView (similar to UIScrollViewDelegate)? I couldn't find in the headers of the V3 implementation. If not, are there plans to implemented?

Thanks!

**Comment by dominik-hadl** [comment]
I would also like to know if there is anything similar to Apple's UIScrollViewDelegate for CCScrollView. I wasn't able to find anything in the headers too.

**Comment by chrene** [comment]
I implemented CCScrollViewDelegate, and I will make a pull request soon

**Comment by slembcke** [comment]
This was apparently resolved.
