### ISSUE TITLE
CCLayout + CCButton to replace CCMenu?

### ISSUE THREAD

**Issue by Ben-G** [cocos2d/cocos2d-objc#395]
Currently CCMenu is removed. My understanding is that CCLayout/CCLayoutBox will cover the layout options that CCMenu provided (align vertically, align horizontally). I support that idea, since CCLayout can be used to layout any kind of node not only CCMenuItems.

However, currently CCLayout/CCLayoutBox are not yet part of develop-v3. Will they be added soon?

**Comment by Birkemose** [comment]
Layout is part of v3, and as you say, will replace ccmenu / ccmenuitem

**Comment by Ben-G** [comment]
Thanks for clarifying.
