### ISSUE TITLE
Old cocos2D tests

### ISSUE THREAD

**Issue by andykorth** [cocos2d/cocos2d-objc#398]
It looks like just about none of the old Cocos2D tests compile, although bringing many of them up to date wouldn't be too hard (mostly just removing references to CCLayer), etc. Unless folks here would rather see them removed, I can start updating some of them so they compile again.

**Comment by vlidholt** [comment]
The structure for the old tests are really hard to maintain, with the hundreds of targets and all. The plan is to move any relevant tests to the new UI-tests, then rename the UI-tests to just tests.

**Comment by Ben-G** [comment]
I think it would be great maintaining the tests. They are great when testing potential changes.

**Comment by andykorth** [comment]
Sounds good. The mess of targets is a huuuuuuuuuge pain, so anything we can do to move away from that is a plus.

I'll move the relevant tests into the ui-tests project.

Is there any reason the ui-tests aren't in the workspace? Perhaps adding ui-tests to the workspace and removing the non-compiling old test project would be nice. At least that will massively clean up the target list in the workspace.

**Comment by andykorth** [comment]
Spoke with Viktor last night:  A few highlights: If possible/applicable, some of these tests could be run automatically, screencapped, and compared to "known-good" screenshots. So if a test can be written without animation, I'll try for that. 

As mentioned above, the old "cocos2d-tests-ios" project will be removed, and the "cocos2d-ui-tests" will be renamed to just tests, and be added to the workspace. The target list for the workspace will be much cleaner, and hopefully the tests will be compiled more regularly (and perhaps even run!). 

When possible, I'll favor unit tests over these tests, which need to be individually inspected.

**Comment by andykorth** [comment]
See https://github.com/cocos2d/cocos2d-iphone/pull/417 for the big organizational commit - removing old tests, renaming new tests.
