### ISSUE TITLE
Multiple "implicit conversion" warning on 64 bit build

### ISSUE THREAD

**Issue by zaerl** [cocos2d/cocos2d-objc#399]
I'm compiling the OS X project generated by `install.sh` (develop-v3.) I have multiple warnings:

```
Implicit conversion loses integer precision: 'NSUInteger' (aka 'unsigned long') to 'int'
```

This is due to the fact that a `NSUInteger` is `#define`'d to `unsigned long` on a 64 bit systems. I know that it's only log noise but it can be easily fixed changing some int variables to NSUInteger and placing some cast here and there.

I can send a pull request if you are interested.

**Comment by dominik-hadl** [comment]
This is no longer an issue (somebody fixed that) and can be closed.
