### ISSUE TITLE
touchesMoved not called in a test.

### ISSUE THREAD

**Issue by andykorth** [cocos2d/cocos2d-objc#405]
I may have found some inconsistencies in how the responders send out touch events. I'm not sure if this is intended behavior or not.

In this test (currently you can run it in cocos2d-ui-tests-ios, run ParallaxTest), touchesMoved never gets called. The method is defined on the TestBase, a CCNode. The node is added to the scene here:
https://github.com/cocos2d/cocos2d-iphone/blob/ce37ae5d2601ddf73c813bdf050925108c5436f6/cocos2d-ui-tests/TestBase.m#L129 

https://github.com/cocos2d/cocos2d-iphone/blob/develop-v3/cocos2d-ui-tests/tests/ParallaxTest.m#L135

CCResponderTest creates new nodes to receive the events and then adds them as children. These children nodes properly receive events. Not sure why this is happening, or if it's intended behavior.  If required, I can create more tests- this just came up as a side effect of porting old tests.

**Comment by Birkemose** [comment]
I will check on it.
Btw, when running the parallax test, it crashes because it can not find image "powered.png". The image is added in a blue folder, so it should be "Images/powered.png". 
Is this only a problem for me?

Btwbtw, I am not really sure I understand the issue. TestBase don't seem to enable touch handling.

**Comment by andykorth** [comment]
Isn't this all that's required to enable touch handling?
https://github.com/cocos2d/cocos2d-iphone/blob/develop-v3/cocos2d-ui-tests/tests/ParallaxTest.m#L89

You are correct, they should be referenced as "Images/powered.png". I think I was moving the files around and I had two copies in my simulator app bundle. Thanks for the catch. 

(side note: I think the test project doesn't need 37 mb of assets. I'll try to go through them and clean them up at some point. I already removed a few that weren't referenced at all.)

**Comment by Birkemose** [comment]
Ahh, I missed that line. My bad.
Well, yes, but it has to be done for the individual node / sprite / button. In that line, you enable touch handling for the base node, which is a CCNode with no content size. So it will never pass the touch test, unless you give it a content size. 
If you ex. set content size of a CCNode to screen size, that would mimic the old CCLayer behaviour. It is used in the responder test, to just grab any touch on the screen. 
https://github.com/cocos2d/cocos2d-iphone/blob/develop-v3/cocos2d-ui-tests/tests/CCResponderTest.m#L28

**Comment by andykorth** [comment]
Ahhh, content size! Makes sense. Thanks for the help. I'll update this test when I get a chance.
