### ISSUE TITLE
Texture loading enhancements.

### ISSUE THREAD

**Issue by slembcke** [cocos2d/cocos2d-objc#409]
This was cross posted from here: http://www.cocos2d-iphone.org/forums/topic/cocos2d-v3-ccfileutils-suffixes-vs-directories/#post-413154

A lot of this sort of discussion goes on on Github, but might as well cross-post some of it here for now. There is a lot of support for switching Cocos2D to use GLKTextureLoader. It exposes a super simple API that loads png, jpeg, pvr and most common image formats. It also gives you async loading nearly for free. What’s not to like about GLKTextureLoader, well apparently it can only load uncompressed pvr files (which are kinda huge), it uses ImageIO which probably means it needs to un-premultiply textures if you disable premultiplication and it’s not super flexible. GLKit is great if it does exactly what you need.

Birkemose and I were talking the other day, and he mentioned loading from a single set of texture resources (like 4x -ipadhd ones). A lot of 3D game engines handle this automagically by storing textures as a complete set of mipmaps. When you select to lower texture quality, it skips loading the larger mipmaps. This is easy to do with PVR or DXT files, but there is little to no direct editor support for them (can’t open them in Photoshop for instance). SpriteBuilder handles it similarly by automatically creating scaled versions from the hires art and plugging that into Cocos's existing path handling.

I’ve written texture loaders using libpng and libjpeg before and it’s pretty easy. Here is an old png one that supports optional premultiplication, paletted pngs, grayscale pngs, etc, and it’s [~130 lines of code](https://gist.github.com/slembcke/7794411). Jpeg loading [is even easier](https://gist.github.com/slembcke/7794411). The benefit of writing your own code like this is that you can load images line by line and downscale them without needing to load the entire image into memory. An iPhone 4 can handle loading a few 2048×2048 at 16MB each, but if you are low on memory, asking it to load a 64MB 4096×4096 texture and downscale it into another 16MB buffer is asking a lot… Using libpng/jpeg directly means that you only need to load a few kilobytes of the whole image at a time and downscale that. The downscaling pass wouldn’t be very expensive compared to loading/decompression, and it could be very easily vectorized. Between png and pvr, that probably covers most Cocos2D usage. Jpeg is easy enough to add too. Does anybody use anything else?

I feel like the only downsides are that it would add a couple hundred lines of code to the project and add libpng/libjpeg as dependencies.

I'd like to prototype this in January if people think it's a good idea.

**Comment by vlidholt** [comment]
Another possible solution to this (possibly in combination to what @slembcke is proposing above) is to allow the user to provide images in 4x, scale it down the first time it's loaded and save it in the apps cache directory. Sequent loads of the image would be much faster as they could be loaded from the cache (already correctly scaled). This is already supported through the CCFileUtils as it supports different lookup paths (we could just add the cache path here).

Another thing, that may not be so easy to handle, is sprite sheets. It's more complicated to scale down a sprite sheet in runtime. I think it could be possible by implementing restrictions on how such sprite sheets are saved (widths dividable by 4, big enough spacing between sprites etc).

Yet another consideration. It must always be possible to manually do the downscaling. Many game companies have their artists do their downscaling (as they are not happy with the automatic scaling in some cases).

**Comment by slembcke** [comment]
Yeah, spritesheets can be safely downscaled if the packer expands the sprite sizes to be multiples of 4, and uses a padding of 4 pixels. I don't think Texture Packer can do this despite having a lot of other padding/packing options. We can bring it up with Andreas though.

My thought was that this would be a fallback. It would only do this if it didn't find the correctly sized image first. Right now Cocos can only fall back on loading smaller images. This would allow it to fall back to loading larger images and downscale them.

**Comment by cocojoe** [comment]
This used to be talked about before in forums with auto downscaling -hd at
runtime for non-retina and writing to disk.  Makes sense for reducing
payload as well....
Agree that manual precedence must be allowed as last illustrator I worked
was fussy about this.

On 5 December 2013 00:32, slembcke notifications@github.com wrote:

> Yeah, spritesheets can be safely downscaled if the packer expands the
> sprite sizes to be multiples of 4, and uses a padding of 4 pixels. I don't
> think Texture Packer can do this despite having a lot of other
> padding/packing options. We can bring it up with Andreas though.
> 
> My thought was that this would be a fallback. It would only do this if it
> didn't find the correctly sized image first. Right now Cocos can only fall
> back on loading smaller images. This would allow it to fall back to loading
> larger images and downscale them.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/cocos2d/cocos2d-iphone/issues/409#issuecomment-29860910
> .

## 

Martin

**Comment by slembcke** [comment]
A related off topic sub-thread here about .ccz files and content protection:
https://github.com/cocos2d/cocos2d-iphone/issues/403#issuecomment-29845139

**Comment by vlidholt** [comment]
Two other ideas if we are doing this that could be useful:

Automatic upscaling. If using lower resolution assets, these to could be upscaled in runtime. For instance, blurry backgrounds could be saved in lower resolution to save space both in bundle size and memory. Would be nice if this was handled automagically (similar to how UIKit does it).

Lazy loading of assets via internet. The user can provide low res images for certain assets, when they are used the first time the low res image is displayed, but the app starts downloading a higher res image in a background thread. Once the image is loaded it's cached and reused. Possibly this could be handled by a subclass of CCSprite if we are not having it on a more general level.

**Comment by slembcke** [comment]
Automatic upscaling: See item 5 in the list -> https://github.com/cocos2d/cocos2d-iphone/pull/408 You just merged the change for that yesterday. ;)

Lazy loading: Interesting. Not sure if I'm sold on the background thread part though. It would make for a substandard experience until the high-res textures were loaded. I get the feeling that AAA games put a _huge_ amount of work into streaming texture loading to make it seamlessly and they have a lot more IO bandwidth to work with. Providing this as a built-in feature might be cool if devs are interested though.

**Comment by vlidholt** [comment]
Sweet! :)

**Comment by Panajev** [comment]
I think downloading higher resolution assets online could work and would be very good for those games which want to push an App Store size that is as small as possible and ask the user to download bits and pieces only as needed.

[web [iPhone msg]]

**Comment by billhollings** [comment]
Actually...I've even experimented before with loading textures in two passes, even from local iOS files. 

An immediate load of a small, coarse texture for a quick preview, while the main high-rez image loads in the background. Think Google maps...coarse resolution first, then finer resolution in a few seconds. 

Loading a full texture can sometimes take several seconds, delaying app start significantly, when a quick app start might be desired. Yes...the immediate quality is lower, but the trade-off can be worthwhile in certain apps. Depends on the app.

If we create the capability in general, then it can be used for both downloaded and large local content, as needed.

...Bill

**Comment by billhollings** [comment]
Oops...sorry...didn't see slembcke's note above before I posted. 

Is this now a real feature? Not sure if item #5 in $408 does the same thing.

**Comment by slembcke** [comment]
I guess the big reason why I'm not sold on the stream-from-the-internet idea is that the first initial impressions of an app are the most important to see if the user will keep the app or not. Although... the use case is realistically ship with 2x art, and save the 4x iPad retina art to be streamed. iPad generally implies a good, non-cellular data internet connection. Hmm...

@billhollings Yup. A texture reports it's contentSize based on it's own private contentScale which is set depending on which file suffix/directory it loaded. Sprites and SpriteFrames use this when constructing their own contentSize. So if it falls back to loading a 100x100 sprite.png file it will be 100x100 points and blurry on a retina screen instead of too small. If it loads a 200x200 sprite-hd.png file it will still report it's content size as 100x100. I've wanted to fix that for years. ;)

**Comment by slembcke** [comment]
I was thinking about downscaling PNGs at load time last night before bed. I wanted to work on something different for relaxation purposes and threw together a prototype. (To be clear, this isn't for 3.0)

It's about ~200 lines of code to load PNGs as a stream while downscaling them.
https://github.com/cocos2d/cocos2d-iphone/compare/fancy-png#diff-2

The short story is that it works, and compared to UIKit it's even fast. The following runtimes are on a 4th get iPod touch, one of the slowest retina devices still around.

<table>
<tr><td>2k PNG loaded using CGImage</td> <td>1.20 seconds</td></tr>
<tr><td>2k PNG loaded using libpng</td> <td>1.26 seconds</td></tr>
<tr><td>1k PNG loaded from 2k file using libpng</td> <td>1.19 seconds</td></tr>
<tr><td>1k PNG loaded using CGImage</td> <td>0.38 seconds</td></tr>
<tr><td>1k PNG loaded using libpng</td> <td>0.36 seconds</td></tr>
</table>

Not thoroughly tested yet, but that seems promising for a little hacked together implementation. libpng performance is largely identical to CGImage. I honestly expected it to be faster, but oh well. Downscaling the 2x image was actually faster, and I ran it several times to check. Less memory bandwidth usage I guess? Downscaling a 2x texture still almost four times as expensive as loading a 1x texture, but I think the convenience, disk savings, and built in encryption support would make this a welcome addition for many devs. Since it would still be possible to ship with 1x textures as an option, there isn't much of a downside.

What I didn't do:
- My existing code handled loading RGB, RGBA, L, and LA textures with or without premultiplication, but I only wrote scaling code for RGBA.
- Didn't vectorize anything, but it doesn't seem like it would matter.
- Doesn't pad non-RGBA textures to 4 bytes per scanline or POT sizes. (can reuse existing code for this)
- Doesn't perform format conversions. (Can reuse existing code for this)
- No decryption support yet, but it would be easy to add since the files are buffered manually. Will ask permission to include Andreas's decryption code.
- No JPEG support, but that should be a much easier and shorter than the PNG version I expect.

Some problems:
- You have to disable Xcode's PNG file "compression" (a.k.a. mangling), or libpng can't load them. We could set this in the templates, and it wouldn't really be a problem. We could catch the error it causes and add a warning about it too.
- Downscaled texture atlasses don't "just work" since the texture coordinates are currently calculated in pixels. This could be fixed though. Atlasses would also need to be padded correctly to support downscaling. (sizes padded to multiples of 4 and 4 pixel borders)

edit: Forgot to mention, but it can do 2x or 4x downscaling. Just in case anybody wants to load iPad retina graphics on their 3GS or old Android phone. The performance penalty would be severe since it throws away so much of the data though.

**Comment by slembcke** [comment]
Another idea I had sort of forgotten about: https://github.com/slembcke/ImageConvert

I've been using that build rule for a few years now. It's very convenient to be able to add .psd files to the Xcode project and have them automatically converted/rescaled at build time without having to export/scale them by hand every time I make an edit. This would be less of a Cocos2D feature than a template feature though.

The build rule already works now and is trivial to deploy if we want to add it to the templates for 3.0.

**Comment by andykorth** [comment]
Yeah, the imageConvert trick is pretty great. Unity3D works that way and touts the fast turnaround of the asset pipeline as a major feature. People seem to think directly reading photoshop files from their game is impossible, but it's actually a pretty easy technique that can really wow people.
