### ISSUE TITLE
Advantage of discarding touch events in CCResponder?

### ISSUE THREAD

**Issue by Ben-G** [cocos2d/cocos2d-objc#410]
The current implementation of CCResponder discards the touch events it receives:

```
- (void)touchesBegan:(NSSet *)touches withEvent:(UIEvent *)event
{    
    [[CCDirector sharedDirector].responderManager discardCurrentEvent];
}
```

This means if your subclass does not override, e.g. `touchesBegan`, the next responder in the responderlist will get to handle the touch event.
**Is there a specific use case for this behaviour?**

I currently have a use case where this implementation is counter intuitive. This is the setting:

I have a CCScene. If the user touches the CCScene, a new CCDragSprite is created and added as a child to the CCScene. If the user touches a CCDragSprite he can move it around. 

Currently my CCDragSprite code looks like this:

```
@implementation CCDragSprite

- (void)onEnter {
    self.userInteractionEnabled = TRUE;
}

- (void)touchesBegan:(NSSet *)touches withEvent:(UIEvent *)event {
}

- (void)touchesMoved:(NSSet *)touches withEvent:(UIEvent *)event {
    // multitouch is disabled, so we will reveive only one touch and can use 'anyObject' to access it.
    UITouch *touch = [touches anyObject];
    // we want to know the location of our touch in this scene
    CGPoint touchLocation = [touch locationInNode:self.parent];

    self.position = touchLocation;
}

@end
```

I have to add an empty implementation for `touchesBegan`, otherwise my CCScene will claim the touch instead of my CCDragSprite.

If I don't miss a significant use case for the current implementation, I propose to remove the event discarding in CCResponder.

Thoughts on this? (If explanation is too confusing I can share the code)

**Comment by Birkemose** [comment]
It is made this way, for a couple of reasons.
The idea is, that touchesBegan is used to determine if you want to process the touch or not. Default is not, which I think is the most logic choice. Aka if you don't specifically handle the touch, it will automatically ripple down the touch chain. So implementing touchesBegan, even if you in rare cases don't need to put any code in it, is your way of saying "I am grabbing the touch".
In previous versions of cocos2d, you returned a BOOL from touchBegan, whether you had grabbed the touch or not. Now, you default grab the touch if touchesBegain is implemented, and discard it if it is not. If you programatically want to discard the touch in touchesBegan, you use the same approach as in UIResponder, and call the super.
