### ISSUE TITLE
Color Cascading

### ISSUE THREAD

**Issue by cocojoe** [cocos2d/cocos2d-objc#428]
I've been testing CCColor and was wondering what is the actual expectation of color cascading?

For example, if we take a red color node with cascade enabled, what do you expect to happen if you add a CCLabelBMFont to it?

``` ruby
CCNodeColor *colorNode = [CCNodeColor nodeWithColor:[CCColor colorWithRed:1.0f green:0.0f blue:0.0f alpha:1.0f]];
[colorNode setCascadeColorEnabled:YES];
[self addChild:colorNode];

CCLabelBMFont* bmFont = [CCLabelBMFont labelWithString:@"cocos2d" fntFile:@"font_menu.fnt"];
[colorNode addChild:bmFont]; // This will be white (font bitmap is white)

[bmFont setColor:[CCColor whiteColor]]; // Oh now it turns red :-)
```

**Comment by andykorth** [comment]
I'm glad you brought this up- I have a test for ColorCascading and it doesn't actually seem to work. 

I had a half-written issue about it.

The intent seemed to be that changing the color of a parent node with CascadeColor enabled would set the color of it's children nodes.

https://github.com/cocos2d/cocos2d-iphone/blob/develop-v3/cocos2d-ui-tests/tests/ColorTest.m#L80

That doesn't work.

Internally, there's extra logic that's supposed to make this work on BMFonts - presumably to color all the characters at the same time and keep them the same color.

I propose removing setCascadeColor, and adding a setColorRecursively method. SetColorRecursively would be simple, clear, and easy to implement. There's no good reason this functionality requires adding fields to superclasses like CCNode<RGBAProtocol> (_cascadeColorEnabled, _cascadeOpacityEnabled, etc). Propagating colors changes is pretty simple. 

For nodes that want to always cascade by default, (like CCLabelBMFont), that class can override setColor and call setColorRecursively.

Related node: _realColor vs. _displayedColor. I haven't finished investigating this, but it looks like these are quite redundant.

**Comment by andykorth** [comment]
A correction: It looks like your commit yesterday fixed my color cascade test. Nice work!
