### ISSUE TITLE
Some files like CCColor.h is not found when template installed.

### ISSUE THREAD

**Issue by hcivelek** [cocos2d/cocos2d-objc#429]
When I install cocos2d and create a new project it says CCColor.h is not found. If I fix this, then I got an same error for another file (CCParticleSystemBase.h).

**Comment by cocojoe** [comment]
When did you last pull from the main repo? This was fixed and merged
yesterday.

On 13 December 2013 12:29, Hasan notifications@github.com wrote:

> When I install cocos2d and create a new project it says CCColor.h is not
> found. If I fix this, then I got an same error for another file
> (CCParticleSystemBase.h).
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/cocos2d/cocos2d-iphone/issues/429
> .

## 

Martin

**Comment by dominik-hadl** [comment]
This is already fixed, just tested it.
