### ISSUE TITLE
CCNode setColor ignores alpha

### ISSUE THREAD

**Issue by andykorth** [cocos2d/cocos2d-objc#430]
See ColorTest.m setupHalfTransparentTest

```
    CCSprite * img = [self loadAndDisplayImageNamed: @"powered.png" withTitle: @"50% alpha, via Color"];
    [img setColor:[CCColor colorWithRed:1.0f green:1.0f blue:1.0f alpha:0.5f]];
```

The CCColor is converted to a ccColor3b (dropping the alpha) and is then applied. I consider this quite wrong.

@cocojoe, are you working on any color changes? Unless you want to do it, I'll fix up how CCColor is being used.

**Comment by cocojoe** [comment]
Feel free to fix :-)

On 13 December 2013 16:42, Andy Korth notifications@github.com wrote:

> See ColorTest.m setupHalfTransparentTest
> 
> ```
> CCSprite * img = [self loadAndDisplayImageNamed: @"powered.png" withTitle: @"50% alpha, via Color"];
> [img setColor:[CCColor colorWithRed:1.0f green:1.0f blue:1.0f alpha:0.5f]];
> ```
> 
> The CCColor is converted to a ccColor3b (dropping the alpha) and is then
> applied. I consider this quite wrong.
> 
> @cocojoe https://github.com/cocojoe, are you working on any color
> changes? Unless you want to do it, I'll fix up how CCColor is being used.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/cocos2d/cocos2d-iphone/issues/430
> .

## 

Martin

**Comment by vlidholt** [comment]
Are you planning on multiplying the color with the alpha property? Maybe this should be the correct behavior?

**Comment by vlidholt** [comment]
Another possibility is to scrap the opacity property and only use the color. I am good with any of those solutions.

**Comment by andykorth** [comment]
The latter is what I have done. It massively simplifies a lot of code. There's a lot of turning color3 + alpha into color4 and back.

**Comment by Birkemose** [comment]
I guess opacity should just wrap colour.a, and setting a colour should normally not affect the alpha channel.

**Comment by vlidholt** [comment]
One consideration is that we probably want to be able to run opacity and color actions independently. I'd say that is pretty important.

**Comment by vlidholt** [comment]
Also, the cascading colors and the CCNodeRGBA I find a bit confusing. Maybe this functionality should be a part of CCNode, and those node types that doesn't support setting color or alpha can just pass the colors down to it's kids (if cascading is enabled). I don't feel very strongly about this, but would love to hear your thoughts.

**Comment by Birkemose** [comment]
My personal opinion on this is:
The internal data representation should always match openGL as closely as possible, unless it makes good sense not to. So internally colour should be a 4 \* GLfloat.
Externally, the user will want an rgb part, and an opacity part, so the interface should reflect that ...
If the 4F colour property is directly available, it should be renamed to colourRGBA or something.

**Comment by Birkemose** [comment]
+1 on moving RGBA back to the node.

**Comment by slembcke** [comment]
@vlidholt 
I do get what the cascading colors are for, so you can fade out an entire node and it's children (which might have an alpha set of their own). It is sort of a mess though... I actually didn't even know it existed until a couple days ago. Not really sure what should be done with it.

@Birkemose 
After years of doing shaders and such, color == RGBA to me. I've never liked Cocos's separate color and alpha, but I've rarely ever had to use it either. If we added a colorRGBA property I'd be pretty happy. I think that would be pretty clear to users too. That seems like a good solution.

edit: To be clear, I mean colorRGBA in addition to the color and alpha properties.

**Comment by andykorth** [comment]
@Birkemose  So I disagree about setting a color not affecting opacity. If you provide a CCColor (a color4), I would expect the alpha to change. But I could be convinced otherwise. (Running color and opacity actions independently could still happen, but maybe it's easier to leave things the way they are). I guess I've always just dealt with color and alpha together. 

Perhaps I'll leave the current setColor behavior (ignore the alpha), and add a setColorRGBA method. 

I definitely agree about storing the color internally at a 4 *GLfloat.

@vlidholt Yeah, cascading colors seem very confusing to me also. I haven't changed the behavior yet though, I think I'll look at it next. I think the CCNodeRGBA protocol can definitely go away. All CCNodes support cascading color anyway, and that's what that's for. I expect that is just an artifact of "how things used to be".

**Comment by billhollings** [comment]
Fading in and out, and being able to run the CCFade family of actions is pretty important. Modifying opacity alone is something we should definitely retain (oops...sorry...I mean "create a strong reference to"  :^)  ).

**Comment by Birkemose** [comment]
The problem with setting alpha is, that the code
sprite.opacity = 0.5;
sprite.color = ccRED;
would not work anymore, and we would get a bazzilion-billion (aka a lot) bug reports.
If we ignore alpha on setColor, and add a setColorRGBA property, hardly anyone can be in doubt about how it works.

**Comment by andykorth** [comment]
Yeah, good point.

**Comment by andykorth** [comment]
So a summary of what I have so far:
- Most user called functions use CCColor. (done a while ago by Viktor)
- setColor doesn't apply the alpha of the CCColor parameter.
- setColorRGBA - new method that does apply the alpha.
- Colors are stored internally as GLfloat4 - don't store separate color3 + alpha. Reduce the endless swapping between bytes and floats internally.
- setOpacity and such all still work unchanged from user's point of view.
- No changes yet to cascade, cascade tests still pass. 

These are done here:

https://github.com/andykorth/cocos2d-iphone/compare/CCColorUseCleanup

Next I'll fix up the repetitive cascade code, look at removing unnecessary CCNodeRGBA (because all the code is in CCNode anyway now).

**Comment by slembcke** [comment]
Seems like this is all taken care of then.
