### ISSUE TITLE
Can not get iPhone retina and iPad to share resources

### ISSUE THREAD

**Issue by Birkemose** [cocos2d/cocos2d-objc#442]
I have been struggling, trying to understand why this fails, but I am not able to. Everything is set to default, and then I set this
    CCFileUtils *sharedFileUtils = [CCFileUtils sharedFileUtils];
    [sharedFileUtils setiPhoneRetinaDisplaySuffix:@"-hd"];  
    [sharedFileUtils setiPadSuffix:@"-hd"]; 
    [sharedFileUtils setiPadRetinaDisplaySuffix:@"-ipadhd"];

Ipad and ipad retina seems to load correctly, but iPhone retina scales wrong.

**Comment by cocojoe** [comment]
Do you have a test project available so we can ensure there are no
differences in any other code etc before testing?

On 21 December 2013 14:34, Birkemose notifications@github.com wrote:

> I have been struggling, trying to understand why this fails, but I am not
> able to. Everything is set to default, and then I set this
> CCFileUtils *sharedFileUtils = [CCFileUtils sharedFileUtils];
> [sharedFileUtils setiPhoneRetinaDisplaySuffix:@"-hd"];
> 
> [sharedFileUtils setiPadSuffix:@"-hd"];
> [sharedFileUtils setiPadRetinaDisplaySuffix:@"-ipadhd"];
> 
> Ipad and ipad retina seems to load correctly, but iPhone retina scales
> wrong.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/cocos2d/cocos2d-iphone/issues/442
> .

## 

Martin

**Comment by slembcke** [comment]
Related issue: https://github.com/cocos2d/cocos2d-iphone/issues/445

In my example project, I set up file utils like this:
https://github.com/slembcke/CCPhysicsColorMatch/blob/master/CCPhysicsColorMatch/Classes/AppDelegate.m#L33

It seems to work correctly for me, and is supposed to match the old 2.x defaults.

**Comment by Birkemose** [comment]
I just tried downloading the colour demo, but it crashes with some PBXCp error or something. Seems that pop.wav couldn't be found.

**Comment by vlidholt** [comment]
There is a property you need to set to use phonehd resources for iPad, `enableiPhoneResourcesOniPad`.

**Comment by Birkemose** [comment]
I just tried, and marked my assets specifically, and -hd is loaded in iPhone retina, but it is still too big, and both sized and positioned completely wrong.

**Comment by andykorth** [comment]
This would be an excellent thing to add to the cocos2d-tests project. 

There are also some unit tests that touch on some of this, but I don't think they go in enough depth yet. See CCFileUtilTests.

**Comment by cocojoe** [comment]
@Birkemose did you get to the bottom of this one? I just tried setting the enableiPhoneResourcesOniPad flag, works fine on iPhone Retina, but uses non HD assets for iPad.

AppDelegate is rather ugly these days.

**Comment by Birkemose** [comment]
After using Scott's app setup, everything seems to work fine.
