### ISSUE TITLE
Actions does not work on overridden properties

### ISSUE THREAD

**Issue by Birkemose** [cocos2d/cocos2d-objc#444]
This has never worked, so I wondered if we at some point should do something about it.
If obviously works if you tween the property directly, but few does, and the tweening is quite limited compared to "real" actions.

**Comment by slembcke** [comment]
Oh? Like if you override the color setter and use a tint action it won't call the overridden method? That's odd. I've never looked closely enough at how actions actually work internally. Is it caching the CCNode method implementations or something?

**Comment by Birkemose** [comment]
I havent checked on the problem yet, but overriding rotation clearly does not work. I have had the problem some time back, but I can't remember if that were with other properties, or also with rotation. Will check tomorrow.

**Comment by Birkemose** [comment]
Actually, I just updated the issue, as I can not get physics to work either, on overridden properties.
Not sure if it is the same issue, but if I create an object, and override rotation on it, it has no effect regarding physics.

My node is a compound node. Empty base CCNode, having 3 children, and where I override rotation of the basic child, to prevent all 3 children from rotate. Positioning, size, etc works fine, bit no rotation.

I wonder if this is a "rotation only" issue, and that is why I for now added the comment here.

**Comment by vlidholt** [comment]
Exactly how do you do your override, are you calling the super method?

``` objc
- (void) setRotation:(float)rot
{
    // Do custom stuff

    [super setRotation:rot];
}
```

**Comment by slembcke** [comment]
Not sure why this wouldn't work unless `[super setRotation:]` wasn't called. CCPhysics can't use the rotation ivars in CCNode since it would have to constantly poll them to check for changes. Calling the super property is non-optional in that way.

**Comment by Birkemose** [comment]
I tried calling super, but to no avail, so maybe it is because my visible sprite is a child of that actual physical sprite? Position works fine. The sprites are bouncing along nicely, they are just not rotating.

**Comment by vlidholt** [comment]
Maybe we can get some sample code to see what's actually going on here? For what purpose are you overriding the rotation property, it seems like a rather unusual thing to do?

**Comment by slembcke** [comment]
I've been meaning to look into this too. There was a post on the forums a couple days ago that sounds like it's the same issue when using CCPhysicsSprite:
http://www.cocos2d-iphone.org/forums/topic/ccphysicssprite-dont-rotate-with-action-chipmunk/

CCPhysicsSprite overrides the rotation properties to use and set values from a Chipmunk body. In rare cases it's useful to override basic properties like that.

**Comment by Birkemose** [comment]
An example could be a particle system, added to a physics node, where you in most cases do not want the particles to rotate with the physics (burning ball for instance)
My way of designing this, would be to build a compound objects, and override ex. rotate, so it only rotated the appropriate parts. Right now I am struggling with that.

I will see if I can scrape up some more information on the issue tomorrow.

**Comment by Birkemose** [comment]
I removed "physics" from the headline, as this seems to be a different issue.

As for actions not working when overriding properties, it seems to be scale and rotation, as they are split into rotationSkewX, rotationSkewY, scaleX and scaleY. Haven't found the fix yet.

Edit:
Both issues fixed.
