### ISSUE TITLE
Assorted template issues.

### ISSUE THREAD

**Issue by slembcke** [cocos2d/cocos2d-objc#445]
So I got a CCPhysics example up and running here: https://github.com/slembcke/CCPhysicsColorMatch

There are some things I noticed about the templates that I would like to fix:
- They don't use CCAppDelegate yet.
- Currently they set up CCFileUtils to use directories instead of suffixes. There are a few issues I see with this:
  - This is completely different than the defaults in 2.x. I think people will be confused and we should have the default setup mirror 2.x.
  - The project does not include any empty folder references to the various directories you need to fill with assets. You would have to know to create a "Resources-phone" directory, etc.
  - Xcode has a lot of bugs associated with folder references. In particular, it's really bad at discovering when files change inside of one and you need to force a clean build for it to notice.
  - If we are going to be moving towards automatic downscaling in the next version, directories don't make a lot of sense.
- The iOS 7 status bar is not disabled by default. It probably should be.

I'd like to make these changes to the templates. Any thoughts?

**Comment by Birkemose** [comment]
I am currently working on the template, so as long as you leave intro scene and hello world alone, it is fine with me.

I still think resource loading is no way as clean as it could have been. The complexity of setting this up is unfathomably incomprehensible, compared to how simple it could be.

**Comment by slembcke** [comment]
Yeah. I have some notes about that in the 3.0+ feature ideas list I'm typing up. We can, and should massively simplify CCFileUtils. I feel like we could rewrite it in a fraction as many lines of code with a simpler setup API and not take away any features it provides.

**Comment by cocojoe** [comment]
Sounds goods re all those changes, out the box Cocos2D should 'just work'
for the majority use case.
If gfx are high quality you can pretty much get away with -hd across
everything (retina+)

On 21 December 2013 22:14, slembcke notifications@github.com wrote:

> Yeah. I have some notes about that in the 3.0+ feature ideas list I'm
> typing up. We can, and should massively simplify CCFileUtils. I feel like
> we could rewrite it in a fraction as many lines of code with a simpler
> setup API and not take away any features it provides.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/cocos2d/cocos2d-iphone/issues/445#issuecomment-31073579
> .

## 

Martin

**Comment by vlidholt** [comment]
Not sure if this is possible, but I personally think that the best solution for a template would be to include Cocos2D as a sub-project. If doing this it will be super easy for users to update Cocos2D (just replace the cocos2d-iphone folder) while still being able to easily access the source code. It would also make it possible to have Cocos2D as a submodule to your git project, which I think we should encourage so that it will be easier for our users to send us bug-fixes and other improvements.

Also see #465

**Comment by slembcke** [comment]
Seems like everything here has been taken care of.
