### ISSUE TITLE
CCAppDelegate does not initialize CCFileUtils.

### ISSUE THREAD

**Issue by slembcke** [cocos2d/cocos2d-objc#447]
CCAppDelegate does not initialize CCFileUtils. We should add an option for this to select if you want the default suffixes, directories, or none.

**Comment by Birkemose** [comment]
This certainly should be simplified in some way.
I do not hope the average newcomer is more stupid than me, because I have just spent half a day getting this to work, and just given up.

**Comment by vlidholt** [comment]
I think that the fix should be that the [CCFileUtils sharedFileUtils] being called the first time sets up a good default properties. If they need to be tweaked this can be done in the applicationDidLaunch method in the custom app-delegate before the setup method is called.

**Comment by slembcke** [comment]
Hmm. Yeah. That makes more sense. Instead of having an explicit configuration step, it just has reasonable defaults.

**Comment by Birkemose** [comment]
It should be simpler, and more intuitive.

**Comment by vlidholt** [comment]
I merged @slembcke s pull request.
