### ISSUE TITLE
CCScheduler iteration/mutation bug.

### ISSUE THREAD

**Issue by slembcke** [cocos2d/cocos2d-objc#448]
InvokeMethods() in CCScheduler.m needs to iterate a copy of it's array or use a doubly linked list of targets. Objects can be removed during iteration.

Needs a unit test too.

**Comment by Birkemose** [comment]
Iterate backwards?

**Comment by slembcke** [comment]
Well, so the issue is that when calling the list of update: or fixedUpdate: methods objects can remove themselves or other objects from the scene. Since objects can remove other objects that may have scheduled updates, the backwards iteration trick doesn't work.

I'm going to make a unit test for performance of this to see if copying the list is a big deal. I suspect not. I have some ideas for simpler changes before moving to linked lists too.

**Comment by tebruno99** [comment]
I believe I have run into this bug as well.  CCSheduler::InvokeMethods causes an index out of bounds exception because the Layer removed an object during the update cycle. The NSArray methods no longer contains the objects but the for loop's index is larger than the size of the array so on the next iteration it throws exception.

**Comment by Birkemose** [comment]
Making a copy is expensive, but if of course depends on how many items are in the list. This sounds more like we need to add some basic functionality?

**Comment by tebruno99** [comment]
I'm still trying to track down how this works in Cocos2d-2.x. As this doesn't occur in the previous version.  I'm rather new to the cocos2d source code so its taking me time to figure out how it used to work.

**Comment by slembcke** [comment]
Oof. Well so I made a performance unit test to find out if I was going to break performance in some terrible way. Turns out ARC was already doing that for me with unnecessary retain counting code. \o/ It's always fun to find out how you can trivially break the performance of simple code with ARC. :(

Since there was a fair amount of discussion, here is a detailed writeup of what I found:

All tests were run with 500 scheduled update selectors run for 500 seconds at 60 Hz on an iPhone 5. The update selectors themselves were empty.

Original code as follows ran in 13.0 seconds.

```
static void
InvokeMethods(NSArray *methods, SEL selector, CCTime dt)
{
    for(NSUInteger i=0, count=methods.count; i<count; i++){
        CCScheduledTarget *scheduledTarget = methods[i];
        if(!scheduledTarget->_paused) objc_msgSend(scheduledTarget->_target, selector, dt);
    }
}
```

Using fast iteration gives ARC some hints to avoid retaining the target through each iteration of the loop. Changing the `_target` ivar from `__weak` to `__unsafe_unretained` avoided retain costs (and thread locking) when dereferencing the ivar. It wasn't using the auto-zeroing property anyway. Despite the copy, it runs in 5.3 seconds since it's doing much less retain counting work and avoids the expense of accessing a weak variable.

```
static void
InvokeMethods(NSArray *methods, SEL selector, CCTime dt)
{
    for(CCScheduledTarget *scheduledTarget in [methods copy]){
        if(!scheduledTarget->_paused) objc_msgSend(scheduledTarget->_target, selector, dt);
    }
}
```

Yay for premature optimization. -_- Fast enumeration is actually faster for once.  Removing the copy, it drops to 0.7 seconds. A much smaller number yet, but also a very very tiny fraction of the CPU time already. The fixed method is actually faster with room for future improvement yet. Seems like a good place to be.

So if you have a lot of scheduled targets (500), the copy call wastes < 1% of your CPU time (~5/500 sec). It's something to look at in the future, but not something I'm going to lose sleep over. The scheduler is already much more efficient in other ways, so it should still be a big improvement.

**Comment by slembcke** [comment]
@tebruno99 It's broken because I completely rewrote the scheduler for 3.x to add fixed updates and use a priority queue for _much_ faster timers.

**Comment by slembcke** [comment]
Fix has been pushed to develop-v3. https://github.com/cocos2d/cocos2d-iphone/commit/33a12fd28d25943e1781ff27c7c8db86b5c5ae15#diff-1

**Comment by tebruno99** [comment]
I have confirmed that this fixed the issue for my preexisting code. Thanks!

**Comment by slembcke** [comment]
Yay for regressions. :( Hopefully that should improve in the future since there are unit tests though. ;)
