### ISSUE TITLE
CCScene.isScene method missing.

### ISSUE THREAD

**Issue by slembcke** [cocos2d/cocos2d-objc#449]
The CCScene.isScene method is missing. This is used by the CCNode.scene method to search the view hierarchy. I think I may have accidentally removed it when doing some refactoring. :-\

Needs a unit test too.

**Comment by Birkemose** [comment]
That should be an easy fix :)

**Comment by vlidholt** [comment]
I think this should not be a public method. For performance issues this can possibly be an optimization, but otherwise to test if a node is a scene just call. 

`[myNode isKindOfClass:[CCScene class]]`

Otherwise, should we add a 'isASpecificKindOfNode' properties for every kind of node? Hardly makes sense to me

**Comment by slembcke** [comment]
It's a private method that is used like this in CCNode:

```
// Overriden by CCScene to return YES.
-(BOOL)isScene {return NO;}
-(CCScene *)scene {return (self.isScene ? (CCScene *)self : self.parent.scene);}
```

isKindOfClass: is sometimes surprisingly slow. I got used to writing recursive search functions like that in other more dynamic languages, but maybe people think it's odd? (Stephen Itterheim made a point about it in his pre-review)

Maybe I shouldn't have made actual issues for all of these. Normally I just write them on a note on my desk that I tend to lose...

**Comment by vlidholt** [comment]
To be more clear, I think they are fine to have in the framework for optimization purposes, but I don't think they should be exposed in the API.  So sounds to me like everything is good!
