### ISSUE TITLE
CCButton Color

### ISSUE THREAD

**Issue by cocojoe** [cocos2d/cocos2d-objc#452]
If you simply set the color of a CCButton e.g. button.color = [CCColor redColor]; This doesn't do anything although a user would expect it to do something...

You set colours for the various states e.g.

[button setLabelColor:[CCColor blackColor] forState:CCControlStateNormal];

Should setColor perhaps be a convenience to set color for Normal State?

**Comment by andykorth** [comment]
That sounds good to me.

**Comment by Birkemose** [comment]
Adding "default behaviour" should be done carefully, as there is a fine line between what some people thinks makes sense, and others don't. 
I might make sense to most, that setting the colour or a button, sets the normal state, while other would expect it to tint / filter all states. It should of course never do nothing.

I think that is we are in doubt, we should assert it, and let the user know what he should do in stead.

**Comment by Birkemose** [comment]
I still think this should be addressed. Setting normal colour seems like a logic choice?

**Comment by slembcke** [comment]
I don't think anybody would find it surprising if that's what it did.

**Comment by cocojoe** [comment]
Have added, will do a pull request later.

On 10 January 2014 02:49, slembcke notifications@github.com wrote:

> I don't think anybody would find it surprising if that's what it did.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/cocos2d/cocos2d-iphone/issues/452#issuecomment-31998662
> .

## 

Martin
