### ISSUE TITLE
CGPoint +, -, *, / operators overload

### ISSUE THREAD

**Issue by tkach** [cocos2d/cocos2d-objc#454]
Hi all!
Writing ccpAdd, ccpSub, etc.. for CGPoints is nice, these functions saves us a lot of time instead of operating on CGPoints properties directly.

But writing such long sequences makes me sad sometimes:

CGPoint result = ccpMult(ccpAdd(pointA, pointB) \* 10);

Also it's sometimes hard to understand what's happening here.

Maybe it's better to overload arithmetic operators for CGPoint struct? It will simplify CGPoint operations greatly, for example

CGPoint operator+(const CGPoint &p1, const CGPoint &p2)
{
    CGPoint sum = { p1.x + p2.x, p1.y + p2.y };
    return sum;
}

Such approach let us to write more laconic code:
CGPoint result = pointA + PointB

I know that difficulity here is that you can't easily jump to implementation of + operation easily, like with ccpAdd function, but maybe it's not so important for users to dig in the internals?:)

What do you think?

**Comment by davilca** [comment]
I like the idea, it's more readable with operators. We could keep both options: functions and overloaded operators.

**Comment by vlidholt** [comment]
It's not possible to overload operators in objective c. http://stackoverflow.com/questions/3613980/can-i-overload-an-operator-in-objective-c

**Comment by Panajev** [comment]
Basically my only real gripe against a language I otherwise really really like.

[web [iPhone msg]]

**Comment by tkach** [comment]
Oh, sorry for my fault.
Really, it's possible to overload operators in Objective-C++ not in the Objective-C.
Closing this issue, thanks @vlidholt
