### ISSUE TITLE
Memory leak and crash when switching scenes

### ISSUE THREAD

**Issue by leszek-s** [cocos2d/cocos2d-objc#457]
Scene does not seem to be released from memory on popSceneWithTransition which causes a low memory warnings and crash after few scene changes.

I have two scenes with following implementations:

<pre>
@implementation MainMenu
- (void)creditsAction:(id)sender
{
    CCScene *scene = [CCBReader loadAsScene:@"Credits"];
    CCTransition *transition = [CCTransition transitionPushWithDirection:CCTransitionDirectionLeft duration:0.3];
    [[CCDirector sharedDirector] pushScene:scene withTransition:transition];
}
@end
</pre>

and

<pre>
@implementation Credits
- (void)backAction:(id)sender
{
    CCTransition *transition = [CCTransition transitionPushWithDirection:CCTransitionDirectionRight duration:0.3];
    [[CCDirector sharedDirector] popSceneWithTransition:transition];
}
@end
</pre>

I'm switching the scene from MainMenu -> Credits -> MainMenu -> Credits ... and so on then after about 10 changes app gets killed by the system due to low memory conditions. In profiler I can see that there is more than 1 instance of Credits class in memory (so it was not released on popScene). I assume that all resources like graphics from png files used on scene built in SpriteBuilder and/or textures created for CCLabelTTF (I got lots of text in credits) was also not released and loaded few times (did not check that but I can't see other reason why scene could take so much memory that app get killed after few push/pop scene).

**Comment by Birkemose** [comment]
I will look into this. Sounds like my mistake.

**Comment by vlidholt** [comment]
This is likely also related to the changing of scenes: #460

**Comment by Birkemose** [comment]
This should be fixed now. Was not related to #460.
@fins, if you can verify the fix, it would be great.
