### ISSUE TITLE
Changes to CCColor

### ISSUE THREAD

**Issue by Birkemose** [cocos2d/cocos2d-objc#458]
A couple of suggestions to CCColor.
TintTo and TintBy actions uses a different colour syntax. I guess this should be the same.
Also, I think color constructors should be colorRed, colorWhite, etc, and not redColor, whiteColor, as it is now.

**Comment by cocojoe** [comment]
Well I agree the autocomplete would look nicer however I don't think there is any need to diverge from the Apple's own convention?
https://developer.apple.com/library/IOS/documentation/UIKit/Reference/UIColor_Class/Reference/Reference.html

**Comment by Birkemose** [comment]
Whoa, I didn't even know that UIKit had gotten it all wrong. Why does redColor make sense, and colorRed doesn't?

**Comment by slembcke** [comment]
Dunno. It sort of does break the tradition of [NSThing thingWith:] naming convention. I agree we should stick with what NSColor/UIColor already do though.

**Comment by vlidholt** [comment]
I'm good either way. But I think the current naming is somewhat flawed, so i wouldn't mind changing it to colorRed etc.
