### ISSUE TITLE
Crash on push scene / problem with touches handling

### ISSUE THREAD

**Issue by leszek-s** [cocos2d/cocos2d-objc#459]
Sometimes when I push a scene then app crashes and it seems that push scene action is called two times. My code:

<pre>
- (void)creditsAction:(id)sender
{
    PlaySound(SOUND_CLICK);
    CCTransition *transition = [CCTransition transitionPushWithDirection:CCTransitionDirectionLeft duration:0.3];
    [[CCDirector sharedDirector] pushScene:[Credits sharedScene] withTransition:transition];
}
</pre>

I think this code was called two times when it crashed because I heard the sound played here two times. I'm not sure why this happend. I just pressed a CCButton (created and connected to this selector in SpriteBuilder) and I got a feeling that touch of my finger was catched two times or something like that. So maybe this is more a bug in touch handling than in scene management. However it is quite hard to reproduce this (maybe 1 time per 100 attempts). I checked that the reason of crash was NSAssert( scene != nil, @"Argument must be non-nil"); in - (void)replaceScene:(CCScene *)scene from CCDirector class. I hope this will tell you something more:

<pre>
(lldb) bt
* thread #1: tid = 0x2403, 0x398c0960 libobjc.A.dylib`objc_exception_throw, queue = 'com.apple.main-thread, stop reason = breakpoint 1.1
    frame #0: 0x398c0960 libobjc.A.dylib`objc_exception_throw
    frame #1: 0x31a1515c CoreFoundation`+[NSException raise:format:arguments:] + 100
    frame #2: 0x322eaab6 Foundation`-[NSAssertionHandler handleFailureInMethod:object:file:lineNumber:description:] + 90
    frame #3: 0x000dbee8 FTD`-[CCDirector replaceScene:](self=0x1d833350, _cmd=0x001f9027, scene=0x00000000) + 268 at CCDirector.m:572
    frame #4: 0x001c3ba6 FTD`-[CCTransition update:](self=0x1c58b440, _cmd=0x001f75e6, delta=0.01667933333374094) + 374 at CCTransition.m:232
    frame #5: 0x0010ef8e FTD`InvokeMethods(methods=0x1d833cf0, selector=0x001f75e6, dt=0.01667933333374094) + 222 at CCScheduler.m:87
    frame #6: 0x00110408 FTD`-[CCScheduler update:](self=0x1d833930, _cmd=0x001f75e6, dt=0.01667933333374094) + 276 at CCScheduler.m:493
    frame #7: 0x00181084 FTD`-[CCDirectorIOS drawScene](self=0x1d833350, _cmd=0x00202228) + 292 at CCDirectorIOS.m:120
    frame #8: 0x001821fe FTD`-[CCDirectorDisplayLink mainLoop:](self=0x1d833350, _cmd=0x002023dc, sender=0x1d83ee40) + 78 at CCDirectorIOS.m:372
    frame #9: 0x0042eb3a libglInterpose.dylib`-[DYDisplayLinkInterposer forwardDisplayLinkCallback:] + 306
    frame #10: 0x33602098 QuartzCore`CA::Display::DisplayLink::dispatch(unsigned long long, unsigned long long) + 160
    frame #11: 0x33601ff0 QuartzCore`CA::Display::IOMFBDisplayLink::callback(__IOMobileFramebuffer*, unsigned long long, unsigned long long, unsigned long long, void*) + 64
    frame #12: 0x35872fd6 IOMobileFramebuffer`IOMobileFramebufferVsyncNotifyFunc + 154
    frame #13: 0x325fc448 IOKit`IODispatchCalloutFromCFMessage + 192
    frame #14: 0x319df5da CoreFoundation`__CFMachPortPerform + 118
    frame #15: 0x319ea172 CoreFoundation`__CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE1_PERFORM_FUNCTION__ + 34
    frame #16: 0x319ea116 CoreFoundation`__CFRunLoopDoSource1 + 138
    frame #17: 0x319e8f98 CoreFoundation`__CFRunLoopRun + 1384
    frame #18: 0x3195bebc CoreFoundation`CFRunLoopRunSpecific + 356
    frame #19: 0x3195bd48 CoreFoundation`CFRunLoopRunInMode + 104
    frame #20: 0x355272ea GraphicsServices`GSEventRunModal + 74
    frame #21: 0x33871300 UIKit`UIApplicationMain + 1120
    frame #22: 0x000c29d6 FTD`main(argc=1, argv=0x2fd60c64) + 58 at main.m:14
</pre>

Variables from CCTransition update:

<pre>
Printing description of self:
&lt;CCTransition = 0x1c58b440 | Name = (null)&gt;
Printing description of self:
(CCScene) CCScene = {
  CCNode = {
    CCResponder = {
      NSObject = {
        isa = CCTransition
      }
      _userInteractionEnabled = NO
      _multipleTouchEnabled = NO
      _claimsUserInteraction = YES
      _exclusiveTouch = NO
    }
    _rotationalSkewX = 0
    _rotationalSkewY = 0
    _scaleX = 1
    _scaleY = 1
    _vertexZ = 0
    _position = (x=0, y=0)
    _skewX = 0
    _skewY = 0
    _anchorPointInPoints = (x=0, y=0)
    _anchorPoint = (x=0, y=0)
    _contentSize = (width=512, height=384)
    _transform = {
      a = 1
      b = 0
      c = -0
      d = 1
      tx = 0
      ty = 0
    }
    _inverse = {
      a = 0
      b = 0
      c = 0
      d = 0
      tx = 0
      ty = 0
    }
    _isTransformDirty = YES
    _isInverseDirty = YES
    _zOrder = 0
    _children = 0x1c566380 @"2 objects"
    _parent = nil
    _name = nil
    _userObject = nil
    _shaderProgram = nil
    _glServerState = CC_GL_ALL
    _orderOfArrival = 0
    _scheduler = 0x1d833930
    _actionManager = 0x1d81e690
    _isInActiveScene = YES
    _paused = NO
    _pausedAncestors = 0
    _visible = YES
    _isReorderChildDirty = NO
    _physicsBody = nil
    _displayColor = {
      r = 1
      g = 1
      b = 1
      a = 1
    }
    _color = {
      r = 1
      g = 1
      b = 1
      a = 1
    }
    _cascadeColorEnabled = NO
    _cascadeOpacityEnabled = NO
    _scaleType = CCScaleTypePoints
    _contentSizeType = {
      widthUnit = CCSizeUnitPoints
      heightUnit = CCSizeUnitPoints
    }
    _positionType = {
      xUnit = CCPositionUnitPoints
      yUnit = CCPositionUnitPoints
      corner = CCPositionReferenceCornerBottomLeft
    }
    _hitAreaExpansion = 0
  }
}
Printing description of self-&gt;_duration:
(NSTimeInterval) _duration = 0.3
Printing description of self-&gt;_incomingScene:
&lt;nil&gt;
Printing description of self-&gt;_outgoingScene:
&lt;nil&gt;
Printing description of self-&gt;_incomingTexture:
&lt;CCRenderTexture = 0x1c56f700 | Name = (null)&gt;
Printing description of self-&gt;_outgoingTexture:
&lt;CCRenderTexture = 0x1c5552e0 | Name = (null)&gt;
Printing description of self-&gt;_fixedFunction:
(CCTransitionFixedFunction) _fixedFunction = CCTransitionFixedFunctionPush
Printing description of self-&gt;_direction:
(CCTransitionDirection) _direction = CCTransitionDirectionLeft
Printing description of self-&gt;_color:
(ccColor4F) _color = {
  r = 0
  g = 0
  b = 0
  a = 1
}
Printing description of self-&gt;_drawSelector:
(SEL) _drawSelector = "drawFixedFunction"
Printing description of self-&gt;_outgoingOverIncoming:
&lt;nil&gt;
Printing description of self-&gt;_outgoingDestination:
(CGPoint) _outgoingDestination = (x=-512, y=0)
Printing description of self-&gt;_retinaTransition:
&lt;nil&gt;
Printing description of self-&gt;_outgoingSceneAnimated:
&lt;nil&gt;
Printing description of self-&gt;_incomingSceneAnimated:
&lt;nil&gt;
Printing description of self-&gt;_outgoingDownScale:
(float) _outgoingDownScale = 1
Printing description of self-&gt;_incomingDownScale:
(float) _incomingDownScale = 1
Printing description of self-&gt;_transitionPixelFormat:
(CCTexturePixelFormat) _transitionPixelFormat = CCTexturePixelFormat_RGB565
Printing description of self-&gt;_progress:
(float) _progress = 1
Printing description of self-&gt;_runTime:
(NSTimeInterval) _runTime = 0.3166901250006049
Printing description of delta:
(CCTime) delta = 0.01667933333374094
(lldb) </pre>

As you can se both _incomingScene and _outgoingScene were nil. Also similar thing happend once on popScene from credits screen to mainmenu. I clicked a back CCButton and I heard my sound that I play on popScene two times and the screen went black so I guess popScene was called two times and all my scenes were unloaded from ccdirector.

**Comment by Birkemose** [comment]
I am in the process of going over pushing and popping scenes (#457), so I will check this also.

**Comment by windqiang** [comment]
I think the problem still exists in cocos2d-swift v3.3.4
