### ISSUE TITLE
CCButtons do not work after popScene (without transition)

### ISSUE THREAD

**Issue by leszek-s** [cocos2d/cocos2d-objc#460]
I have two scenes created with SpriteBuilder with CCButtons to switch between them. On the first scene first button action switches the scene with:

<pre>
[[CCDirector sharedDirector] pushScene:optionsScene];
</pre>

on the second scene another ccbutton action switches the scene to the previous one with:

<pre>
[[CCDirector sharedDirector] popScene];
</pre>

after that CCButton on the first scene will not work, however if I change popScene to popSceneWithTransition then it will work fine.

**Comment by Birkemose** [comment]
This has been fixed. Was not related to #457 
@fins, if you can confirm the fix, it would be great.
