### ISSUE TITLE
CCLabelTTF Font Cropped

### ISSUE THREAD

**Issue by cocojoe** [cocos2d/cocos2d-objc#461]
Anyone noticed fonts having a few lines cut off at the top, possibly just certain fonts, I've not had time to do a visual comparison but it's certainly noticeable with a custom font I'm using.

**Comment by guykogus** [comment]
I've come across the same issue with an old project of ours. I believe the problem lies in the size defined by the font file. So the font may be defining the text as being a few pixels too short and so the top gets cropped. This is especially noticeable on capital latin letters with accents.
