### ISSUE TITLE
Problems with transitions and physics

### ISSUE THREAD

**Issue by Birkemose** [cocos2d/cocos2d-objc#463]
Default, transitions are non-animated, while physics will run anyways. I guess we have to find a way to synchronise this. I guess physics would have to test if a scene was a transitions type, and then test for animation.

Also, I tried using the paused property of the physics node. 
If I set it in onEnter, and clear it in onEnterTransitionDidFinish, it seems to work. 
If I set it in init, and clear it in onEnterTransitionDidFinish, it results in the overridden update: of the attached physics nodes, not to be called anymore.

While the first approach is probably the more correct, the later might result in a lot of bug reports.

**Comment by slembcke** [comment]
Forgot about this. Physics doesn't seem to be the only issue. The spinning Cocos icon in the current templates have the same issue. The icon's rotation pops after the transition finishes. This sort of implies that everything in the scene is scheduled and running while the transitions happen.

I tried pausing the entire scene when the transition starts and then unpausing it when the transition finished. It left the scene paused and I'm not really sure why. It might be an order-of-operations thing. I'm not sure I understand the sequence of events for transitions well enough yet.

**Comment by Birkemose** [comment]
I fixed the transitions, so that scenes are now correctly paused and resumed, according to animation settings in the transition.
However, I am pretty sure, that physics are running, even if scene.paused = YES

**Comment by slembcke** [comment]
Shouldn't be. CCPhysicsNodes schedule their fixedUpdate: calls like a regular node. It's a bug if it is. I never made unit tests for a lot of the CCNode scheduling functionality so I can't say very confidently that it works as intended other than some manual testing I did a couple of months ago.

**Comment by Birkemose** [comment]
It seems that setting paused for a node, stops update:, but not any scheduled action.
It also does not stop physics and touch responder.
I am pretty sure I do not test for paused in touch responder, as I had to implement the getter for paused in CCNode. It simply wasn't there.

**Comment by Birkemose** [comment]
This is now #495
