### ISSUE TITLE
spriteWithSpriteFrameName is not included in the interface

### ISSUE THREAD

**Issue by vexxed** [cocos2d/cocos2d-objc#466]
The spriteWithSpriteFrameName method in CCSprite was available in 2.1, but is no longer included in the interface for 3. The implementation still exists in the .m file, and adding it to the interface works correctly. Perhaps this was accidentally removed?

**Comment by cocojoe** [comment]
Use spriteWithImageNamed instead, it's multi purpose.

On 3 January 2014 05:15, vexxed notifications@github.com wrote:

> The spriteWithSpriteFrameName method in CCSprite was available in 2.1, but
> is no longer included in the interface for 3. The implementation still
> exists in the .m file, and adding it to the interface works correctly.
> Perhaps this was accidentally removed?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/cocos2d/cocos2d-iphone/issues/466
> .

## 

Martin
