### ISSUE TITLE
Physics debug draw

### ISSUE THREAD

**Issue by Birkemose** [cocos2d/cocos2d-objc#470]
I couldn't get physics debug draw to work, until I realised it is not visible on a black background. Argh ...
I guess many will start toying with physics on a blank screen, so I think debug drawing should be default on, and that it should be visible on a black background.

**Comment by slembcke** [comment]
Oh? There might be something else wrong then. I've always started using a black background:
![debug draw](http://files.slembcke.net/upshot/upshot_nhiSRrtL.png)

The default colors might be a little too transparent though maybe?

**Comment by Birkemose** [comment]
Hmm ... I only see colour, if there is another colour. On a black background, there is nothing. Weird.
Latest version. Your setup. No messing with anything.

**Comment by cocojoe** [comment]
Odd, I can see a faint pink quad against black.

On 8 January 2014 09:16, Birkemose notifications@github.com wrote:

> Hmm ... I only see colour, if there is another colour. On a black
> background, there is nothing. Weird.
> Latest version. Your setup. No messing with anything.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/cocos2d/cocos2d-iphone/issues/470#issuecomment-31815645
> .

## 

Martin

**Comment by Birkemose** [comment]
Ahh ... if I turn the light up on my monitor, I can see the faintest dark red sphere imaginable. It is so faint, that to watch Scott's image, you would have to wear sunglasses.

**Comment by slembcke** [comment]
Hmm. I'll change the default colors to be more opaque then. I had made them subtle so that you could still see the graphics below them to make sure everything was lined up right. I guess I went a little too far with the transparency.

**Comment by Birkemose** [comment]
Maybe we could make the uber option, and make the draw colour available to the public? ;)

**Comment by slembcke** [comment]
Yeah, was considering that too. A shape and joint debug color should be satisfactory I expect.

**Comment by slembcke** [comment]
Eh. I decided not to make a last minute API change like that. I doubled the opacity of the colors. I made them into constants for now if anybody wants to dig into the code and adjust them. Can consider fancier configuration later.
