### ISSUE TITLE
CCTexture contentScale handling

### ISSUE THREAD

**Issue by leszek-s** [cocos2d/cocos2d-objc#472]
I noticed that -(NSString_) fullPathForFilename:(NSString_)filename contentScale:(CGFloat *)contentScale method in CCFileUtils class by default is setting texture contentScale by directory name and is ignoring the suffixes (-hd etc.) in my filenames that I use to create sprites which I do not have anywhere in my spritebuilder (.ccb) scenes. I'm not sure if this is a bug or not but some comments in the code say that filename suffixes are used by default and not the directory names. My project was generated by spritebuilder if that changes something. I'm wondering if it would be possible to enable both methods (filename suffixes and directory names) at the same time? Maybe then it would be more convenient to use.

**Comment by slembcke** [comment]
So I think this is a CCFileUtils issue and not a texture one. You cannot currently configure CCFileUtils to use both suffixes and directories. They are mutually exclusive. This is something I would _love_ to fix if we refactor CCFileUtils in the near future.

**Comment by vlidholt** [comment]
Agreed – it should be possible to use both!

**Comment by slembcke** [comment]
Coalescing all the the CCFileUtils and texture loading ideas for 3.2 and am adding this to the list.
