### ISSUE TITLE
CCFileUtils Cleanup

### ISSUE THREAD

**Issue by slembcke** [cocos2d/cocos2d-objc#474]
CCFileUtils is sort of a mess. This seems like a common sentiment. Too many small changes over too many years without enough refactoring. I feel like we can simplify the code, and make it easier to config without losing any functionality. Is this a good list of features to retain?
- Convert generic to device specific file path (by suffix or directory).
- Return the scale of an asset.
- Support path aliases. (ex: when you request to load somefile.png it will actually load somefile.pvr)

That is not a large feature set for how complicated the code is. There has been discussion of some other features as well.
## Builtin support for downloading high res assets. (Easy-Hard)

@vlidholt brought up the idea of streaming and caching 4x assets from the internet (bring your own server). I think there are a couple of options for implementing this.

Prompt and download: (Easy)
Ship your game with 2x assets only. Use automatic downscaling for 1x support (or include 1x art). Detect if the game is launched on a retina iPad and prompt them with a dialog asking if they'd like to download the optional HD art pack. The loading could happen in a background thread, allowing the player to start playing while they wait. If individual images are made available as they download, it still has some benefits of streaming.

Stream and cache: (Medium, possibly hard)
This was Viktor's original idea. Each time an image is loaded, the texture cache can check a server URL and start downloading the 4x image. When the download finishes, it can reload the texture. Some parts of Cocos need a texture's pixel size. We would need to fix this first. I'm also not sure how intelligently we would need to schedule this. If the game spends several minutes downloading splash screen and menu graphics while you are already playing the game it won't seem so magical.
## Sprite Sheet / Directory equivalence. (easy)

So I actually thought we already had this implemented due to how [CCSprite withImageNamed:] operates, but apparently not. This seems like it would be a nice feature to have so deciding to transition to sprite sheets later wouldn't be as much of an issue. I understand the code for this is already ready somewhere?
## Simplify Configuration.

My idea is that a dictionary could make configuring CCFileUtils much simpler. Perhaps best explained using examples. The default retina iPad search rules could look like this if a dev typed them in explicitly:

```
if(UI_USER_INTERFACE_IDIOM() == UIUserInterfaceIdiomPad && [UIScreen mainScreen].scale > 1){
    [CCFileUtils sharedWhatever].searchRules = @[
        @{@"suffix":@"-ipadhd", @"contentScale":@4},
        @{@"suffix":@"-ipad", @"contentScale":@2},
        @{@"suffix":@"-iphone5hd", @"contentScale":@2},
        @{@"suffix":@"-hd", @"contentScale":@2},
        @{@"suffix":@"", @"contentScale":@1},
    ];
}
```

Some notable things, it's possible to make one clear list instead of calling a dozen different methods. Each suffix or directory has an explicit value for the content scale. Right now the contentScale is a hardcoded assumption in CCFileUtils. Lastly, instead of having a lot of device specific methods in CCFileUtils, allow the developer to take care of that. It's already a mess to try and cover all of Apple's hardware within the API itself, and it will almost certainly get more complicated in the future if left this way.

We could easily allow the dev to mix suffixes and directories. Let's say a handy use for this could be optionally downloading retina iPad art from the internet into the documents directory. Check the directory first, otherwise fall back to using suffixes.

```
NSString *path_to_downladed_images = ...;

[CCFileUtils sharedWhatever].searchRules = @[
    @{@"directory":path_to_downladed_images, @"contentScale":@4},
    @{@"suffix":@"-ipad", @"contentScale":@2},
    @{@"suffix":@"-hd", @"contentScale":@2},
    @{@"suffix":@"", @"contentScale":@1},
];
```

If we mix this with the automatic downscaling feature, you could have a very simple setup. Add all images normally (no buggy Xcode folder references required), and tell Cocos that they are 2x art. The setup for _all_ devices could then be:

```
[CCFileUtils sharedWhatever].searchRules = @[
    @{@"directory":path_to_downladed_images, @"contentScale":@4},
    @{@"suffix":@"", @"contentScale":@2},
];
```

You could ship your game with only 2x art. On a 1x device it could downscale, and on a 4x device it download and cache the art from the internet (see next item). This would give you a very small download size while still supporting all devices. When loading a texture that has a higher contentScale than the director, downscale automatically if possible.

```
[CCFileUtils sharedWhatever].searchRules = @[
    @{@"directory":path_to_downladed_images, @"contentScale":@4},
    @{@"suffix":@"", @"contentScale":@2},
];
```

Or you could go for the extremely simple setup and tell Cocos that all art is 4x, and have it downscale as needed. No suffixes. No directories. Just work load the exact file that was asked for and make it work.:

```
[CCFileUtils sharedWhatever].searchRules = @[
    @{@"suffix":@"", @"contentScale":@4},
];
```

**Comment by slembcke** [comment]
I also had some ideas about CCAssetInfo that I described in this thread:
https://github.com/cocos2d/cocos2d-iphone/issues/480

**Comment by LearnCocos2D** [comment]
More suggestions:

a) The option to downscale and save the downscaled images, in order to keep bundle size small while keeping the memory usage on non-Retina devices in check. Though CCFileUtils is probably not the place to implement this.

b) Allow using a documents (app data) path as a file search path, to ease development of apps which are downloading updated resource files from the web (or from a local network during development). And to support a).

The idea is to have your app load bundle resources when first installed. But as soon as the app downloads an updated version of any bundled resource file to the documents directory the app will from then on load the file from the documents/appdata dir rather than the one in the bundle because the same file with the same name located in documents (app data) has a higher priority. This may need informing the caches so they uncache the bundle file.

This feature is specifically great during development. Keep the app running, send updated files (perhaps via Spritebuilder) directly to the running app, tap the "reload scene" button or perhaps refresh (some) files automatically and you end up with an almost immediate turnaround time, bypassing compilation, deployment, launching and going through the regular game menus to load a specific scene. I have used this in Sprite Kit and wouldn't want to miss it for the world. ;)

**Comment by slembcke** [comment]
I was about to ask if you had any ideas about this since you've been looking at the CCFileUtils code lately.

a) There is a separate enhancement issue for that with a working prototype. #473 I've considered caching the image after downscaling, but am undecided. Writing out a .png with libPNG is pretty easy so it might be a good thing to try.

b) Yes definitely. You'd just need to add a custom search directory rule for it.

Dynamic reloading: This was discussed a few months ago using an HTTP server. It's trivial to do with Cocoa, we just need to switch CCFileUtils to use URLs instead of simple paths.

Also, I've reconsidered the idea of using dictionaries in favor of a CCAssetRule class. I think it would make it much more readable and give you auto-complete support. Ex:

```
[CCFileUtils sharedWhatever].searchRules = @[
    @{@"directory":@"NeatGraphics", @"contentScale":@4},
];

// Would become

[CCFileUtils sharedWhatever].searchRules = @[
    [CCAssetRule ruleWithDirectory:@"NeatGraphics" contentScale:4],
];
```

**Comment by vlidholt** [comment]
Just some notes on this, b) is supported by the current version and should definitely be there.

**Built in support for downloading high-res images**
This must not necessarily be part of the CCFileUtils. I'm thinking this could be a sub-class of CCSprite, you provide the sprite with both an initial image to display, and URL. The linked URL is loaded in background, saved in the apps cache (possibly with different caching options) so it's loaded quickly next time. Example usages are: dynamically loading high-res assets (I know Pocket Gems use this approach for their game maps & non-critical image assets etc) or to download images of people from Facebook (use a placeholder image and dynamically load the actual image).

**SpriteSheet/Directory equivalence**
This is currently on the texture level and not part of the CCFileUtils. I think this is a reasonable approach.

**Simpler Configuration**
I like the idea of simplifying the configuration. Something to take into consideration here is the backwards compatibility and how we want to handle that.
