### ISSUE TITLE
Xcode Asset Pipeline

### ISSUE THREAD

**Issue by slembcke** [cocos2d/cocos2d-objc#475]
So one thing that Unity users really love about Unity is the asset pipeline (how easy it is to get their photoshop files, sounds and 3D models into Unity). XNA devs mention liking it's asset pipeline too, but I know little to nothing about XNA.

In particular, consider the typical artist working in Photoshop. They edit their .psd file, then export it to -hd.png (which PS's save-as dialog makes strangely difficult). Then they downscale it and export again. Finally they can press run in Xcode to see the changed art. After testing it, they have to commit 3 files to source control. Really a pain when you are tweaking little things!
## Default build rule in the templates to convert .psd files to .png. (Easy)

Add .psd files directly to your Xcode target and have it automatically convert them to .png files. This is _very_ handy. I personally use it on almost every project I do. It makes it really easy to edit a texture, hit save in PS, run in Xcode and see the change in a couple seconds. There really is little downside and I have working code for it right now.
## Scriptable asset importing. (Medium)

Have an Xcode script phase that can encrypt files, recompress all or specific files with specific settings, etc. I haven't extensively thought about this. Possible implementations would be to have folder references with .ccasset extensions that are processed by a build rule, or a global script that runs. This would make it easier to optimize the file size of a project by making it easy to experiment with compression settings.

Anything we do would be limited by Xcode build rules, but I think we could add a lot of nice features.

**Comment by cocojoe** [comment]
@slembcke Anything that improves work flow is great, obviously the psd ->
png would be rather nice with auto batching in the future.

In regards to scripting, I made a simple script for encrypting assets (in
my case json game levels) with AES256, so you add a folder reference to
your project it will then loop through that directory/encrypt and then add
the encrypted files into your application.   I added a decrypt category for
NSData, all runs fine as well under apportable.

On 6 January 2014 23:06, slembcke notifications@github.com wrote:

> So one thing that Unity users really love about Unity is the asset
> pipeline (how easy it is to get their photoshop files, sounds and 3D models
> into Unity). XNA devs mention liking it's asset pipeline too, but I know
> little to nothing about XNA.
> 
> In particular, consider the typical artist working in Photoshop. They edit
> their .psd file, then export it to -hd.png (which PS's save-as dialog makes
> strangely difficult). Then they downscale it and export again. Finally they
> can press run in Xcode to see the changed art. After testing it, they have
> to commit 3 files to source control. Really a pain when you are tweaking
> little things!
> Default build rule in the templates to convert .psd files to .png. (Easy)
> 
> Add .psd files directly to your Xcode target and have it automatically
> convert them to .png files. This is _very_ handy. I personally use it on
> almost every project I do. It makes it really easy to edit a texture, hit
> save in PS, run in Xcode and see the change in a couple seconds. There
> really is little downside and I have working code for it right now.
> Scriptable asset importing. (Medium)
> 
> Have an Xcode script phase that can encrypt files, recompress all or
> specific files with specific settings, etc. I haven't extensively thought
> about this. Possible implementations would be to have folder references
> with .ccasset extensions that are processed by a build rule, or a global
> script that runs. This would make it easier to optimize the file size of a
> project by making it easy to experiment with compression settings.
> 
> Anything we do would be limited by Xcode build rules, but I think we could
> add a lot of nice features.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/cocos2d/cocos2d-iphone/issues/475
> .

## 

Martin
