### ISSUE TITLE
Free particles does not work with scaled particle systems

### ISSUE THREAD

**Issue by Birkemose** [cocos2d/cocos2d-objc#484]
When particle systems are scaled, free particles start to move with emitter position also.
This has been a bug since 1.x

Scaling is very useful, as particles are absolute sized, and thus needs scaling, according to device. The alternative will be separate plists.

Temporary fix:
Set startSize, endSize, gravity, etc directly.

**Comment by slembcke** [comment]
Referencing this issue so it shows up in #1163
