### ISSUE TITLE
Newton spheres in template does not deallocate

### ISSUE THREAD

**Issue by Birkemose** [cocos2d/cocos2d-objc#488]
Newton spheres created, does not deallocate.
Not really sure why.

**Comment by slembcke** [comment]
Think it's CCPhysics related? I'll look into it.

I like the faked lighting effect. It looks really nice.

**Comment by Birkemose** [comment]
I don't know. The newton scene itself is deallocated, and just from browsing the code, I couldn't see anything wrong with it. I also made a compound rope object, also consisting of physics, sprites and joint, but it deallocates fine.

**Comment by slembcke** [comment]
Oh this is definitely a me bug. Something I've tested by hand in the past but never made a unit test for...

CCPhysicBody objects were creating a retain cycle with the node they attach to. This wasn't supposed to happen as long as onExit got called (if it didn't you'd be in even bigger trouble), but apparently I broke that at some point.

I committed a fix and some unit tests for it.
