### ISSUE TITLE
Setting paused for a node, does not entirely pause it

### ISSUE THREAD

**Issue by Birkemose** [cocos2d/cocos2d-objc#495]
Setting paused for a node, stops update:, but it does not stop any running action.
It does also not stop touch responder, and apparently also does not stop physics.
I can not really tell if the later is possible, i.e., stopping physics for only some objects. If not, having to set the paused property of the physics node, make sense.
In that case. Can a CCScene tell if a physics node has been attached to it?

**Comment by slembcke** [comment]
Definitely a bug. Haven't found the issue just yet. Something is wrong with the recursive part of the pausing.

It was never particularly well tested, but it definitely worked at one point...

**Comment by slembcke** [comment]
Oh jeez. (_facepalm_) It was because I refactored a 10 line function at some point and renamed some of the variables. Sort of like shadowing, but separated by time. -_-

I have a fix and a couple UI tests. Going to try adding a couple unit tests too. The singletons might make that annoyingly difficult though.

**Comment by slembcke** [comment]
Oh also. For discussion, you cannot pause part of a simulation. Pausing a CCNode with a physics body attached will pause it's update: and fixedUpdate: calls as well as it's actions, but not it's physics. You have to pause an entire CCPhysicsNode along with it's children if you want to pause physics.

Pausing the physics of only some objects in a physics simulation is really problematic. Should it remove them from the simulation until they are unpaused? Should it make them static? There are a lot of possibilities that we could do that all sort of make sense, but have a lot of issues. Putting the physics node in charge of the whole simulation was the cleanest way to do it I thought.

A CCScene cannot tell if there is a CCPhysicsNode unless it iterates the hierarchy.

**Comment by Birkemose** [comment]
Thanks a lot. I will try test tomorrow, and report back what I find.

Not really surprised I can't pause a physics object. Probably not relevant either. Should we leave it for now?

**Comment by slembcke** [comment]
Oh, and touch responder... Should it pause the input of a node? I'm not so sure that is a good idea. I guess I see advantages either way. Unfortunately this is sort of one of those feature interaction explosions where every feature has to work with every other feature in some reasonable way.

The code would end up in the private [CCNode wasRunning:] method if it's desired. That handles both adding/removing nodes from the scene as well as pausing.

**Comment by Birkemose** [comment]
Yeah, I think it makes sense to keep responder running. All seems to work now. Thanks.
