### ISSUE TITLE
MIT credits

### ISSUE THREAD

**Issue by Birkemose** [cocos2d/cocos2d-objc#496]
I have been adding my name to the MIT license in the files I have expanded / created, but since everybody is cross-contributing (is that a word?), I think, that for all the core cocos2d stuff (not sprite builder specific, chipmunk, kazmath, etc), we should change it to copyright 2013-2014 Cocos2D Authors.

This will basically be the files in the cocos2d folder when you install the template.

Maybe it would be a good idea, to then create a license file, with the current authors. That way, nobody will be forgotten, even if they leave the project for other jobs.
Does that sound reasonable?

**Comment by dominik-hadl** [comment]
I like this idea :+1: There actually is an AUTHORS file in the project root, with some of the authors listed, so maybe that should be updated?

**Comment by slembcke** [comment]
Makes sense I guess. I've only added my name to files I actually created. I figured "why not?" more than "I deserve credit!". If I really wanted credit for something, git already does a fine job of tracking which code I wrote (and which bugs I made, heh).

**Comment by Birkemose** [comment]
Okay. That is the way we do it then.

**Comment by cocojoe** [comment]
Makes sense, be good to replace all headers with one standard license.

On 10 January 2014 19:35, Birkemose notifications@github.com wrote:

> Okay. That is the way we do it then.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/cocos2d/cocos2d-iphone/issues/496#issuecomment-32057996
> .

## 

Martin

**Comment by vlidholt** [comment]
I think we should remove the AUTHORS file because it's a lot of work to maintain it. Instead, maybe we can create a link to the contributors page on Github. This way we make sure that nobody is left out.

**Comment by Birkemose** [comment]
I have updated the AUTHORS file by scanning the git repo, for everybody who has contributed.
I have added some text in AUTHORS. Please edit Your own if you need to.
