### ISSUE TITLE
Texture coordinate precision issues.

### ISSUE THREAD

**Issue by slembcke** [cocos2d/cocos2d-objc#501]
I came across this thread in the forums:
http://www.cocos2d-iphone.org/forums/topic/possible-bug-of-cocos2dtexture-packer/

The summary is that texture coordinates sometimes don't line up quite right for sprite atlases. This can cause animations to jitter or weird artifacts where sprites bleed into one another. It seems to be caused by using mediump as the texture coordinate precision which makes sense given the GLSL specs.

There is another thread referenced about switching the shaders to highp, but at a surprisingly high performance cost. I honestly wouldn't have expected there to be any performance difference since it's not used for a dependent texture read.

If there isn't a simple shader fix that doesn't break performance, then the only other thing I can think of is to add debug warnings to sprite frame creation to let somebody know that their texture coordinates may be truncated. An easy fix at the texture packing level is to align the texture coordinates to a 1k grid to fit within the guaranteed mediump accuracy range.

**Comment by vlidholt** [comment]
"An easy fix at the texture packing level is to align the texture coordinates to a 1k grid to fit within the guaranteed mediump accuracy range."

Can you describe this in more detail and I'll make sure this happens in SpriteBuilder's texture packer.

**Comment by slembcke** [comment]
When packing a sprite sheet that is 1024x1024 or less, you don't need to do anything. When packing a 2048 sprite sheet, make sure that all of the coordinates are divisible by 2. For a 4096 sprite sheet, make sure they are divisible by 4. Etc.

This should waste fairly little space in the atlas overall, but ensures that the texture coordinates can be represented exactly by a mediump shader parameter. Using non-POT texture sizes for the atlas might still cause issues since you can't cleanly store non-POT denominators in a float.

**Comment by vlidholt** [comment]
Ok, thanks for the explanation, will make sure this happens in the SB sprite packer.

**Comment by slembcke** [comment]
This is fixed in the 3.1 branch due to precision changes. I think we should leave it "as is" in 3.0 to avoid creating new issues since it's been an issue since 2.0 and has come up relatively rarely.
