### ISSUE TITLE
Minor last minute installer issues.

### ISSUE THREAD

**Issue by slembcke** [cocos2d/cocos2d-objc#502]
Sorry for the 11th hour issue. I was testing it to make sure everything worked right.

First issue is that the default install.sh script still downloads Chipmunk from GitHub even if it has a local checkout of Chipmunk. We should make the installer include this in it's package so it doesn't need to download separately. Should be easy, I'll look into that now.

Secondly, the install.sh script points at Chipmunk2D/master. So it sort of limits me from making changes. Should we make a cocos2d fork of Chipmunk (I need Lars to do that) or should I make a cocos2D branch in the main Chipmunk repository (I can handle that)?

One more extremely minor issue is that the build installer script doesn't blacklist certain directories such as build, DerivedData, .git, or other directories that shouldn't end up in the installer. That can greatly increase the size of the installer download if you don't run the script from a very clean exported checkout.

**Comment by cocojoe** [comment]
A download of Chipmunk could be added to the build_installer, would just need modify the template installer to check first otherwise download (if you're using it from Git vs an installer build).

That was one of the original issues I forgot about was the download of 'master' rather than say a 'stable' certified branch.

Are you talking about the installer/build_installer.sh ?
As it does exclude .git and installer (the specified exclusion options), otherwise it would be huge.

```
tar -C ../. --exclude='.git' --exclude='installer' -zcf install.tar.gz .
```

**Comment by slembcke** [comment]
Oh hrm. When I ran it this morning I had a 230MB installer app. When I opened up the bundle and peeked in the tarball, it included .git files, and DerivedData. Let me double check on that though.

I modified the instal.sh script to download Chipmunk only if external/Chipmunk doesn't exist, and to use git submodule update if possible over a tarball download:
https://github.com/cocos2d/cocos2d-iphone/commit/e3e3dfb2e00415359afb23a63c0840947cbd0dc3

I should probably have it squelch the git output though... Whoops.

**Comment by slembcke** [comment]
In regards to excluding .git, I'm just can't read. -_- The .git/ directory was not included in the build, but some of the other minor files like .gitignore were. I just read it wrong. No problem here... I added a DerivedData, build, and api-docs to the exclude list too.

With the install.sh change I made, it installs Chipmunk correctly without needing a download now. I'm happy with that. I'll make a branch and tags in the Chipmunk for Cocos in the repo instead of having a fork. I think that will require less work for everybody. Can always be changed later.

**Comment by cocojoe** [comment]
I just noticed that when I did a clean checkout of cocos2d-iphone that the
Chipmunk sub module is checked out anyway into external/Chipmunk so the
build_installer includes it in the install.tar.gz.  Imagine the install.sh
just has a bit of legacy relating to downloading etc

On 13 January 2014 19:00, slembcke notifications@github.com wrote:

> In regards to excluding .git, I'm just can't read. -_- The .git/ directory
> was not included in the build, but some of the other minor files like
> .gitignore were. I just read it wrong. No problem here... I added a
> DerivedData, build, and api-docs to the exclude list too.
> 
> With the install.sh change I made, it installs Chipmunk correctly without
> needing a download now. I'm happy with that. I'll make a branch and tags in
> the Chipmunk for Cocos in the repo instead of having a fork. I think that
> will require less work for everybody. Can always be changed later.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/cocos2d/cocos2d-iphone/issues/502#issuecomment-32199392
> .

## 

Martin

**Comment by slembcke** [comment]
I changed the Chipmunk download URL to be a stable tag.. Those were my only concerns. I'll close the issue in a bit unless anybody else has anything.

**Comment by dominik-hadl** [comment]
@slembcke I originially had the git checking out submodule part in the install.sh script, however I decided to remove it. The reasons are simple, it was just an option how to create more problems for users installing cocos2d. Imagine a  situation where an experienced user makes changes in the Chipmunk submodule and then he installs cocos2d. If the change was major, the templates may not compile. 

Also, think of people having modified git (probably very rare, but still) or people not having git in their PATH. 

I simply thought that Chipmunk isn't that big it couldn't be downloaded. However, there are two options how to make the download much faster - either way downloading a "release" of Chipmunk (think of a zip file containing only chipmunk and obj-chipmunk) or downloading all files from folders "include" and "src" (for both non-objc and objc) separately.

**Comment by dominik-hadl** [comment]
Another thing for the git submodule is that you have to init it first, otherwise it will not update anything - if you decide to do it this way then don't forget to add it to the script. (you can run 'git submodule update --init')

**Comment by slembcke** [comment]
So the use cases I considered:
- Downloaded from an archive of some sort. If they are some sort of official archives, I can't imagine why we wouldn't just include the external/Chipmunk directory. No downloading or Git required in this case. The installer app follows this path.
- Checked out from git (so the .git directory exists). It should be relatively safe to run "git submodule update" then to make sure that the submodule is checked out and up to date.
- They downloaded an archive from GitHub which doesn't include the external/Chipmunk directory. The install.sh script will download Chipmunk into the correct place.

It's possible to get a weird archive from somewhere, or copy a git repository to a machine without git, but I don't feel like that's going to be nearly as common as trying to run the installer without having internet connectivity. GitHub also tends to go down fairly commonly too.

If Git submodules worked in a reasonable way like similar constructs in other VCS systems, I feel like this wouldn't even be an issue. As it is, git submodules are one of the most frustrating Git features. Using them on a project like this is basically required for sanity, but the default Git behavior is to check out an incomplete repository without it's submodules. When trying to export the repository it does the same thing!?!?

**Comment by slembcke** [comment]
Is it an issue if the user modifies the code before running the installer? They would have the same problem if they edited the Cocos2D source before running the installer script. Chipmunk isn't a special exception to that.

You are right about the submodule init part. I got the crazy misinformed idea that they had made the "--init" parameter to the update command default. Why on earth would Git do something sensible like that to avoid a useless step. -_-

**Comment by dominik-hadl** [comment]
Ok, I was just saying what happened to me and a few other people when I had this submodule feature in the script, that's why I thought that the only way how to obtain a correct copy of the submodule would be by downloading it.

Btw. as for changing where Chipmunk downloads from you could easily create an url redirect or something similar, which you could update to anything you want without doing anything with the actual installer.

**Comment by slembcke** [comment]
@nickskull Though we need the download location to be versionable so that when we release Cocos 3.1+ with a new Chipmunk reference, the 3.0 installer doesn't try installing a newer and potentially incompatible version of Chipmunk.

**Comment by dominik-hadl** [comment]
Then setting it to a specific commit is probably the easiest way.

**Comment by cocojoe** [comment]
This has created a problem with the 3.0 Preview Download on Cocos2D which basically just grabs the repo archive.  https://github.com/cocos2d/cocos2d-iphone/archive/develop-v3.zip

However when you run install.sh it assumes that you have used Git and expects the chipmunk submodule files to be present, which they will not be.  Really it should download if files not present.

Now this issue should go away when the installer app goes up instead however it's not ideal experience for anyone trying the preview.

**Comment by slembcke** [comment]
Oh. My mistake. :-\ I assumed that the external/Chipmunk directory would not be present in the archive but it's there as an empty directory. I tested it by deleting the Chipmunk directory and not using the archive.

To check if it should download the Chipmunk archive it did this: `elif [[ ! -d "$SCRIPT_DIR/external/Chipmunk" ]]; then`. Changing the path to be something inside the directory does work however. I'll make a fix for that.

**Comment by slembcke** [comment]
Verified and pushed. I hate git submodules. :(
