### ISSUE TITLE
cocos2d.h can't be included in a precompiled header for iOS.

### ISSUE THREAD

**Issue by scottandrew** [cocos2d/cocos2d-objc#504]
Can not include cocos2d.h in an apps precompiled header. This appears to be an issue with OpenAL classes. 

Setting #define OBJECTAL_CFG_USE_COCOS2D_ACTIONS 0 to 1 doesn't help.

**Comment by Birkemose** [comment]
Removing OALSimpleAudio.h from cocos2d.h, makes prefix work. No idea why yet.
As openAL is really heavy on macros, it might be a case of something not being defined yet, as prefix is loaded early.

**Comment by cocojoe** [comment]
Tedious

On 15 January 2014 10:38, Birkemose notifications@github.com wrote:

> Removing OALSimpleAudio.h from cocos2d.h, makes prefix work. No idea why
> yet.
> As openAL is really heavy on macros, it might be a case of something not
> being defined yet, as prefix is loaded early.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/cocos2d/cocos2d-iphone/issues/504#issuecomment-32350454
> .

## 

Martin
