### ISSUE TITLE
Open AL Initialisation in CCAppDelegate

### ISSUE THREAD

**Issue by cocojoe** [cocos2d/cocos2d-objc#505]
Unless anyone seriously objects, I'm going to add the Open AL initialisation into the CCAppDelegate as the boot up is not noticeable at this stage however if the sound init occurs the first time a user plays a SFX then it will create noticeable lag resulting in poor experience and unnecessary forum posts :)

In all my games I shift it into AppDelegate anyway.

**Comment by Birkemose** [comment]
Sounds reasonable. Maybe also leave a comment or search phrase for those who wants to replace openAL?

**Comment by slembcke** [comment]
Seems like a good idea.
