### ISSUE TITLE
CCActionRotateTo doesn't behave as expected.

### ISSUE THREAD

**Issue by cocojoe** [cocos2d/cocos2d-objc#511]
Each time CCActionRotateTo is ran the node will reset back to 0 before running the next CCActionRotateTo action. Rather than rotating relative to its new angle.

If you modify the action source to use 'rotation' instead of rotationSkewX, rotationSkewY it works as you would expect it to.

Could do with being looked at as I use it in my tutorials and it makes it look broken.

**Comment by slembcke** [comment]
Hmm. So I think that was Birkemose's fix for a similar issue. I can't find the issue, but I found the commit:
https://github.com/cocos2d/cocos2d-iphone/commit/8674d28da4ce292ef7fe4653753ad3c651cffc95

**Comment by cocojoe** [comment]
That logic is already applied to CCRotateTo, the issue appears to be in node setRotation:  

As there is a physics body it will never update the rotationSkewX/Y however CCRotateTo will use these to get its initial bearing on each run.

```
// getters synthesized, setters explicit
-(void) setRotation: (float)newRotation
{
    CCPhysicsBody *body = GetBodyIfRunning(self);
    if(body){
        body.absoluteRadians = -CC_DEGREES_TO_RADIANS(newRotation + NodeToPhysicsRotation(self.parent));
    } else { 
        _rotationalSkewX = newRotation;
        _rotationalSkewY = newRotation;
        _isTransformDirty = _isInverseDirty = YES;
    }
}
```

As physics is involved I'm not sure what should be done....

**Comment by cocojoe** [comment]
@slembcke Any reason why I can't just update Skew regardless in this method? The world did not end when I did so.

**Comment by slembcke** [comment]
Not sure I understand the issue enough to see what's causing it. Let me switch branches quick and try to reproduce it.

When a physics body is assigned to a node it uses the transform information from the physics instead of the CCNode position/rotation ivars to avoid state synchronization bugs. Setting the ivars shouldn't really do anything.

**Comment by slembcke** [comment]
Fixed. Not a very DRY solution, but it works.
