### ISSUE TITLE
Bug: Scheduling custom selectors before onEnter causes update method not to be scheduled

### ISSUE THREAD

**Issue by Ben-G** [cocos2d/cocos2d-objc#515]
Because of this check in `onEnter` in CCNode, the update method is not scheduled automatically if a developer has already scheduled any other selector, e.g. in the init method:

```
-(void) onEnter
{
   ...

    if(![_scheduler isTargetScheduled:self]){
        [_scheduler scheduleTarget:self];
    }

    ...
}
```

**Reproduce Problem:**

```
- (id)init 
 {
    self = [super init];

    if (self) {
        [self schedule:@selector(test) interval:0.1];
    }

    return self;
}
```

Implement `test` and `update:`

```
- (void)update:(CCTime)delta {
    CCLOG(@"Update");
}

- (void)test {
    CCLOG(@"Test");
}
```

-> only `test`will be called.

**Workaround:**

Schedule the selector in `onEnter` (or later):

```
- (void)onEnter {
    [super onEnter];

    [self schedule:@selector(test) interval:0.1];

}
```

This workaround works fine, however I can image the behaviour is confusing for many developers. Ideally the check in `onEnter` should only check if `update` has already been scheduled.

**Comment by slembcke** [comment]
I think the reason for checking if the node has been scheduled already is historical at this point. I remember adding it, but not the specific reason why. Rescheduling an existing target should be safe and is handled specifically... I don't see any reason not to remove the check.

I'll test a bit more and commit it tomorrow.

**Comment by slembcke** [comment]
This should be fixed now in Git.
