### ISSUE TITLE
Proposal: CCActionMove with flexible target

### ISSUE THREAD

**Issue by Ben-G** [cocos2d/cocos2d-objc#521]
I have prototyped a CCAction for one of our tutorials that allows a Node to follow a moving target until it reaches it. Would there be any interest in adding this to cocos2d? Or is it too much of a niche use case?

![actionfollowmoving](https://f.cloud.github.com/assets/1423068/1980880/f4b76a92-83ca-11e3-9557-217efa539098.gif)

If there's interest I'll polish it and create a pull-request. Once it reaches the target the action completes, that's why the penguin stays at the final position.

In the GIF you see my action combined with a rotation action. Sorry about it being sluggish.

**Comment by cocojoe** [comment]
Yeah a CCActionHomingMissle ;) Would be good to have, I'm all for developer
convenience.

On 23 January 2014 01:15, Ben-G notifications@github.com wrote:

> I have prototyped a CCAction for one of our tutorials that allows a Node
> to follow a moving target until it reaches it. Would there be any interest
> in adding this to cocos2d? Or is it too much of a niche use case?
> 
> [image: actionfollowmoving]https://f.cloud.github.com/assets/1423068/1980880/f4b76a92-83ca-11e3-9557-217efa539098.gif
> 
> If there's interest I'll polish it and create a pull-request. Once it
> reaches the target the action completes, that's why the penguin stays at
> the final position.
> 
> In the GIF you see my action combined with a rotation action. Sorry about
> it being sluggish.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/cocos2d/cocos2d-iphone/issues/521
> .

## 

Martin

**Comment by slembcke** [comment]
Closing this since the pull request for it was also closed.
