### ISSUE TITLE
Improved Rendering (Batching)

### ISSUE THREAD

**Issue by Birkemose** [cocos2d/cocos2d-objc#526]
As we probably all agree on, batching will be a major feature of 3.1, as is dramatically can speed up some applications. Especially for newcomers and user who might not be interested in digging deep into openGL.

General assumptions
Render data, should be held in the centralized render engine, and commands should be sent, to fill it with data. In that respect I think the scheme used by CCDrawNode, basically is what we are looking for. A set of medium level commands, controlling the render engine, with all vertex data, held in centralized buffers. There rarely should ex. be needs for updating texture coordinates.

Hardware Z
Hardware Z should be implemented, to improve batching. Opaque geometry should be rendered first, unsorted. Then color blended, sorted. Then additive blended, unsorted. 
I was wondering, if color blended geometry could be sorted by using indexed rendering.

Dividing geometry based on textures
To me it makes sense, to divide the render engine buffers, based on textures. For a single sprite texture, this would create pretty much the same buffers as are created in a CCSprite. For render state changes, this seems to be optional. The main state change, when rendering from a single texture, might actually be a shader change, which we in that case to some extend can circumvent.

**Comment by slembcke** [comment]
I'm a bit skeptical of the advantages of z-testing in Cocos2D. It's very uncommon to disable blending in 2D rendering engines except for large fully opaque background images for example. Normally everything is drawn at z=0 with depth testing disabled. Since the developer can use the CCNode.vertexZ value in conjunction the alpha cut shader to take advantage of the z-buffer, we can't repurpose the z-value to do anything else. Ignoring that, I'm still skeptical of the benefits. To get any performance benefits, you'd need to submit fully opaque geometry with no blending, usage of the discard() statement in a shader, and it would need to reduce a significant amount of overdraw.

Breaking a sprite up into opaque and transparent parts might help as in #527, but there would need to be a pretty low upper bound on the amount of extra geometry sent. It would also need to take the shader, CCNode.alpha value, and mipmapping into consideration to ensure that the opaque parts of the geometry never have any partially transparent pixels in them. All of this combined, it seems like a pretty hard problem to solve.

**Comment by Birkemose** [comment]
I fully agree, that just enabling hardware Z, will make no difference.

On the other hand. If we want to make better use of GPU bandwidth in 2D rendering, I can not see how we can eventually avoid it. Like we can not eventually avoid multithreading if we want to make better use of more than one CPU.

With no Z enabled, everything will be rendered pretty much as we send it to the hardware. While it always will save a little time rendering fully transparent pixels, or rendering fully opaque pixels on top, the real benefit is as what 3D does, namely the huge bandwidth gain from completely discarding pixels hidden behind opaque geometry.
3D is struggling much more with geometry bandwidth, where as 2D is struggling with shader bandwidth, so anything that could move 2D towards 3D, would imo be good.

I do not think the vertexZ will be a real problem. What the central render engine should do, is calculate the hardware Z, based on the users setup. User has no direct hardware Z access, unless in direct opengl code, so vertexZ would have to be synthesised in some way.

Apart from mipmapping, which I guess is not that common in 2D (other than for eating memory), I dont think splitting up geometry, should cause artefacts. But I agree, it will be less trivial with opacity, etc etc'

As we now have a GUI editor, I think it makes sense to look into where we could benefit from that. Splitting up a huge foreground sprite into opaque and transparent geometry, might be a step in the right direction, and SpriteBuilder could help us with that. I fully agree, that the upper bound of geometry created should be fairly low, but as it is now, you can not even use a sprite which is not rectangular, so much could be gained I think.

Finally, I will have to admit, that none of this is trivial.

**Comment by slembcke** [comment]
"I do not think the vertexZ will be a real problem. What the central render engine should do, is calculate the hardware Z, based on the users setup. user has no direct hardware Z access, unless in direct opengl code."

Definitely not true. The CCNode.vertexZ value is used when generating the 4x4 transformation matrix of a CCNode [here](https://github.com/cocos2d/cocos2d-iphone/blob/develop-v3/cocos2d/CCNode.m#L930). The use case for that is to avoid resorting geometry for things like isometric tile maps. There was a question about this [on the forums](http://www.cocos2d-iphone.org/forums/topic/cocos2d-v3-0-how-to-config-vertexz-depth-buffer-and-batch-nodes/) this morning as well. People definitely use that feature.

How would this interact with custom GL code? Would you have to ensure that the custom geometry is drawn with the correct z-value (and flat) to avoid accidental clipping?

**Comment by Birkemose** [comment]
As I see it, most are using vertexZ, because they are struggling with rendering stuff in the right order. I think a centralised render engine will fix most of that.

Am a little puzzled as to why you think this would be a major showstopper?

**Comment by lgoss007** [comment]
I think I like your ideas Birkemose, I'm all for a hardware Z and moving 2D towards 3D.

**Comment by slembcke** [comment]
Most of this has been implemented in the 3.1 branch except for the z-test part. The extra geometry it required significantly increased the CPU usage. There was another discussion thread about this somewhere with more details... Can't seem to find it now though.
