### ISSUE TITLE
Shaders

### ISSUE THREAD

**Issue by Birkemose** [cocos2d/cocos2d-objc#531]
The use of shaders should be greatly simplified. Creating a shader as it is now, is not difficult, but attaching it to a node becomes cumbersome, if any other parameters than the default ones, are to be used. Cocos2D should come with an array of "often used" shaders, which could be plugged in, in a single line of code.

I would suggest, that uniforms could be linked directly to properties.
As the three main attribues are vertices, texture coordinates and colors, I see no need to expose attributes in a render engine. If the user wants to use other kinds of attributes, he will have to create a custom render method. See #529

More than one set of attributes  
I would suggest, that attributes could be created and linked directly from the centralized render engine. This would match perfectly with a centralized render engine, where buffers were created based on texture.
If a shader then supported two or more textures, the state changes when switching texture or shader, could be absolutely minimized down to changing uniforms, thus preventing flushing the GPU cache.

Multi texture / effects shader
This leads me to the final suggestion for shaders, namely to create a multi purpose shader, which could be used to prevent costly shader changes when ex a single tinted sprite should be rendered.

**Comment by slembcke** [comment]
That was my thought on the attributes too. Use a reasonable vertex format (v3f, t2f, c4f) for all regular rendering. If you want more, then you'd need to use custom GL code.
