### ISSUE TITLE
Debug and performance improvements

### ISSUE THREAD

**Issue by Birkemose** [cocos2d/cocos2d-objc#532]
I would like to suggest more advanced debug and performance information. As it is now, pretty much only frame rate is useable. 
Two things springs to mind

A state change tracker.
Recording repetitive state changes. If state change is texture A, texture B, texture A, it would be trivial to suggest to the user, to include texture B in texture A, to reduce texture switches. Likewise, other changes could be tracked.

A fill rate estimator
With a little math, an estimate could be made, as to how many opaque and transparent pixels are renderd on the screen. This would be a special performance feature which had to be switched on, as it would take a significant overhead. On the other hand, if made right, it could be an invaluable tool for users in understanding why their rendering is slow.

**Comment by slembcke** [comment]
Andy and I have shot some ideas back and forth about debugging as well. Most of those conversations inevitably ended with "Hmm. I suppose Apple's tools already do that better than what we could add." :-\

In the case of the two ideas above, between the OpenGL ES Analyzer instrument and the "Analyze Performance" button within Xcode's GLES frame debugger I think both of those options are already covered much better than we could, though for the average user it might be hard to translate the GL API level advice it gives into Cocos level advice.

**Comment by Birkemose** [comment]
That probably is right. Maybe the time would be better spent, writing up some good performance tutorials.

**Comment by tanis2000** [comment]
+1 for tutorials on how to use the instruments and translate the results into cocos2d advices.
