### ISSUE TITLE
Update method not working during scene transitions (no more)

### ISSUE THREAD

**Issue by davilca** [cocos2d/cocos2d-objc#533]
In v2.1, update method is called during transitions, and works as expected. If you create an action in the init method of a scene, this action is played during the transition to the scene. If you make stuff in the update method during transitions, it works as expected.

In v3.0, this behavior is gone. You can try this with the template example. Please, change the transition duration of the "Intro Scene -> Hello world scene" to 5 sec., for example. The logo will not rotate until the transition is completed.

I really prefer the v2.1 "real time" transitions, where you can see animated stuff even during transitions.

**Comment by Birkemose** [comment]
In 3.0, animations during transitions can be controlled, and they are default NO. You can control if both exiting and incoming scene will be animated during transition.
Could that be your issue?

**Comment by davilca** [comment]
Problem solved, that was just the case!

CCTransition *t = [CCTransition transitionPushWithDirection:CCTransitionDirectionLeft duration:5.0f];
t.outgoingSceneAnimated = YES;
t.incomingSceneAnimated = YES;

I'm not sure if it's better to have non animated scenes by default. This can confuse people used to 2.1 default behavior. But I suppose you made this choice with a purpose.

Closing this!
