### ISSUE TITLE
Implement NSCopying, NSCoding protocols for CCNode and its subclasses

### ISSUE THREAD

**Issue by KingOfTheHuns** [cocos2d/cocos2d-objc#535]
Currently it is not easy to clone a node graph in cocos2d. It would be very useful feature to be able clone nodes on the fly. 

E.g. one use case that it could came in handy when nodes are loaded from ccbi files.
Nodes that spawned frequently could be preloaded and cloned on demand. This would avoid unnecessary disk IO each time when a node is instantiated using CCBReader. Apple nailed it in Sprite Kit  (SKNode and other nodes).
In addition it could also be used to standardize node graph serialization by SpriteBuilder.

**Comment by Ben-G** [comment]
+1 preloading + cloning would be very useful, for example for particle effects created in SpriteBuilder.

**Comment by tanis2000** [comment]
+1 for this one

**Comment by slembcke** [comment]
In past projects I've implemented copying in a category. It wasn't very hard for the subset of functionality the project required (IIRC, just nodes and sprites). It was pretty useful. NSCoding would be quite a bit harder, but probably possible with some restrictions. I'm thinking textures and scheduled stuff (methods, blocks, actions) in particular might make this problematic. It's not really clear how (or if) SpriteKit handles this sort of thing.

**Comment by KingOfTheHuns** [comment]
I guess it could be implemented in increments to cocos2d. First NSCopying protocol and next NSCoding?
Concerning NSCoding I think that the majority of use cases are just fine with the normal encoding/decoding i.e. preserve the node graph without the need for scheduled stuff, etc.

BTW: NSCopying for CCNode implies that CCPhysicsBody should have NSCopying as well.

**Comment by kirillzuev** [comment]
Any plans to implement this?

**Comment by slembcke** [comment]
We are fixing some of the underlying issues (like CCTexture) that prevent supporting NSCoding in v4. Copy/coding support may not come in 4.0, but it's definitely a priority.
