### ISSUE TITLE
CCTiledMapLayer tileAt:ccp(0,0) returning the whole layer instead of the tile at (0,0)

### ISSUE THREAD

**Issue by tanis2000** [cocos2d/cocos2d-objc#536]
There's something wrong with the tileAt method of CCTiledMapLayer.
If the parameter of pos is ccp(0,0) it returns the CCTiledMapLayer instead of the CCSprite of the tile at that position.

**Comment by tanis2000** [comment]
I've found where the error lies, but I'm unsure wether I should change the behavior of CCNode or the way the tile layers are created.

Each layer gets created as a child with the name equal to the index in the list of layers of the map. This means that the first layer is going to be called "0".

The tile at position 0,0 gets called with y*map.width+x which means that the name is "0" as well.

In CCNode, the getChildByName method checks if the node itself has that name before checking the children, thus it returns itself instead of the correct children.

My opinion is that it should only check the children because, as the name of the method implies, I'm looking for a child of that node and not the node itself. I don't know why it behaves that way. Any opinions?

**Comment by slembcke** [comment]
This causes the recursive version of the search to do nothing except iterate the node graph and breaks several of the unit tests. There was a discussion somewhere about why it made sense to have the search include the root, but I can't remember a search term to find it. @andykorth might remember.

**Comment by andykorth** [comment]
Yeah, the recursive method will need a termination condition ;) Good thing we have unit tests, eh?

The main reason the node itself was checked was to simplify the code. Also other tools like Unity have Find methods that work the same way. 

I could go either way on the behavior of "getChildByName"- I'm not surprised that someone might expect that function looks only at the children. 

However, two other things seem odd here - CCTiledMapLayer searches for tiles via string comparisons with the node's name, and there's more than one match? It also seems strange, as tanis2000 noted, that the CCTiledMapLayer itself is named "0". 

Any of those fixes is fine with me.

**Comment by tanis2000** [comment]
@andykorth actually it's not odd that the CCTiledMapLayer is named the same way. Before "name" there was the "tag" (numeric) and it used the index of the layer in the map to assign the tag.

So it was already possible that both layers and tiles had the same tag. Now they have the same name.

If we want to keep that kind of search it would be a good idea to call the layers something like layer_0 and the tiles tile_0 so that they do not mix up.. at least until someone adds another map as a child of a layer or a sprite within the layer.. then things really get messy.

**Comment by andykorth** [comment]
Ah interesting point about layers vs. tiles- didn't know that. Thanks. 

Adding more and more other nodes to the different parts of the tile map is another good point. That is probably another good reason that getting a tile at (x,y) shouldn't use string comparisons. (GetTile(x,y) out of a 100x100 tile map requires an average of 5000 string comparisons to find the tile!)

**Comment by tanis2000** [comment]
@andykorth considering that there already exists a method that reads the information of the layer and parses them (parseInternalProperties) and that when setting up the tiles we already know _layerSize.width/height and that tiles can be accessed by position like this: y*_layerSize.width+x, I'm pretty sure that it would't hurt to keep a similar array with a reference to the CCSprites that have been added to the layer so that they can still be accessed by position.

Right now I can't think of a condition where this would break something or wouldn't work.

**Comment by slembcke** [comment]
That's certainly what I would do if I was rewriting it from scratch. There is no point in doing a linear search when a simple lookup will work just fine.

I feel like maybe it was implemented the way it was to avoid duplicating data or to avoid large, sparse arrays for mostly empty layers. I'm not particularly worried about the memory usage of a tilemap though.

**Comment by tanis2000** [comment]
@slembcke I wouldn't be worried by the memory usage of tile map either. If a sparse array is a problem, we could as well resort to a linked list and a search algorithm. Either way, I need a solution as I'm using the CCSprite placed by the CCTiledLayer to build the physics body at runtime for my game :)

**Comment by slembcke** [comment]
Ok. Finally got back around to fixing this. The fix will be pushed shortly.

**Comment by tanis2000** [comment]
@slembcke thanks Scott!
