### ISSUE TITLE
Module test framework

### ISSUE THREAD

**Issue by Eternity-theIndie** [cocos2d/cocos2d-objc#540]
I haven't had time to look into your work as I'm trying to finish my project. :)

But, I wonder if you've looked into testing aspects? I guess that can be good for you at this stage, but it will also benefit all users. As much of the regression tests shall be fully automated.

As I'm still using 1.1 I can't use the module test framework of Xcode 5. Maybe you do that already?

Ok, sorry for not knowing the exact state of 3.0, but I have been missing a test framework in 1.1.

Cheers!

**Comment by slembcke** [comment]
So we have a meager selection of unit tests and a single test application with a bunch of test scenes in it for things that aren't so easy to unit test. Is that what you are asking?

**Comment by andykorth** [comment]
Both the testing frameworks are quite good right now, in my opinion- we just need more tests in them!

**Comment by Eternity-theIndie** [comment]
In 1.1 I think there is a specific test project for the _Cocos2d engine_, but the Cocos2d framework does not provide any support for testing the _application_. 

Maybe when an app designer creates a new Cocos2d v3 project it could provide the following:
- todays functionality, i.e. a framework for the application design
- (new) the full regression suite of the cocos2d v3 library. I mean, the user might want to modify the cocos2d source code, and then the user wants to rerun the regression tests from within the application project.
- (new) A framework for non-graphical unit tests of the application code. In this framework an application designer would add tests for a Judge class, that keeps track of the scoring, or for an AStar class that finds paths inside a polygon. Cocos2d shall only provide a basic platform for this framework, and maybe it's ok with the unit tests provided by Xcode (although I've not tested that).
- (new) A framework for more advanced application tests. Like you said, maybe scenes where the application designer can verify graphical aspects of the application. (I'm not sure how important this framework is though...)

Ok, I just wanted to give you some idea. Maybe you've thought of this already. So my question was not about the cocos2d regression suites, but about the application regression suites.

I guess the test benches marked with new could be included as targets within the main project.

**Comment by Eternity-theIndie** [comment]
Just want to add a suggestion.

I read in some thread that Birkemose wrote that you would setup a demo game to demo Cocos2d v3. One suggestion would be that you in that project add some samples of how the _application_ is tested with _automated_ regression tests.

That regression suite shall run all application tests as well as all automated cocos2d tests.
