### ISSUE TITLE
Question: Update to future Cocos2d versions + Project templates

### ISSUE THREAD

**Issue by Ben-G** [cocos2d/cocos2d-objc#543]
These are actually two questions, but they are both related to the Cocos2d project structure.
- Is there a plan how existing projects will be updated to future Cocos2d versions? I couldn't find a lot here while searching - maybe I missed something?
- Wouldn't it be useful to have multiple template projects? I like how the current one shows off a lot of features of Cocos2d, but If I want to start a new project it is a little annoying that I need to remove a lot of files. So at least an "empty project" template would be great

**Comment by chrene** [comment]
Agree - We should just have a Cocos2d Project and a Cocos2d-Demo project, and maybe rename the HelloWorldLayer to something more useful like MainScene or MainLayer.
