### ISSUE TITLE
Possible issue with swapping bodies for a node.

### ISSUE THREAD

**Issue by slembcke** [cocos2d/cocos2d-objc#545]
From the forums:
http://www.cocos2d-iphone.org/forums/topic/physics-body-update-doesnt-do-collision-detection/

Summary:
The developer is swapping bodies on a node and it's collisions aren't occurring when the secondary body is set.

**Comment by vdfdev** [comment]
+1 I'm having the same problem here, and it just happens with the delegate. I will try to fix it myself later, would you mind suggesting where should I start looking ? Thanks

**Comment by slembcke** [comment]
@Felizardo If your issue was specifically with the collisionType, I think I fixed that in this commit:
https://github.com/cocos2d/cocos2d-iphone/commit/7b1f3520ccdd27b98cb2715839e019704c09b1db

I was actually looking for a different bug. Two birds with one commit I guess. \o/

**Comment by vdfdev** [comment]
Yes, it fixed! Thanks a lot :)
