### ISSUE TITLE
CCOrbitCamera action in V3?

### ISSUE THREAD

**Issue by SiarheiFedartsou** [cocos2d/cocos2d-objc#550]
Hello! Now I'm thinking about migration to V3 in my project and I've found out that there is no camera actions in V3(and CCCamera at all). But we use CCOrbitCamera... What should we use instead in V3?

**Comment by slembcke** [comment]
@Birkemose Made an extension (https://github.com/cocos2d/cocos2d-swift-ext/tree/master/Extensions/CCTransformationNode) to help out with this in v3. Better support for 3D transform is already partly implemented in v4.
