### ISSUE TITLE
CCNode unit tests failing

### ISSUE THREAD

**Issue by richardgroves** [cocos2d/cocos2d-objc#555]
Some of the CCNode unit tests are failing for me - is anyone else seeing this?

In particular:

1) testGetChildByName - final test fails

2) testGetChildByNameRecursive - all three tests fail

For 1) it fails because _getChildByName_ doesn't check if self.name matches the passed in name.

For 2) they fail because on a recursive check no _name isEqualToString:_ test is ever performed - it just recurses to the bottom of the hierarchy and returns nil.

Proposed change to _getChildByName_ that makes all the tests pass:

```
-(CCNode*) getChildByName:(NSString *)name recursively:(bool)isRecursive
{
    NSAssert(name, @"CCNode#getChildByName: name is NULL");

    if ([self.name isEqualToString:name])
        return self;

    for (CCNode* node in _children) {
        if([node.name isEqualToString:name])
            return node;

        if(isRecursive){
            // Recurse:
            CCNode* n = [node getChildByName:name recursively:isRecursive];
            if(n)
                return n;
        }
    }

    // not found
    return nil;
}
```

Changes:

1) First test that _self_ isn't the name we are looking for
2) Test the child node name before recursing to any children it might have

EDIT: just seen that issue #536 discusses the problem in (1) above - and a commit tagged to that issue removed the self.name test: either the unit test needs fixing or that change reverting and the consequences for CCTiledMapLayer reassessing

**Comment by slembcke** [comment]
Due to unresolved issues in #536.

(edit: Whoops, didn't read all the way to the bottom. Seems you are already on top of things.)

**Comment by slembcke** [comment]
#536 has been fixed and will be pushed shortly. I ended up using a helper function for the recursion. It really should never had been returning the root object of the search anyway. That would have added a number of bugs as it turns out.
