### ISSUE TITLE
Cocos2d cocoapod?

### ISSUE THREAD

**Issue by Ben-G** [cocos2d/cocos2d-objc#556]
On the note of extensions for Cocos2d (#522): Is anyone interested in creating / maintaining a CocoaPod?

**Downside**
- An additional way of setting up a Cocos2d project 

**Upside**
- Provides an easy way for creating extensions & updating to newer Cocos2d version

**Comment by s1ddok** [comment]
CocoaPods are unlikely to be implemented officialy.
