### ISSUE TITLE
Call scene method on device orientation changed

### ISSUE THREAD

**Issue by Birkemose** [cocos2d/cocos2d-objc#558]
I can not really find out how to handle device rotation gracefully.
Would it be an idea to expand CCScene, so that a callback is made when rotated, and a property which could lock the scene to a certain mode.

@property (nonatomic, assign) CCDeviceOrientation allowedDeviceOrientation;
- (void)deviceOrientationDidChange:(CCDeviceOrientation)orientation;

**Comment by billhollings** [comment]
In cocos3d I deal with this by having the `UIViewController`'s `viewDidLayoutSubviews` method set the `contentSize` of the top-most `CCNode` (`CCScene`, or in my case the top-most `CCLayer`) to match the `UIView` bounds.

From there, a customized `CCScene/CCLayer` can override `setContentSize:` to lay out its components to the new orientation size.

This approach works both for full-screen `UIView`s and smaller `UIVIew`s, and leverages iOS framework for auto-setting the `UIView`'s new size.

I also support a `viewDidRotateFrom: uiOrientation to: uiOrientation` method on the topmost `CCNode`, which the `UIViewController` also invokes, but in practice it is not required.

**Comment by billhollings** [comment]
One other thing...

When it comes to OpenGL, `CC3Layer` supports an `updateViewport` method that is invoked whenever its `contentSize`, `position`, or `scale` properties are changed. As the name indicates, this method updates the OpenGL viewport to match the pixel-bounds (a `globalBoundingBoxInPixels` property) of the `CC3Layer`.

**Comment by Ben-G** [comment]
To support this nicely we need to rethink how Cocos2d code should be structured a little. UIKit basically has two approaches:
- use Constraints & Autoresizing to define a behaviour for any screen size upfront
- implement `layoutSubviews` to perform custom resizing of children whenever the view size changes

To cover the first part, we already have different position types in Cocos2d 3.0.
For custom layout updating it would be great to have a method `layoutChildren` that get's called whenever the `contentSize` of a Node changes.
Then it could become a convention to only use relative positioning and to perform all the positioning in `layoutChildren`.

When we start to use relative layouting we also get device support for tablets, etc. almost for free.

Thoughts?

**Comment by slembcke** [comment]
@andykorth Did some experiments for this (#1093) and converted the Galactic Guardians project to support dynamic rotation. We made notes about API changes to make in v4. I'll keep them in mind when working on the transform refactoring, and there were some to apply to the director/view as well.
