### ISSUE TITLE
Particles are paused after popscene

### ISSUE THREAD

**Issue by leszek-s** [cocos2d/cocos2d-objc#560]
I have 2 scenes. On the first scene (main menu) there are some flying particles. If I push another scene and then pop back to the first main menu scene then particles on the main menu should continue to fly but they are paused in position that they were previously before switching the scene.

EDIT: also when I have - (void)update:(CCTime)dt implemented then it will also not be called after popscene.

**Comment by slembcke** [comment]
There were a couple pause related scheduling bugs that were fixed in the last week or so. Would you be able to grab the latest git version and see if it was fixed?

**Comment by leszek-s** [comment]
I just checked with the latest version and the problem still exists. Particles are paused and update is not called.

**Comment by cocojoe** [comment]
This will be related to #608 I'm sure.

Are you pushing with a transition?
