### ISSUE TITLE
Won't build out of box

### ISSUE THREAD

**Issue by nheagy** [cocos2d/cocos2d-objc#565]
I just installed cocos2d 3.0rc1 via DMG, created a new empty project via the included template, and hit run.

Build failed with a lot of "Multiple methods named 'setScale:' found with mismatched result, parameter type or attributes" errors, for setScale, setRotation, and others.

I fixed it by casting self.target or _target to CCSprite. As such: http://cl.ly/image/1x2p2m173n3x

This may be related to Xcode 5.1, which is what I used to build the default project.

**Comment by slembcke** [comment]
This is apparently an issue with the Xcode betas. They introduced a method name with the same selector so ARC is complaining about an ambiguous call. It should be fixed in the current Git version, though I haven't tried out the Xcode 5 beta to verify.

**Comment by jan-happy** [comment]
It's fixed in the latest develop-v3 branch.
