### ISSUE TITLE
TextureTest causes weird behaviour

### ISSUE THREAD

**Issue by Birkemose** [cocos2d/cocos2d-objc#568]
The TextureTest seems to cause weird behaviour and crashes.
As long as the TextureTest havent been performed, the test harness seems to work as expected. After the TextureTest, other tests fails.

**Comment by andykorth** [comment]
Is it related to search paths? https://github.com/cocos2d/cocos2d-iphone/pull/542

**Comment by Birkemose** [comment]
Urk ... seems like I was missing an update. My bad.
