### ISSUE TITLE
Switching position type

### ISSUE THREAD

**Issue by Birkemose** [cocos2d/cocos2d-objc#569]
I have tried to find a way to switch position type, but was unable to. Anyone tried this?
It seems that convertToNodeSpace etc, are less useful for normalized placement, as there really is no way (that I know of) to get the coordinates into normalized space. Thus the requirement for switching position type.

**Comment by vlidholt** [comment]
These are the methods (in CCNode) that you are looking for:

``` objc
- (CGPoint) convertPositionToPoints:(CGPoint)position type:(CCPositionType)type;
- (CGPoint) convertPositionFromPoints:(CGPoint)positionInPoints type:(CCPositionType) type;

- (CGSize) convertContentSizeToPoints:(CGSize)contentSize type:(CCSizeType) type;
- (CGSize) convertContentSizeFromPoints:(CGSize)pointSize type:(CCSizeType) type;
```

I see that they have no description in the header file (and therefore isn't showing up in the api documentation).

**Comment by Birkemose** [comment]
Ahh, I missed those. Works perfect. Thanks.
