### ISSUE TITLE
Adding clipping to nodes

### ISSUE THREAD

**Issue by Birkemose** [cocos2d/cocos2d-objc#571]
I wonder if adding glScissors clipping to nodes, could be useful.

**Comment by davilca** [comment]
I'm sure it can be useful in some situations. Time ago I think I needed that for something related to the pixel perfect collision detection, but I cannot remember the details. Maybe some other users could tell us some use case examples.

**Comment by raginmari** [comment]
I think that CCClippingNode is much more versatile. I mostly use CCClippingNode with a CCDrawNode as stencil + a CCDrawNode category that draws simple shapes (e.g. rectangle). The most obvious advantage to glScissors clipping is transforms: glScissors clipping is screen-based and ignores transforms that you apply to your nodes (e.g. a dialog presenting scrollable content that "wobbles" when it appears).

As far as I understand, both the stencil test and the scissors test are performed before the fragment shader stage, so I don't know how the two compare performance-wise.

**Comment by Ben-G** [comment]
I think it is definitely useful if you have more complex hierarchies of nodes. I previously had a couple of use cases where I wanted to use one node as a _window_ that only shows a certain portion of a group of other nodes.

**Comment by slembcke** [comment]
This functionality will be in the v4 viewport node. (thanks to the input of at least half a dozen people!)
