### ISSUE TITLE
CCPhysicsNode leaks memory

### ISSUE THREAD

**Issue by jjxtra** [cocos2d/cocos2d-objc#578]
In CCPhysicsNode.h:

```
@interface CCPhysicsCollisionHandler : NSObject {
    cpCollisionHandler *_handler;
    id _delegate;
```

Should be

```
@interface CCPhysicsCollisionHandler : NSObject {
    cpCollisionHandler *_handler;
    __weak id _delegate;
```

**Comment by slembcke** [comment]
Good catch! I think that is the leak I was trying to track down the other day but having a difficult time reproducing in the Leaks instrument.

Thanks.

Fixed here: https://github.com/cocos2d/cocos2d-iphone/commit/a2e01590c770fcee54ebb8c8d90ba72a8bdaf9c4
