### ISSUE TITLE
Colliders in the 6th+ position in the collisionMask no longer collide

### ISSUE THREAD

**Issue by tanis2000** [cocos2d/cocos2d-objc#579]
@slembcke this one is for you :)

I have everything working.. I added a new kind of object like I’ve done for others and suddenly just this object isn’t colliding with anything.

My floor is set up this way:

```
            body.collisionCategories = @[@"floor"];
            body.collisionMask = @[@"player", @"enemy", @"bullet", @"shell", @"coin", @"powerup"];
```

The new object like this:

```
    self.physicsBody.collisionCategories = @[@"powerup"];
    self.physicsBody.collisionMask = @[@"floor", @"player"];
```

For some reason they don’t collide.
Then I tried switching the category of this new object and I set it to @”enemy” and this way the objects hit the floor and stay there.

Is there a limit to the array of the collisionMask or anything like that?

**Comment by slembcke** [comment]
You should be able to use up to 32 unique categories in a given CCPhysicsNode, and it should throw assertions if you go over.

It might be helpful to use the debugger to get the bitmask value for the given array from the CCPhysicsNode. I'll look into it though.

**Comment by tanis2000** [comment]
@slembcke thanks for having a look at it.. it's kind of weird. BTW I don't
know why but the values of the physics object (not the CCPhysics but those
underneath) show up wrong in the watch window in XCode. If I NSLog them, I
see the correct values, while the watches show either nil or incoherent
values. I don't know if it's a problem with the settings of my project or
what else that could be.. :-P

**Comment by slembcke** [comment]
Hmm. I've tried reproducing this a couple times now with no luck. I did find a minor bug in that the category limit assertion limit allowed you to add 33 categories instead of 32, but that would have triggered false positives not false negatives.

Are you certain that there isn't something else filtering out the collisions such as a collision delegate method returning false? If you can make a replication project for the issue that would be very helpful too.

**Comment by tanis2000** [comment]
I'll try to isolate that code into a new project, but it's going to take a while. I could give you access to a dev box with the project through TeamViewer if that could help. Just let me know.

**Comment by tanis2000** [comment]
I found out the problem. It was due to a serializer I wrote that also saved the collision masks of the level. Loading it up from file instead of generating it at run time, loaded the old collision mask that was before the 6th collision category in my game was added. 
I'm closing this as it's no longer pertinent.
