### ISSUE TITLE
Mac support

### ISSUE THREAD

**Issue by tanis2000** [cocos2d/cocos2d-objc#580]
What happened to Mac support in v3? Is it planned for a later release or is it gone completely? I was looking at porting my code to work on both iOS and OSX to help with testing and recording a trailer but I see there is no support for mouse and keyboard or anything else regarding the Mac in the current code.

**Comment by slembcke** [comment]
The Mac stuff is still all there. I run the tests on the Mac version about once a day. ;) The Mac code might not be included in the iOS templates though?

**Comment by tanis2000** [comment]
You are right that the code is there, I agree with you :)
But there's no Mac target in the XCode project of cocos2d-iphone and if I
set it as a dependency to a Mac project, XCode complains with this:

error: -fobjc-arc is not supported on platforms using the legacy runtime

Command
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang
failed with exit code 1

**Comment by tanis2000** [comment]
Further inspection tells me that the main difference between the iOS project that has been created by SpriteBuilder and a standard Mac project created through the templates is that SB adds the cocos2d-iphone as a project and that project has only the iOS target.

On the other hand, the standard template doesn't include a project but instead it includes all of the source files of cocos2d-iphone inside the newly created project.

Wouldn't it be possible to add a new target to the cocos2d-iphone project so that it can be included both in an iOS and Mac project?

**Comment by tanis2000** [comment]
Ignore my comment up there :) 
I didn't notice that the cocos2d-mac project is already in the repo. I skipped over it without even noticing.. now I went back to have a look again because I couldn't believe it wasn't there.. and well.. here it is! ;)

**Comment by tanis2000** [comment]
The project is fine now. I managed to get everything working, except for the CCBReader that's not finding the files. 

A classic 
    [CCBReader loadAsScene:@"MainScene"]

gives the error: 
    2014-02-10 23:53:01.738 platformer-mac[9250:303] -[CCFileUtils fullPathForFilename:contentScale:] : cocos2d: Warning: File not found: MainScene.ccbi
    2014-02-10 23:53:01.756 platformer-mac[9250:303] **\* Assertion failure in -[CCScene addChild:], /Users/tanis/Documents/platfromer-v3-sb/platformer.spritebuilder/Source/libs/cocos2d-iphone/cocos2d/CCNode.m:682
    2014-02-10 23:53:01.759 platformer-mac[9250:303] Argument must be non-nil

I suppose the Published-iOS folder is being ignored for some reason. How's the CCBReader supposed to be configured to use the same resources as on the iOS version?

**Comment by tanis2000** [comment]
Tonight I keep answering to myself as soon as I finish writing here.. 

I've added
    [CCBReader configureCCFileUtils];

in my AppDelegate and it did the trick.

**Comment by slembcke** [comment]
So to summarize, what exactly is it that you would like to see fixed. Is it that the SpriteBuilder templates don't include the necessary parts already in place to make a dual Mac/iOS project?

**Comment by tanis2000** [comment]
To be honest the best would be to have SpriteBuilder output a template that already has a Mac OSX target together with the iOS one. 

But CCAppDelegate needs to be tweaked as well because 

```
- (void) setupCocos2dWithOptions:(NSDictionary*)config
```

doesn't really take into consideration the Mac platform and isn't working.. and a lot of setup is done there. 

As an example, even though I can read the ccbi files, at runtime it can't find the spritesheets. 

Does it make sense?

**Comment by ghost** [comment]
It's been a bit since I tried to get a Mac project going. Now that SB is the official way to set up Cocos2d I think it needs to include an option to set up a Mac target.

I needed to set up a little project for a test case. I still have the older project templates in Xcode and it looks like the last update to the now unsupported Cocos2d installer creates a mac project that does not compile. There's is no way to get a Mac project going out of the box (unless I guess checking out from github). Setting up a SB project and adding in the Mac target manually is currently required?

**Comment by cocojoe** [comment]
This is a coming soon however in the mean time please have a look at the following tutorial:  http://jademind.com/blog/posts/porting-cocos2d-game-to-osx-using-spritebuilder/

**Comment by slembcke** [comment]
As of SB 1.3, the templates include a Mac target by default. No more fiddling required.
