### ISSUE TITLE
How do you debug Chipmunk's assertions?

### ISSUE THREAD

**Issue by tanis2000** [cocos2d/cocos2d-objc#583]
I keep getting this assertion when I have something like 3-4 bodies rotating at a high speed at the same time. I'm pretty sure that this happens when one of my "enemies" explode. When that happens, I change the following parameters on each enemy:

```
self.physicsBody.allowsRotation = YES;
[self.physicsBody setVelocity:ccp(0, 200)];
[self.physicsBody applyAngularImpulse:-300];
self.physicsBody.collisionMask = @[@"floor"];
```

Maybe it could be the setVelocity that breaks the physics computation? I can try to apply an impulse and see if it happens againg.

The assertion is the following:

```
Aborting due to Chipmunk error: Body's position is invalid.
Failed condition: v.x == v.x && v.y == v.y
Source:/Users/tanis/Documents/platfromer-v3-sb/platformer.spritebuilder/Source/libs/cocos2d-iphone/external/Chipmunk/src/cpBody.c:103
```

**Comment by slembcke** [comment]
Something is causing your position to turn into NaNs. Sometimes it can be hard to figure out where the NaN came from. There aren't currently any bugs I know of in Chipmunk that would cause them to happen without bad input. I try to catch all of the weird parameters that would lead up to this, but you can't catch them all. Is the mass or moment 0 or infinity? Are you applying infinite forces somewhere? Are you passing NaNs into CCPhysics somewhere?

**Comment by tanis2000** [comment]
I've found the problem. I was actually setting the y position of the
CCSprite to NaN. I forgot to remove a division in the formula and I had a
division by zero in a certain condition. It's weird that the runtime didn't
throw an exception because I was dividing by zero, though! :-P
