### ISSUE TITLE
Random stuttering

### ISSUE THREAD

**Issue by jjxtra** [cocos2d/cocos2d-objc#584]
Seeing random stuttering. Even in a scene with just a few sprites it is very noticeable on an iPhone 5S. Happens randomly, not easily reproducible. After putting in a bunch of logging I am noticing that the delta passed to my update spikes to 100-200 milliseconds when this stuttering happens so _something_ is lagging the main thread.

I am using CCPhysicsNode with 4-8 objects, maybe that is the culprit?

This stutter is much worse when using Apportable to target a 2013 Nexus 7. It happens almost constantly.

Profiling reveals a fairly low CPU graph with no spikes when it stutters so at the moment this is a puzzler...

**Comment by slembcke** [comment]
I'd be pretty surprised if this was a Cocos2D bug. My best guess would be that it's IO related (loading new sprites, logging, etc). Which leads me to my next point:
"After putting in a bunch of logging I am noticing that the delta passed to my update spikes to 100-200 milliseconds when this stuttering happens so something is lagging the main thread."

Was it happening before you put in a lot of logging? IO like that tends to be synchronous and buffered, so adding a lot of logging statements can really destroy your performance when the buffer is flushed. Try doing a time profile with waiting times enabled.

**Comment by jjxtra** [comment]
Testing for stutter was done in release mode with all logging disabled and no debugger attached. I noticed the spike in the update method when I added NSLog to troubleshoot in the debugger. NSLog only fired if update was >= 0.1f.

Just some more info, all my rendering is done with SpriteFrameCache and SpriteBatchNode. There are at most 8 physics object at a time, all just moving around.

**Comment by slembcke** [comment]
Since it's happening across two different devices, it does sound like it's happening within the app itself and not the OS. Other than blocking IO related issues, I'm not sure what could cause that from within your app without showing up pretty heavily on the time profile chart.

The easiest way to find those is to enable the "Record Waiting Threads" option on the time profiler instrument. You'll have to wade through all of the blocking operations to find it though including vsync and such.
![screenshot](http://files.slembcke.net/upshot/upshot_npLMubGa.png)

edit: Are you loading any textures, sounds, particle effects, etc on the fly?

**Comment by jjxtra** [comment]
I am not loading anything on the fly, it's all loaded up front.

**Comment by jjxtra** [comment]
I tried profiling as you suggested but am not sure what the results mean. I am showing about two seconds worth where there was a bad stutter. Further down (not visible) is my apps code which was 0.9% of time.
![screen shot 2014-02-11 at 8 33 03 pm](https://f.cloud.github.com/assets/1271832/2144997/679978e4-9397-11e3-9c9c-9359ff9cab83.png)

**Comment by jjxtra** [comment]
Something else that is bizarre is that the FPS counter always stays at 60 even with really bad stuttering

**Comment by jjxtra** [comment]
One of the startups at least is related to AXValidationManager. Ever heard of that? It causes bad stutter when the app starts.

![screen shot 2014-02-11 at 9 55 46 pm](https://f.cloud.github.com/assets/1271832/2145363/11f87984-93a2-11e3-8699-cdd58a50b30e.png)

**Comment by cocojoe** [comment]
@jjxtra Please post a minimal project that replicates this behaviour.  Generally in these situations it's the code not talked about that is the issue.

**Comment by jjxtra** [comment]
I've been able to alleviate most of the stutter on iOS by using a sprite sheet, although I still have the nasty stutter when the app starts due to AXValidationManager taking 250 milliseconds on the main thread. If anyone knows what this call is or how to make it go faster, please post.

**Comment by jjxtra** [comment]
Removed AdMob and stutter is gone.
