### ISSUE TITLE
CCPhysicsNode delegate return type checks fail on 64-bit device

### ISSUE THREAD

**Issue by interstateone** [cocos2d/cocos2d-objc#587]
The NSAssert at https://github.com/cocos2d/cocos2d-iphone/blob/develop-v3/cocos2d/CCPhysicsNode.m#L349 will fail on a 64-bit device because BOOL is [now typedef'd to bool, not char](http://blog.bignerdranch.com/564-bools-sharp-corners/). Either the assertion message and documentation should be changed or, even better, the assertion should accept a method return type encoding of `B` if running on a 64-bit device.

**Comment by slembcke** [comment]
Thanks. I fixed that in the 64 bit branch and added the 64 bit arch to the unit tests. Apparently I only ran them on the iPad in 32 bit mode. Whoops.

It was a mistake to compare the type encoding string to a static string. You are supposed to compare it to the output of @encode().
