### ISSUE TITLE
Dangling pointers from unretained pointers in blocks.

### ISSUE THREAD

**Issue by slembcke** [cocos2d/cocos2d-objc#591]
There are definitely more of these: #588

**Comment by slembcke** [comment]
Fixed another in https://github.com/cocos2d/cocos2d-iphone/commit/4a25f4ec01997e2be474779a29ca9aa3622d2dae

I suspect a similar bug here, but I'm not quite certain what the chunk of code does:
https://github.com/cocos2d/cocos2d-iphone/blob/develop-v3/cocos2d-ui/CCBReader/CCBReader.m#L655

**Comment by dominik-hadl** [comment]
Yes, this is the same thing I fixed in my pull request. It should be weak.. or at least what I think it should be.
