### ISSUE TITLE
Static Libraries for cocos2d, cocos2d-ui, kazmath, etc.

### ISSUE THREAD

**Issue by davilca** [cocos2d/cocos2d-objc#593]
Hello people!

I wonder why the default template doesn't distribute all cocos2d related files using static libraries. As Chipmunk library already does, I think it would be good to have the following static libraries:
- cocos2d (including cocos2d, cocos2d-ui and CCBReader)
- kazmath
- ObjectAL

This way we can change our game target build settings (enable more warnings, change compiler options, etc), without affecting the other libraries. Also, with this way I think that refactoring is faster because it will only affect the game target.

What do you think? Is there any performance penalty for using static libs? I like how Chipmunk is distributed right now.

Thanks in advance.

**Comment by jjxtra** [comment]
No performance penalty for static lib, although there are possible problems using Apportable to target Android.
