### ISSUE TITLE
Offsets from CCSpriteFrame are not handled correctly

### ISSUE THREAD

**Issue by jjxtra** [cocos2d/cocos2d-objc#600]
When using the trim, keep position option in texture packer I would expect that the offset stored in the plist would keep each frame of an animation in the correct spot. Unfortunately something is broken and the animation frames jerk around. The only solution is to do no trimming in texture packer and have each frame of animation be the same size.

**Comment by jjxtra** [comment]
Apparently just using the Trim option in texture packer seems to be working, so I'm going with that for now...

**Comment by cocojoe** [comment]
@jjxtra It would be beneficial if you could have a look on the forum first, a lot of these knee jerk type issues are already discussed.
