### ISSUE TITLE
Enhancement: Option to render particle system with CCSprite

### ISSUE THREAD

**Issue by jjxtra** [cocos2d/cocos2d-objc#607]
How difficult would it be to add an option for CCParticleSystem to render with CCSprite? What would be the performance implications of doing this? If it makes sense, I'm happy to add this feature. I've not had great luck with the particle batch node and using multiple particles on the same sprite sheet.

Perhaps a sub-class or a new CCSpriteParticleSystem?

**Comment by slembcke** [comment]
I've thought about this a little bit so far in relation to the new rendering code in 3.1. @Birkemose had some thoughts here too: https://github.com/cocos2d/cocos2d-iphone/issues/528

I'm sort of thinking along similar lines as Lars where you can implement custom particle rendering and movement behaviors by exposing the update and/or rendering loops. I'll probably be playing around with this next week.

**Comment by jjxtra** [comment]
Great! If there's anything I can help with, testing or whatever, let me know.

**Comment by slembcke** [comment]
Pinging this for #1163
