### ISSUE TITLE
After calling popScene update is no longer called

### ISSUE THREAD

**Issue by TheProphetOfRa** [cocos2d/cocos2d-objc#608]
I have two scenes, the first one triggers the second with pushScene: withTransition: and the second one falls back to the first with popScene. After popScene has been called the first scene's update method is no longer called. popScene: withTransition has also been tried neither with any success.

**Comment by slembcke** [comment]
Sounds like the scene isn't getting unpaused. Possibly related to this issue https://github.com/cocos2d/cocos2d-iphone/issues/608.

**Comment by MighteeCactus** [comment]
Facing same issue. It happens only when you use push with transition. Without transition everything is fine. 
After calling push without transition and then pop with/without transition everything works properly.
I found that if you have simple node graph i.e. animated node is a child of the scene node, than something like:

```
- (void)onEnter
{
    [super onEnter];
    [self setPaused:NO];
}
```

can resume the animation after push/pop transition, but if you have smth more complicate than that transition failed to resume popped scene...
Overriding 

```
[node onEnterTransitionDidFinish] 
```

won't help either. Btw it is called BEFORE the 'paused' property will be changed last time by the transition...

I hope this will help.

**Comment by cocojoe** [comment]
@MighteeCactus please can you provide your more complicated test project please.

**Comment by cocojoe** [comment]
After looking into this, when a scene is pushed with a transition it will become paused.  
There is nothing to resume it with a direct pop, a transition will try and set the scene's pause flag but it doesn't really help.

I'll do a pull with the fixes shortly.
