### ISSUE TITLE
swapBuffers crash

### ISSUE THREAD

**Issue by jjxtra** [cocos2d/cocos2d-objc#615]
Getting the following crash (usually only happens when backgrounding the app or sleeping the phone while in the app):

http://crashes.to/s/966ebba4ccc

**Comment by slembcke** [comment]
So iOS will terminate your app if you attempt to access GL while the app is in a background state. I wonder if it's related to that. Are you enabling background processing in your app at all? I know this was an occasional problem with old versions of Cocos2D, and I don't really know if it was ever fixed.

**Comment by jjxtra** [comment]
I don't run any background tasks, but I do have backgrounding enabled. Maybe cocos2d isn't pausing the opengl rendering fast enough when the app is backgrounded?

**Comment by jjxtra** [comment]
I got this to reproduce while debugging by pressing the home button right as an iAd full screen ad was in the process of showing on my iPhone 5s. The ad had just barely finished showing.

**Comment by cocojoe** [comment]
Have you looked at iAd best practice? Ensure all that stuff is stopped correctly just in case.

**Comment by jjxtra** [comment]
I have a fix for this, please implement in the latest code for CCDirectorIOS:

```
- (void) viewWillAppear:(BOOL)animated
{
    [super viewWillAppear:animated];

    UIApplicationState state = UIApplication.sharedApplication.applicationState;
    if (state != UIApplicationStateBackground)
    {
        [self startAnimation];
    }
}
```

**Comment by cocojoe** [comment]
@jjxtra Glad you got to the bottom of this, can you create a pull request please. Thanks

**Comment by jjxtra** [comment]
Pull request: https://github.com/cocos2d/cocos2d-iphone/pull/621

**Comment by jjxtra** [comment]
Closing and waiting for pull request to be merged in...
