### ISSUE TITLE
ZipUtils.h, ZipUtils.m and TexturePacker

### ISSUE THREAD

**Issue by davilca** [cocos2d/cocos2d-objc#620]
Hello people!

In order to use TexturePacker content protection for graphic assets, we need to replace this cocos2d files with the new ones provided by TexturePacker website:

cocos2d/Support/ZipUtils.h
cocos2d/Support/ZipUtils.m

So that we can use this function to set the protection key:

caw_setkey_part(0, 0x01a34b6f);

Maybe it would be a good idea to already support those changes in the main cocos2d branch, because those files provided by TexturePacker may get obsolete sometime.

What do you think?

**Comment by slembcke** [comment]
There is a bunch of notes about this in the image loading enhancements for 3.1. ;)

Actually... If anybody knows how to get a hold of Andreas, I've tried reaching out to him twice in the last few months and not heard anything back from him. I was hoping to work with him to make the feature a little more future proof than adding a hack to the existing .ccz file format. :-\
