### ISSUE TITLE
Keep the Newton demo

### ISSUE THREAD

**Issue by Birkemose** [cocos2d/cocos2d-objc#626]
I know we spoke about removing the newton demo, but I was wondering if it still isnt a good idea to have a minimum of "wow" effect, even for a helloworld setup.
I always thought the normal helloworlds were a little boring, and many newcomers will most like just download cocos2d, and start making a game right away.

**Comment by cocojoe** [comment]
I would say keep it as a secondary template, there is no harm in it.  Now
we are getting close to gold be nice to have the clean template as default.

Would it also be possible to have version numbers in the template
description? (or just a pita?)

On 3 March 2014 14:12, Birkemose notifications@github.com wrote:

> I know we spoke about removing the newton demo, but I was wondering if it
> still isnt a good idea to have a minimum of "wow" effect, even for a
> helloworld setup.
> I always thought the normal helloworlds were a little boring, and many
> newcomers will most like just download cocos2d, and start making a game
> right away.
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/cocos2d/cocos2d-iphone/issues/626
> .

## 

Martin

**Comment by ghost** [comment]
I think the Newton demo is a helpful starting point for those trying to learn the physics api. Can you add an OS X Newton template as well?

**Comment by Ben-G** [comment]
+1 for keeping it as an additional template

**Comment by slembcke** [comment]
Seems like there is a strong sentiment to leave it the way it is.
