### ISSUE TITLE
Transitions not working on fixed screen mode

### ISSUE THREAD

**Issue by vlidholt** [cocos2d/cocos2d-objc#627]
More info here: http://forum.spritebuilder.com/t/fixed-screen-mode-and-scene-transitions/446

My guess is that the transitions uses the view size instead of the size of the open-gl-world (which may be partially off screen). Would be nice if we could get a fix in for rc 3.

**Comment by slembcke** [comment]
Hmm. I think we are going to need to make a CCDirector.designRect property. The designSize property just isn't sufficient. Fixing the transitions to use that should be pretty straight forward.

**Comment by slembcke** [comment]
Fixed: https://github.com/cocos2d/cocos2d-iphone/commit/fe866ef91d8c6f735da75dbc1081d3722022b73f

Was pretty straightforward.

I ended up making a CCDirector.viewportRect property (designRect didn't actually make sense when compared to designSize). I made it private for now, but it seems like it would be generally useful for people using the fixed screen mode or custom projections.

**Comment by cocojoe** [comment]
This may have crept back in, doesn't work in 3.1 - see original thread.

Sample project: https://github.com/cocojoe/fixedtransitionissue.spritebuilder

**Comment by cocojoe** [comment]
Please can this be looked at as still persistent in 3.2

**Comment by Ricardo1980** [comment]
I have exactly this problem with transitions. I use the current version of Cocos2D and SpriteBuilder.

**Comment by YvesLeBorg** [comment]
darn, i should read these more often ! i ended up creating my own viewportRect harness, as well as some runtime layout helpers for working with it. Yes Scott, please make that property visible :)

fyi, my helpers (a ccnode category):

a CCNodeBorder enum 

get / setPositionInPointsW
get / setPositionInPointsV
align: border: toViewport: border: offset:
align: border: toNode: border: offset:

**Comment by slembcke** [comment]
Fixed in cc264a9f71179340dfbf738405c4788830e65673
