### ISSUE TITLE
New renderer usable at a basic level.

### ISSUE THREAD

**Issue by slembcke** [cocos2d/cocos2d-objc#631]
Remaining tasks:
- [x] CCSprite
- [x] CCSprite9Slice
- [x] CCNodeColor / CCNodeGradient
- [x] Mac compatibility
- [x] CCDrawNode
- [x] CCRenderTexture
- [x] CCProgressNode
- [x] CCMotionStreak
- [x] CCBMLabel - uses a lot of batch node hacks when changing strings
- [x] CCParticleSystem
- [x] CCTileMap not working - uses a lot of batch node hacks
- [x] CCClippingNode
- [x] CCAtlasNode / CCLabelAtlas - Usage has been replaced and the class removed.
- [x] Generate buffers / VAOs as required - Code for this is in my personal vertex-buffering2 branch.
- [x] Threaded rendering - The API is in place for CCRenderer. Actual threading implementation to follow later.
- [x] Global z-ordering.

Everybody should already have a pretty good idea about what is going on so I’ll skip to the good parts. While still very much pre-alpha, it's progressed enough that it would be useful to have people hacknig on it and sending feedback. You can get it from the `develop` branch here: https://github.com/cocos2d/cocos2d-iphone/tree/develop

Please give me feedback on anything / everything. The naming and APIs are not final. I’m still not 100% sold on anything.

First of all, some things have changed:
- The `CCBlendMode` class is replacing the `ccBlendFunc` struct. ccBlendFunc doesn’t support separate blend functions, which is going to be important for implementing an effect node with proper alpha blending. It’s already sort of an issue with CCRenderTexture, but most people seem to work around it. There are backwards compatible methods though.
- The `CCGLProgram` class has been renamed to `CCShader` and pretty much rewritten from scratch. I thought the name change was important since the name “GL program” isn’t very beginner friendly, and experienced developers will not be confused by the CCShader name. Creating and compiling shaders is quite easy now.
- Since a large number of CCNode subclasses implement the blending and texturing protocols using copy pasted code, I moved the implementations to CCNode. It doesn’t _really_ belong there, but the color and shader code was already in CCNode. It also made the renderstate code much simpler. The methods are not exposed in the headers, and are only exposed by the subclasses implementing the protocols.
- Kazmath is gone, GLKMath is in. It’s _soooo_ much nicer to work with.
## Custom, Non-GL Rendering:

I'll use the `[CCSprite draw:transform:]` method as an example. The method selector has changed. The renderer and transform is passed as arguments instead of relying on global variables to store them. `transform` is the MVP matrix. Since the transformation is being done on the CPU, it saves a couple steps to convert directly to clip coordinates instead of world coordinates. (It's still possible to get the window coordinates in a vertex shader if you need.) The following code should explain the rest.

```
-(void)draw:(CCRenderer *)renderer transform:(const GLKMatrix4 *)transform;
{
    // Exit early if the sprite is not visible.
    // This function is likely to change slightly before release.
    // Probably will take an explicit center/extents instead.
    if(!CCCheckVisbility(transform, _contentSize)) return;

    // Tell the renderer you want to draw 2 triangles from 4 vertexes.
    CCRenderBuffer buffer = [renderer enqueueTriangles:2 andVertexes:4 withState:self.renderState];

    // Buffer the vertexes.
    CCRenderBufferSetVertex(buffer, 0, CCVertexApplyTransform(_verts[0], transform));
    CCRenderBufferSetVertex(buffer, 1, CCVertexApplyTransform(_verts[1], transform));
    CCRenderBufferSetVertex(buffer, 2, CCVertexApplyTransform(_verts[2], transform));
    CCRenderBufferSetVertex(buffer, 3, CCVertexApplyTransform(_verts[3], transform));

    // Buffer the triangles using the indexes of the vertexes you just buffered.
    CCRenderBufferSetTriangle(buffer, 0, 0, 1, 2);
    CCRenderBufferSetTriangle(buffer, 1, 0, 2, 3);
}
```

Pretty simple. You don't need to know very much about GL to implement a drawing custom method like this. You only need to know how to make vertexes (position, texture coordinates, color). Culling is simple and efficient. Batching is automatic.
## Custom GL Rendering:

You can queue custom GL code to the renderer using the `[CCRenderer equeueBlock:]` and `[CCRenderer enqueueMethod:target:]` methods. CCRenderer only cares about the blending mode, texture bindings, and shader bindings. If you change any of those states, you should call `[CCRenderer invalidateState]` before exiting your block/method. Potential uses include completely custom drawing functions, or changing GL state before and after visiting a node's children. Should be pretty straightforward to use for experienced GL developers.
## Shaders:

Shaders in 2.x/3.0 were _really_ hard to use correctly even for an experienced GL dev. There were so many steps involved, and you needed to know so much about GL shaders to make it work. I wanted to make this much more streamlined. Improvements include:
- You can create/cache a shader in one line using `[CCShader shaderNamed:]`.
- A default vertex shader that just copies the attributes to varyings is provided if you only supply a fragment shader.
- Shaders include a lot more builtins now, all the standard attributes and a lot of useful uniforms. (See below)
- Shader uniforms can be set globally using `CCDirector.globalShaderUniforms` or per-node using `CCNode.shaderUniforms`.
- Setting up multi-texturing is easy as passing a CCTexture to a sampler uniform.
### Creating/caching a shader from a file.

```
node.shader = [CCShader shaderNamed:@"TrippyTriangles"];
```

This will look for a fragment shader file named TrippyTriangles.fsh (required) and a vertex shader named TrippyTriangles.vsh (optional). If you don't supply a vertex shader, the default one will be used.
### Creating a non-cached shader from a string:

```
CCShader *shader = [[CCShader alloc] initWithFragmentShaderSource:CC_GLSL(
    uniform lowp mat4 u_ColorMatrix;

    void main(void){
        gl_FragColor = u_ColorMatrix*texture2D(cc_MainTexture, cc_FragTexCoord1);
    }
)];
```

There are variations of this method that take an explicit vertex shader too. The `CC_GLSL` macro just makes an NSString out of it's contents. A reasonable way to embed GLSL source directly in your program when it's very short.
### Setting Shader Uniforms:

You can pass values into your uniforms using dictionaries. The key is the uniform's variable name, and the value should be either an NSNumber (for a float), NSValue (for vectors or matrices), or a CCTexture (for samplers). The most common uniform types are wrapped, but not all of them.

You can set uniforms for any shader globally using the `CCDirector.globalShaderUniform` mutable dictionary.

```
[CCDirector sharedDirector].globalShaderUniforms[@"u_ColorMatrix"] =
    [NSValue valueWithGLKMatrix4:colorMatrix];
```

You can override uniforms explicitly for specific nodes using the `CCNode.shaderUniforms` dictionary. The dictionary is initialized when first accessing the property. Currently nodes with a custom set of uniforms cannot be batched even if the dictionary is empty. This isn't ideal, but it's sort of hard to avoid. Unity's Renderer.material property has this problem too, and now I sort of understand why.

```
sprite3.shaderUniforms[@"u_noiseTexture"] = noiseTexture;
```
### Builtin Shader Uniforms:

```
uniform highp mat4 cc_Projection;
uniform highp mat4 cc_ProjectionInv;
uniform highp vec2 cc_ViewSize;
uniform highp vec2 cc_ViewSizeInPixels;
uniform highp vec4 cc_Time;
uniform highp vec4 cc_SinTime;
uniform highp vec4 cc_CosTime;
uniform highp vec4 cc_Random01;

uniform sampler2D cc_MainTexture;
```
### Builtin Shader Varyings:

```
varying lowp vec4 cc_FragColor;
varying highp vec2 cc_FragTexCoord1;
varying highp vec2 cc_FragTexCoord2;
```
### Builtin Vertex Shader Attributes:

```
attribute vec4 cc_Position;
attribute vec2 cc_TexCoord1;
attribute vec2 cc_TexCoord2;
attribute vec4 cc_Color;
```
### Default Vertex shader:

```
void main(){
  gl_Position = cc_Position;
  cc_FragColor = cc_Color;
  cc_FragTexCoord1 = cc_TexCoord1;
  cc_FragTexCoord2 = cc_TexCoord2;
}
```

**Comment by cocojoe** [comment]
Will digest this in the morning, great work though.

On 5 March 2014 22:43, Scott Lembcke notifications@github.com wrote:

> Everybody should already have a pretty good idea about what is going on so
> I'll skip to the good parts. While still very much pre-alpha, it's
> progressed enough that it would be useful to have people hacknig on it and
> sending feedback. You can get it from the render-queue branch here:
> https://github.com/cocos2d/cocos2d-iphone/tree/render-queue
> 
> Please give me feedback on anything / everything. The naming and APIs are
> not final. I'm still not 100% sold on anything.
> 
> First of all, some things have changed:
> - The CCBlendMode class is replacing the ccBlendFunc struct.
>   ccBlendFunc doesn't support separate blend functions, which is going to be
>   important for implementing an effect node with proper alpha blending. It's
>   already sort of an issue with CCRenderTexture, but most people seem to work
>   around it. There are backwards compatible methods though.
> - The CCGLProgram class has been renamed to CCShader and pretty much
>   rewritten from scratch. I thought the name change was important since the
>   name "GL program" isn't very beginner friendly, and experienced developers
>   will not be confused by the CCShader name. Creating and compiling shaders
>   is quite easy now.
> - Since a large number of CCNode subclasses implement the blending and
>   texturing protocols using copy pasted code, I moved the implementations to
>   CCNode. It doesn't _really_ belong there, but the color and shader
>   code was already in CCNode. It also made the renderstate code much simpler.
>   The methods are not exposed in the headers, and are only exposed by the
>   subclasses implementing the protocols.
> - Kazmath is gone, GLKMath is in. It's _soooo_ much nicer to work with.
> 
> Custom, Non-GL Rendering:
> 
> I'll use the [CCSprite draw:transform:] method as an example. The method
> selector has changed. The renderer and transform is passed as arguments
> instead of relying on global variables to store them. transform is the
> MVP matrix. Since the transformation is being done on the CPU, it saves a
> couple steps to convert directly to clip coordinates instead of world
> coordinates. (It's still possible to get the window coordinates in a vertex
> shader if you need.) The following code should explain the rest.
> 
> -(void)draw:(CCRenderer *)renderer transform:(const GLKMatrix4 *)transform;
> {
>     // Exit early if the sprite is not visible. This function is likely to change slightly before release.
>     // Probably will take an explicit center/extents instead.
>     if(!CCCheckVisbility(transform, _contentSize)) return;
> 
> ```
> // Transform the vertexes using the MVP matrix.
> CCVertex verts[] = {
>     CCVertexApplyTransform(_verts[0], transform),
>     CCVertexApplyTransform(_verts[1], transform),
>     CCVertexApplyTransform(_verts[2], transform),
>     CCVertexApplyTransform(_verts[3], transform),
> };
> 
> // Enqueue a drawing command for 2 triangles with the renderer.
> CCTriangle *triangles = [renderer enqueueTriangles:2 withState:self.renderState];
> 
> // Write the vertexes to the triangle array
> triangles[0] = (CCTriangle){verts[0], verts[1], verts[2]};
> triangles[1] = (CCTriangle){verts[0], verts[2], verts[3]};
> ```
> 
> }
> 
> Pretty simple. You don't need to know very much about GL to implement a
> drawing custom method like this. You only need to know how to make vertexes
> (position, texture coordinates, color). Culling is simple and efficient.
> Batching is automatic.
> Custom GL Rendering:
> 
> You can queue custom GL code to the renderer using the [CCRenderer
> equeueBlock:] and [CCRenderer enqueueMethod:target:] methods. CCRenderer
> only cares about the blending mode, texture bindings and shader bindings.
> If you change any of those values, you should call [CCRenderer
> invalidateState] before exiting your block/method. Potential uses include
> completely custom drawing functions, or changing GL state before and after
> visiting a node's children. Should be pretty straightforward to use for
> experienced GL developers.
> Shaders:
> 
> Shaders in 2.x/3.0 were _really_ hard to use correctly even for an
> experienced GL dev. There were so many steps involved, and you needed to
> know so much about GL shaders to make it work. I wanted to make this much
> more streamlined. Improvements include:
> - You can create/cache a shader in one line using [CCShader
>   shaderNamed:].
> - A default vertex shader that just copies the attributes to varyings
>   is provided if you only supply a fragment shader.
> - Shaders include a lot more builtins now, all the standard attributes
>   and a lot of useful uniforms. (See below)
> - Shader uniforms can be set globally using
>   CCDirector.globalShaderUniforms or per-node using CCNode.shaderUniforms
>   .
> - Setting up multi-texturing is easy as passing a CCTexture to a
>   sampler uniform.
> 
> Creating/caching a shader from a file.
> 
> node.shader = [CCShader shaderNamed:@"TrippyTriangles"];
> 
> This will look for a fragment shader file named TrippyTriangles.fsh
> (required) and a vertex shader named TrippyTriangles.vsh (optional). If you
> don't supply a vertex shader, the default one will be used.
> Creatin a uncached shader from a string:
> 
> CCShader *shader = [[CCShader alloc] initWithFragmentShaderSource:CC_GLSL(
>     uniform lowp mat4 u_ColorMatrix;
> 
> ```
> void main(void){
>     gl_FragColor = u_ColorMatrix*texture2D(cc_MainTexture, cc_FragTexCoord1);
> }
> ```
> 
> )];
> 
> There are variations of this method that take an explicit vertex shader
> too. The CC_GLSL macro just makes an NSString out of it's contents. A
> reasonable way to embed GLSL source directly in your program when it's very
> short.
> 
> You can pass values into your uniforms two ways. You can set uniforms for
> any shader globally using the CCDirector.globalShaderUniform mutable
> dictionary. The key is the uniform's variable name, and the value should be
> either an NSNumber (for a float), NSValue (for vectors or matrices), or a
> CCTexture (for samplers). The most common uniform types are wrapped, but
> not all of them.
> Setting global shader uniforms:
> 
> [CCDirector sharedDirector].globalShaderUniforms[@"u_ColorMatrix"] = [NSValue valueWithGLKMatrix4:colorMatrix];
> 
> You can override uniforms explicitly for specific nodes using the
> CCNode.shaderUniforms dictionary. Currently this is a immutable dictionary,
> but I think this is likely to change. Setting per-node uniform values
> basically guarantees that the node cannot be batched, so we might not want
> to encourage people to use this too heavily.
> 
> sprite3.shaderUniforms = @{
>     @"u_noiseTexture": noiseTexture,
> };
> 
> Builtin Shader Uniforms:
> 
> uniform highp mat4 cc_Projection;
> uniform highp mat4 cc_ProjectionInv;
> uniform highp vec2 cc_ViewSize;
> uniform highp vec2 cc_ViewSizeInPixels;
> uniform highp vec4 cc_Time;
> uniform highp vec4 cc_SinTime;
> uniform highp vec4 cc_CosTime;
> uniform highp vec4 cc_Random01;
> 
> uniform sampler2D cc_MainTexture;
> 
> Builtin Shader Varyings:
> 
> varying lowp vec4 cc_FragColor;
> varying highp vec2 cc_FragTexCoord1;
> varying highp vec2 cc_FragTexCoord2;
> 
> Builtin Vertex Shader Attributes:
> 
> attribute vec4 cc_Position;
> attribute vec2 cc_TexCoord1;
> attribute vec2 cc_TexCoord2;
> attribute vec4 cc_Color;
> 
> Default Vertex shader:
> 
> void main(){
>   gl_Position = cc_Position;
>   cc_FragColor = cc_Color;
>   cc_FragTexCoord1 = cc_TexCoord1;
>   cc_FragTexCoord2 = cc_TexCoord2;
> }
> 
> Notes: Working:
> - CCSprite
> - CCSprite9Slice
> - CCNodeColor / CCNodeGradient
> - CCMotionStreak
> 
> Mostly working:
> - CCDrawNode - haven't copied over the AA shader yet
> - CCBMLabel - uses a lot of batch node hacks when changing strings
> - CCRenderTexture - missing a lot of the original API
> - Performance - Much better than 3.0, but still a lot of good
>   optimizations to apply.
> 
> Not working
> - Passing CCColors to shader uniforms - Use GLKVector4.
> - Mac compatibility - I was hoping to have that ready by now, but that
>   hasn't happened yet.
> - CCAtlasNode / CCLabelAtlas - Already deprecated, but required by the
>   FPS label and SpriteBuilder
> - CCParticleSystem
> - CCTileMap not working - uses a lot of batch node hacks
> - CCClippingNode
> - A "CCEffectNode" - Will probably be a subclass of CCRenderTexture
>   using the autoDraw functionality
> - Threaded rendering - Still fairly confident that this will be
>   possible without a lot of pain or limitations
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/cocos2d/cocos2d-iphone/issues/631
> .

## 

Martin

**Comment by Birkemose** [comment]
Looks awesome.

**Comment by slembcke** [comment]
I guess I should publish a brief change log if people are going to be looking at this now. Did some more work this evening:
- Mac compatibility implemented.
- Made CCRenderState interning vastly more efficient. (No more dictionaries with dictionaries for keys)
- CCNode.shaderUniforms is now a mutable dictionary instead and is created on demand.

**Comment by slembcke** [comment]
CCDrawNode is fully implemented now.

**Comment by slembcke** [comment]
CCRenderTextures now work like they used to. I think we can clean up their API a bit, but that can come later.

Realized a very rookie mistake about how doing the perspective divide on the CPU doesn't really work (perspective corrected texture interpolation, etc). Changed the position attribute to a float4. That may take some explaining in the docs... or it can be wrapped up under a nice CCRenderBuffer setter maybe?

Since I expanded the vertex format even more, I decided to bit the bullet and move to indexed triangle rendering at the same time. Came up with an implementation that is pretty similar to the old one. Less memory / bandwidth usage, though it was never a bottleneck to begin with. (/me shrugs)

Speaking of vertex format, I never explained that. The current vertex format is float4 for postion, two sets of float2 texture coordinates and float 4 color. Moving away from fixed point color uses a little more memory bandwidth, but adds a lot of flexibility for custom shaders. The extra set of texture coordinates is for custom rendering and isn't currently used for anything in Cocos2D.

**Comment by jjxtra** [comment]
Is it going to use the new isMultiThreaded property of EAGLContext?

**Comment by slembcke** [comment]
Probably yes. Apple's docs are really fuzzy about what exactly it does (presumably push draw call setup to a second thread). The docs also mention that it requires hardware support, but doesn't say what hardware supports it.

I also have plans to try multi-threading at the level of the render-queue which should be usable everywhere. I need to prototype this and make a decision about it pretty soon.

**Comment by jcmeyer5** [comment]
I just installed the develop branch.... working well so far!

**Comment by jcmeyer5** [comment]
So what is the intention with CCNode?  I noticed that it got a few more protocols in 3.1, most interesting being the CCTextureProtocol (as they others are just more refactoring then they are additions).  I don't have enough knowledge to speculate, so I'll just leave the question open.

**Comment by slembcke** [comment]
As much as I hated the idea of adding even more "stuff" to CCNode, the color and shader functionality was already implemented there. In 3.0 and below, most node subclasses reimplemented the same methods over and over again in the exact same way. The compromise I made was to define the methods but not expose them except through protocols.

**Comment by slembcke** [comment]
Tilemaps and atlas node replacement were finished a few days ago. Closing this now.
