### ISSUE TITLE
V3: Use color instead of fontColor in CCLabelTTF

### ISSUE THREAD

**Issue by toreolsensan** [cocos2d/cocos2d-objc#634]
CCLabelTTF has a fontColor property which is used to control the color of the text. I imagine this dates back to before CCNode got its color property. So now you can set color on a label, but it has no effect, which is surprising. I would suggest that fontColor was made a deprecated alias of color instead. If this is acceptable I'd be happy to make the fix.

**Comment by vlidholt** [comment]
This is the correct behavior. The fontColor is the color used for drawing the texture, the color property is the color used for blending. Labels that are not using the fontColor, shadow and outline property takes a lot less memory and is faster to draw.
