### ISSUE TITLE
CCPhysicsBody eachCollisionPair always throws NSInvalidArgumentException 

### ISSUE THREAD

**Issue by sdrdis** [cocos2d/cocos2d-objc#635]
Hi,

CCPhysicsBody eachCollisionPair always throws NSInvalidArgumentException (unrecognized selector sent to instance), not depending on the number of objects colliding.

More specifically here :
https://github.com/cocos2d/cocos2d-iphone/blob/8daf9645fabb36992c0c3eaffff2f8d51ab875d7/cocos2d/CCPhysicsBody.m#L281
and here :
https://github.com/cocos2d/cocos2d-iphone/blob/8daf9645fabb36992c0c3eaffff2f8d51ab875d7/cocos2d/CCPhysicsBody.m#L285

So it happens when trying to update the pair arbiter.

Thank you :smile:

**Comment by slembcke** [comment]
Fixed in the develop-v3 branch. Got bit by automatic property synthesis and moving the property definition to a category. As usual... not enough unit tests either.

https://github.com/cocos2d/cocos2d-iphone/commit/93939049bc67b95f02c177aa681c34f7ab88df20

**Comment by sdrdis** [comment]
thank you :), keep up the good work :).
