### ISSUE TITLE
CVDisplayLink threading issues on Mac

### ISSUE THREAD

**Issue by slembcke** [cocos2d/cocos2d-objc#637]
The default setup for the Mac version is to run Cocos on a CVDisplayLink thread, but these are high priority threads that aren't really intended to have main loops ran on them. Input continues to run on the main thread which can cause terrible race conditions. This has come up on the forums a number of times in the last few years.

We should either remove the CVDisplayLink code and rely on VBL sync instead or use GCD to schedule rendering from the display thread on the main thread.

http://www.cocos2d-iphone.org/forums/topic/mouse-events-fired-on-the-wrong-thread/#post-416283

**Comment by vlidholt** [comment]
Imo, Cocos2D should always run on the main thread (from a user perspective). Running on any other thread causes lots of synchronization issues that are hard to handle. E.g. extra synchronization is required to interact with other user interface elements, such as the main menu. Running on the main thread doesn't lose any performance, so other options should be removed.

**Comment by slembcke** [comment]
This has been resolved in the v4 branch.
