### ISSUE TITLE
CCLabelTTF empty when they contain a semicolon (:) or space when compiling with arm64

### ISSUE THREAD

**Issue by BillyLavoie** [cocos2d/cocos2d-objc#645]
XCode 5.1 is out and automatically adds arm64 to the architectures. Everything seemed to run ok for my game except a few labels were missing (Ex: "Level: 2") when I would run it on a 64bit device but appeared fine on a 32bit device. After a lot of debugging I managed to pin point that if I changed the text to "Level2" it worked. "Level:2" and "Level 2" both didn't work either. I didn't test all the special characters, I know % works fine.

**Comment by jpswensen** [comment]
I am seeing the same effect. I tried to see if it was caused somewhere in the [CCLabelTTF updateTexture] call, but I can see no difference between strings with/without spaces. They both seem to have the right contentSize and such.

**Comment by robmerrell** [comment]
Just a little more info for debugging: As pointed out here: http://www.cocos2d-iphone.org/forums/topic/ios-7-1-bug-ccbutton/ adding a space at the end of the string seems to make the problem go away.

**Comment by vlidholt** [comment]
Fixed
