### ISSUE TITLE
64 bit tests

### ISSUE THREAD

**Issue by Birkemose** [cocos2d/cocos2d-objc#647]
Since 5.1 is default has 64 bit targets enabled, we might get more crash reports about this. Do you think we need to test specifically for this? and if so, any ideas on how we do that?

**Comment by slembcke** [comment]
My two main testing devices are an old iPod 4 running iOS 6 and an 64 bit iPad running iOS 7. I figure that covers at both extremes of the devices Cocos will be running on. I use test on both nearly daily.

At some point I had it print out which runtime you were using in CCConfiguration. I must have removed it at the end of the 64 bit changes I made. I added it back now. It's useful to make sure you aren't running a 32 bit executable on a 64 bit CPU.

What devices do other people test on? I guess it would be useful to try and maximize our test coverage.

**Comment by cocojoe** [comment]
iPhone 4 iOS 6, iPhone 5 iOS6, iPad 3 iOS7

On 12 March 2014 14:46, Scott Lembcke notifications@github.com wrote:

> My two main testing devices are an old iPod 4 running iOS 6 and an 64 bit
> iPad running iOS 7. I figure that covers at both extremes of the devices
> Cocos will be running on. I use test on both nearly daily.
> 
> At some point I had it print out which runtime you were using in
> CCConfiguration. I must have removed it at the end of the 64 bit changes I
> made. I added it back now. It's useful to make sure you aren't running a 32
> bit executable on a 64 bit CPU.
> 
> What devices do other people test on? I guess it would be useful to try
> and maximize our test coverage.
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/cocos2d/cocos2d-iphone/issues/647#issuecomment-37416596
> .

## 

Martin

**Comment by slembcke** [comment]
I also have an iPhone 5, iPad 2, iPad 4 and a random smattering of Android devices for testing at the office. The iPad 2 is useful occasionally since it's the slowest multicore tablet (though there is nothing in Cocos that is really threaded yet).

**Comment by slembcke** [comment]
Seems like we should be pretty well covered for testing devices. I'm going to close this.
