### ISSUE TITLE
Multiple methods "setRotation" issue. Target cannot be decided between UIRotationGestureRecognizer and CCNode.

### ISSUE THREAD

**Issue by abhineetprasad1** [cocos2d/cocos2d-objc#652]
The compiler throws ARC Semantic issue when the project in built in release mode as it cannot determine the target (UIRotationGestureRecognizer  or CCNode) for the selector call "setRotation".

relevant code: 

@interface CCAction : NSObject <NSCopying> {
    id          __unsafe_unretained _originalTarget;
    id          __unsafe_unretained _target;
    NSInteger   _tag;
}
@property (nonatomic,readonly,unsafe_unretained) id target;
@property (nonatomic,readonly,unsafe_unretained) id originalTarget;
@property (nonatomic,readwrite,assign) NSInteger tag;
in

CCAction.m
@synthesize tag = _tag, target = _target, originalTarget = _originalTarget;

-(void) startWithTarget:(id)aTarget
{
    _originalTarget = _target = aTarget;
}

-(void) startWithTarget:(id)aTarget
{
    _originalTarget = _target = aTarget;
}
Class Hierarchy

@interface CCActionFiniteTime : CCAction <NSCopying> 
@interface CCActionInterval: CCActionFiniteTime <NSCopying>
@interface CCBRotateTo : CCActionInterval <NSCopying>

CCBRotateTo.m {

   -(void) startWithTarget:(CCNode *)aTarget
   {
      [super startWithTarget:aTarget];
      startAngle_ = [self.target rotation]; // error here
      diffAngle_ = dstAngle_ - startAngle_;
   }

   -(void) update: (CCTime) t
   {
      [self.target setRotation: startAngle_ + diffAngle_ \* t]; //error here
   }

}

**Comment by slembcke** [comment]
What version? This should have been fixed as of RC3 or 4.

**Comment by abhineetprasad1** [comment]
This has been fixed in RC4. Thankyou!
