### ISSUE TITLE
Actions and Animations need to run in sync with Physics.

### ISSUE THREAD

**Issue by jtwigg** [cocos2d/cocos2d-objc#659]
CCActionManager and CCBAnimationManager need to support fixed time stepping when a physics body is attached to them.
- Needs to hook into add/remove nodes. Eg dynamically adding physics body to running animation.
- Animations velocity needs to be pushed into physics.
- Needs to work with transformations (not skew)

**Comment by jtwigg** [comment]
Process:
1) All static bodies will KVO changes of "position" and "rotation" upon their parent nodes up until the CCPhysicsNode. This will occur at onEnter and be removed onExit
2) When the KVO fires off, it will change the body.type to Kinetic. It will register itself with the CCPhysicsNode as an active Kinetic body.
3) When the body is updated, it will generate velocity & rotation data by tracking the previous vs current delta's.
4)) The CCPhysicsNode will purge any kinetic bodies who have not had their positions updated back to static bodies.

**Comment by vlidholt** [comment]
Also, any actions run on a node that has a CCPhysicsNode as an ancestor will use a fixed time step to ensure it's in synch with the physics.
