### ISSUE TITLE
CCControl setSelected adds up normal and selected state

### ISSUE THREAD

**Issue by misterHallodri** [cocos2d/cocos2d-objc#664]
[CCControl setSelected: YES] can result in not defined state CCControlStateNormal | CCControlStateSelected. Maybe splitting state and selected flag would make sense here?

**Comment by NickyWeber** [comment]
CCControl is pretty much in line with UIControl of UIKit. To quote Apple: "**UIControlStateNormal**
The normal, or default state of a control—that is, enabled but neither selected nor highlighted."

As soon as you set any of the following: selected, highlighted or disabled it is just not normal any more. So a control can be disabled, selected and highlighted at the same time in cocos2d and UIKit.
