### ISSUE TITLE
infinite loop in CCLabelBMFont if string has embedded '\n'

### ISSUE THREAD

**Issue by KerryBatts** [cocos2d/cocos2d-objc#666]
This loop (lines 556-568) never terminates, because the value of idxStr doesn't change:

NSString\* idxStr = [NSString stringWithFormat:@"%d", idx];
while(!(characterSprite = (CCSprite *)[self getChildByName:idxStr recursively:NO]))
   justSkipped++;

**Comment by KerryBatts** [comment]
This seems to work.  Could someone with much better knowledge of the logic confirm?

NSString\* idxStr = [NSString stringWithFormat:@"%d", idx];
 while(!(characterSprite = (CCSprite *)[self getChildByName:idxStr recursively:NO]))
{
     justSkipped++;
     idxStr = [NSString stringWithFormat:@"%d", idx+justSkipped];
}

**Comment by slembcke** [comment]
_Just_ found the same bug trying to finish up BMFont support for the 3.1 renderer. It looks like the bug was introduced by the CCNode.tag -> name change. I'll have to backport the fix when I'm done with it.

**Comment by slembcke** [comment]
Fixed by reverting to an earlier version of the code and fixing that.
