### ISSUE TITLE
CCEffect

### ISSUE THREAD

**Issue by vlidholt** [cocos2d/cocos2d-objc#670]
We've been talking about adding an effects node and effects to Cocos2D, this would work similar to how effects work in SK, but use shaders. I propose something along these lines.

Effects can be added to either CCSprite:s (or sub-classes) or a new CCEffectNode by setting an _effect_ property. The effects node would draw it's children into the area specified by the content size of the node. It would clip any objects drawn outside of the area.

_CCEffect_ is the base class for all effects, an effect is a partial shader. One or more effects can be stacked together to build a complete shader. To combine several effects we have an extra effect class, _CCEffectSequence_ (this would work similar to the action sequences).

Each effect can take external parameters (either passed to the effect in it's constructor, as properties or read from the nodes/environment), these are passed down to the actual shader.

Example effects usage:

```
mySprite.effect = [CCEffectMotionBlur effectWithReferenceNode:myPhysicsNode strength: 1.0];

anotherSprite.effect = [CCEffectSequence effects:
    [CCEffectHueSaturation effectWithHue: 0.0 saturation: -100.0 lightness: 0],
    [CCEffectBlur effectWithRadius: 5.0],
    nil];
```

The CCEffect provides a good framework for building the actual parts for the shaders and the sequence can stack them together. There could be read only properties on the effect that returns the actual shader.

This needs more thinking about the internals of the effects, error handling, caching, etc, but can serve as a starting point for the discussion.

**Comment by nheagy** [comment]
I think this is a great idea.

I just finished implementing a two-pass Gaussian blur so a lot of implementation ideas are fresh I my mind, particularly for blurs. Would probably be nice to have a framework for multipass effects. Also some method for reusing FBOs behind-the-scenes.

Also, I'm guessing SK leverages core image for many effects. It's possible we could do the same with GPUImage, since it is shader-based and written in ObjC (tho it would need a ton of changes, and possibly an outright fork).

**Comment by slembcke** [comment]
A couple of notes about potential issues from the other day:
- Destination alpha of a render texture rarely has the correct alpha values. (I can help with this some through the default blending modes for sprites.) SpriteBuilder's blending mode support will need to be updated as well since it can't do separate blending functions.
- I don't think we can trivially give render textures premultiplied alpha, a requirement unless we limit effect nodes to nearest neighbor filtering. We might have to perform a premultiplication pass.
- As @nheagy also pointed out, not all effects can be implemented efficiently in a single pass. (separable blurs, dynamic displacement maps, etc) This isn't much of a problem for a brand new class like CCEffectNode, but can't easily be applied to a sprite as a simple single pass shader effect.
- If we are building on CCRenderTexture, is it a problem that they won't scale/rotate nicely without filtering artifacts?

**Comment by cocojoe** [comment]
If effects are going to have their own action manager it would be a good
time to look at performance of running actions so this could either be back
ported in the CCActionManager or ideally this effect action manager could
form the new core for all existing actions as well.

Sounds good though.

On 2 April 2014 15:49, Scott Lembcke notifications@github.com wrote:

> A couple of notes about potential issues from the other day:
> - Destination alpha of a render texture rarely has the correct alpha
>   values. (I can help with this some through the default blending modes for
>   sprites.) SpriteBuilder's blending mode support will need to be updated as
>   well since it can't do separate blending functions.
> - I don't think we can trivially give render textures premultiplied
>   alpha, a requirement unless we limit effect nodes to nearest neighbor
>   filtering. We might have to perform a premultiplication pass.
> - As @nheagy https://github.com/nheagy also pointed out, not all
>   effects can be implemented efficiently in a single pass. (separable blurs,
>   dynamic displacement maps, etc) This isn't much of a problem for a brand
>   new class like CCEffectNode, but can't easily be applied to a sprite as a
>   simple single pass shader effect.
> - If we are building on CCRenderTexture, is it a problem that they
>   won't scale/rotate nicely without filtering artifacts?
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/cocos2d/cocos2d-iphone/issues/670#issuecomment-39339351
> .

## 

Martin

**Comment by slembcke** [comment]
I suppose actions could be used to tween effect values, but there isn't really a reason to make something new to do it.

I think what Viktor meant by effect sequences is that you could apply a blur, then a distortion, then convert to grayscale. That was the idea that was thrown around the other day anyway.

**Comment by nheagy** [comment]
@slembcke I'm curious about #4… why is it that they won't scale or rotate nicely? I think this is a problem but I don't understand the technical reason why.

Edit: ok, I looked at the source, seems that there's no multisampling FBO. I'm not an expert, so I'm not certain why this hasn't been done as it would be great for render textures in general?

**Comment by slembcke** [comment]
The children of the effect node would be rendered into the CCRenderTexture instead of rendered in screen space. If you set the render texture scale to 2.0 then children will get bigger as expected, but also blurry. Any other transformation that causes a perfect 1:1 mismatch in the texture to screen pixel alignment is also going to cause artifacts.

**Comment by vlidholt** [comment]
Moving this one to 3.2.

**Comment by nheagy** [comment]
I've been thinking about this lately, wondering about API. Given the scaling implications and such @slembcke mentioned, the API could be designed to more reflect that.

Instead of:

```
mySprite.effect = [CCEffectMotionBlur effectWithReferenceNode:myPhysicsNode strength: 1.0];
```

We could do something like the recently retired batch node:

```
CCEffectSprite *myEffect = [CCEffectSprite effectSpriteWithSize:CGSizeMake(100,100)];
myEffect.effect = [CCEffectMotionBlur effectWithReferenceNode:myPhysicsNode strength: 1.0];
[myEffect addChild:mySprite];
```

This may not be a beautiful as SpriteKit's, but I think its behavior would be easier to predict. Thoughts? Has work begun on adding effects?

**Comment by vlidholt** [comment]
Done some initial testing on the new CCEffects. Things that needs to be fixed:

### CCEffectNode
- [x] Doesn't respect the anchorPoint property.
- [x] Cannot be resized once init:ed. Should have lazy initialization, so that the effects node can be created with `[[CCEffectNode alloc] init]` and then setting the content size.
- [x]  Must support the different size types for content size.
- [x] Effect should be an `effect` property instead of the `addEffect:` method. (Currently there is no way of changing the added effects.) See original spec above for API.

### CCEffect
- [x] The effects need constructors in addition to to init methods.
- [x] Constructors and methods that are only interesting in sub classes should be hidden in a CCEffect_Subclass.h file (see for example CCControl). Methods include initWithFragmentFunc/Uniforms etc.

### Individual effects
- [x] Pixellate, scale is unclear, instead should define pixel size in points.
- [x] Pixellate, pixels are not square.
- [x] Color & ColorPulse, assuming these are for testing and should be removed?
- [x] Brightness / Contrast. Brightness has a default value of 0 while Contrast has a default value of 1. These should be the same (no change = 0).
- [x] EffectGlow, blur strength is unclear. Should be defined in points.
- [x] EffectGlow, is it possible to define another parameter with the strength of the effect (not the blur radius)? This would be very useful to tweak the visuals of this effect.

**Comment by osinoleg** [comment]
Thanks Viktor, great feedback.

**Comment by vlidholt** [comment]
Prioritized effects for the 3.2 release:
- [x] Hue
- [x] Saturation
- [x] Brightness
- [x] Contrast
- [x] Pixellate
- [ ] Blur
- [ ] Bloom
  - [x] Property for threshold
  - [x] Property for  intensity
  - [ ] Option for better quality blur (needed for larger radius)
- [x] Refraction
- [x] Reflection
- [ ] Glow (like in photoshop)
- [ ] Drop shadow (like in photoshop)

If time permits, less important effects:
- [x] Lighting
- [ ] Grain/noise
- [ ] Wiggle
- [x] Color channel offset

**Comment by nheagy** [comment]
I don't see blur, is it planned?

**Comment by vlidholt** [comment]
Oops missed blur, it should definitely be in there

**Comment by richardgroves** [comment]
Does 'Wiggle' include the replacement of the dropped 'CCActionGrid3D' and
friends?

http://forum.cocos2d-swift.org/t/what-happened-to-ccactiongrid3d-in-v3-0/12959/1
implies it would make the 3.1.1

On Thu, Jun 26, 2014 at 11:20 PM, Viktor Lidholt notifications@github.com
wrote:

> Oops missed blur, it should definitely be in there
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/cocos2d/cocos2d-iphone/issues/670#issuecomment-47287690
> .

## 

Richard Groves
Technical Director | NoodlFroot

M: +44 (0)7962 054 163

www.noodlfroot.com

NoodlFroot Limited is a company registered in England and Wales with
registration number 07245048.
Registered office: 145-157 St John Street, London, EC1V 4PY.

**Comment by vlidholt** [comment]
Wiggle will be somewhat different from that (see https://www.youtube.com/watch?v=NRhQ3XmHUF4 for reference). But we will make replacements (maybe not exact clones) for the dropped CCActionGrid3D. The new CCEffects will allow us to make very cool new transitions too.

**Comment by richardgroves** [comment]
Great - glad to hear the new CCEffect system will provide a good base for a
wide range of effects.

I'm actually after a CCTransitionPageTurn  replacement that I can then get
to work on individual nodes, so might have to dig in and get my hands dirty
myself I guess.

On Fri, Jun 27, 2014 at 7:58 PM, Viktor Lidholt notifications@github.com
wrote:

> Wiggle will be somewhat different from that (see
> https://www.youtube.com/watch?v=NRhQ3XmHUF4 for reference). But we will
> make replacements (maybe not exact clones) for the dropped CCActionGrid3D.
> The new CCEffects will allow us to make very cool new transitions too.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/cocos2d/cocos2d-iphone/issues/670#issuecomment-47387603
> .

## 

Richard Groves
Technical Director | NoodlFroot

M: +44 (0)7962 054 163

www.noodlfroot.com

NoodlFroot Limited is a company registered in England and Wales with
registration number 07245048.
Registered office: 145-157 St John Street, London, EC1V 4PY.

**Comment by vlidholt** [comment]
Review of latest version:
- [x] Remove debug ifdefs. This should no longer be included in the ccConfig.h
- [x] Declare all finished effects in cocos2d.h
- [x] API docs are needed

### CCEffectNode
- [x] Not working with relative content size, e.g. content size (1,1) and contentSizeType set to CCSizeTypeNormalized

### CCEffectGlass
- [x] Add a constructor without a normal map to make it clear it's ok to pass NULL (applies to refraction & reflection too)

### CCEffectGaussianBlur
- [x] Rename to CCEffectBlur
- [x] Rename effectWithPixelBlurRadius to effectWithBlurRadius (as it's actually in points not pixels)

### CCEffectBloom
- [x] Cannot get it to work in any satisfying way, parameters doesn't make sense too me, e.g. intensity set to 0 doesn't leave the image unaffected. It's possibly that this is a documentation issue. Also, cannot get white areas to expand out, only areas which has a color.

**Comment by thayerandrews** [comment]
My latest pull request includes fixes for the debug ifdefs and the imports of completed effects in cocos2d.h. I'm continuing work on the other items now.

**Comment by thayerandrews** [comment]
Just created a new pull request with API docs for all CCEffect classes.

**Comment by thayerandrews** [comment]
Based on a conversation just now with Viktor I'm adding the following:

### CCEffectGlass / CCEffectReflection
- [x] Add reflection strength slider to control overall contribution of the reflection environment independent of the fresnel terms.
- [x] Add reflection strength slider to control overall contribution of the reflection environment independent of the fresnel terms.

**Comment by thayerandrews** [comment]
### CCEffects and project templates
- [x] Add all CCEffects headers to the Xcode project templates.

**Update:**
The Xcode project templates have been removed in 3.2 so this is a non-issue now.

**Comment by nheagy** [comment]
Looks great. I hope to dive in and check out the implementation within a week or two. I'm especially interested to see how the blur turned out, since I just wrote one for Fire Words.

**Comment by thayerandrews** [comment]
### CCEffectStack
- [x] Add constructor methods.

**Comment by nheagy** [comment]
So it's been months since I said I'd review the code, but I finally got around to it this weekend. Overall I'm impressed, this seems like a very solid implementation. I have a few questions, if you have time to answer:
1. Do the FBOs used for effect passed have multisampling working? When I wrote my gaussian blur, which was also based on GPUImage's, I was getting artifacts with the subsampling optimization without using glResolveMultisampleFramebufferAPPLE(). I wasn't able to find this anywhere for the FBOs for the effects, and I suspect this means the blur could be faster for larger radii.
2. A further optimization for blur would be to downsample the source texture when the blur is significantly large. Accommodating this might be a big change, tho it can really help for big full-screen blurs.

Anyway, nice work :)

**Comment by thayerandrews** [comment]
Thank you for the feedback. Yeah, we're pretty excited with how CCEffects is turning out.

Regarding multisampling, we are not currently enabling it for the effect pass FBOs or in CCRenderTexture (from which CCEffectNode is derived). We have seen some visual artifacts in the blur though so I'm interested to investigate this further.

Downsampling the blur source textures might not actually be too bad so this is also an interesting change to investigate. We could possibly add a check against the blur radius and the source texture size and, if both are large enough, introduce an intermediate pass that downsamples the source prior to the blur passes. Of course the intermediate pass might kill any performance win we get from the downsample.

**Comment by osinoleg** [comment]
Wow, downsampling the blur is a great idea! Thayer is right in pointing out
that the intermediate pass might nullify the performance gain, worth trying
out. Will bring this up in the cocos2d meeting, maybe I can take a closer
look at this.

Thanks guys :)

**Comment by mefilt** [comment]
How use effects on one drawnode?

**Comment by thayerandrews** [comment]
CCEffects can only be applied to CCSprite and CCEffectNode so they cannot be used directly with CCDrawNode. However, you can create a CCEffectNode, add your CCDrawNode to it, and apply any effects to the effect node.
