### ISSUE TITLE
CCLabelTTF with custom font disappears on 64-bit device

### ISSUE THREAD

**Issue by DSalko** [cocos2d/cocos2d-objc#672]
It's weird, but only on 64bit device (iphone 5S) label completely disappears. We're using this font https://www.google.com/fonts/specimen/Electrolize if it matters. And it works fine on other devices. Has anyone else experienced similar issue?

**Comment by slembcke** [comment]
Possibly related to https://github.com/cocos2d/cocos2d-iphone/issues/645

**Comment by DSalko** [comment]
Thank you, I'll check.

**Comment by blairwang** [comment]
cocos2dx version 2.2.6 for 64bit , CCLabelTTF invisible with some words! But can be visible when other words or other fontSize. Beg for the way to solve it !!! 
The source code is so different that I can't do "Switches floats to CGFloat" operation, can you help me?

**Comment by komrat1988** [comment]
try this https://github.com/cocos2d/cocos2d-x/commit/dc15993c391c3919e0aafaf19845ad9ee8905935
