### ISSUE TITLE
CCButton can be tapped while scene animates

### ISSUE THREAD

**Issue by jjxtra** [cocos2d/cocos2d-objc#683]
If you double tap a CCButton that pushes a scene, you can get two tap callbacks, even after the scene starts animating away. CCButton should ignore all touches if the scene it is in is animating in or out. This problem likely stems from a bug in CCControl, the fix should probably be made their, perhaps in triggerAction.

**Comment by richardgroves** [comment]
I'd suggest that the client code should set the enabled property of the
CCButton to NO when it has done something as major as trigger a scene
transition. To arbitrarily disable some nodes during a transition is a bit
aggressive.

On Sun, Apr 6, 2014 at 10:41 PM, Jeff Johnson notifications@github.comwrote:

> If you double tap a CCButton that pushes a scene, you can get two tap
> callbacks, even after the scene starts animating away. CCButton should
> ignore all touches if the scene it is in is animating in or out.
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/cocos2d/cocos2d-iphone/issues/683
> .

## 

Richard Groves
Technical Director | NoodlFroot

M: +44 (0)7962 054 163

www.noodlfroot.com

NoodlFroot Limited is a company registered in England and Wales with
registration number 07245048.
Registered office: 145-157 St John Street, London, EC1V 4PY.

**Comment by slembcke** [comment]
Yeah, would have to think about this some. UIKit has you do similar to what @richardgroves is suggesting. It makes it a little more complicated, but more flexible (I guess?).

I'm not 100% certain how you can still get touches after a transition starts to be honest. I would have expected the nodes to be removed from the responder manager by that point, though I'm not very familiar with that code. The sequence is probably more complicated than I think it is.

**Comment by Birkemose** [comment]
This has always been a common cause for problems. 
You can not get touches after the transition has started. The problem is because the new scene takes time to create, and in that time the first scene is still alive.

I guess the director could default pause the outgoing scene immediately upon call, but I am not 100% certain if that is too much automation.

Den 07 Apr 2014 kl. 15:27 skrev Scott Lembcke notifications@github.com:

**Comment by adamfraser** [comment]
I've run into this a couple of times as well and ended up using an approach similar to @richardgroves

**Comment by slembcke** [comment]
I think this was fixed, but it would need to be double checked.
