### ISSUE TITLE
CCTiledMap doesn't parse new CCTiledMapLayers after encountering one with zero tiles

### ISSUE THREAD

**Issue by smklinger** [cocos2d/cocos2d-objc#687]
in CCTiledMap's private "parseLayer" function after getting CCTiledMapTilesetInfo, it should just return nil if tileset is nil.

**Comment by smklinger** [comment]
Should empty layers be ignored? or added? I'm not sure what the desired functionality is.

**Comment by EarthAlchemist** [comment]
In the code, CCTileMap.m line 87, the empty layer will make the contentsize.width and height to +INF, and this is error...

**Comment by smklinger** [comment]
I've submitted pull request #694
