### ISSUE TITLE
Possible passing uninitialised data, CCNode.

### ISSUE THREAD

**Issue by iSevenDays** [cocos2d/cocos2d-objc#689]
https://github.com/cocos2d/cocos2d-iphone/blob/v3.0/cocos2d/CCNode.m : 225

Assuming body is non-nil, "CGPoint position = self.position;" and then this is executed "self.position = position;"

Is there no problem?

**Comment by kalo** [comment]
a CCNode's initial position is CGPointZero so this should be alright.

the position is reset after a physical body rotation if (or in case) the body's center of gravity is different than the node's anchor point.

**Comment by iSevenDays** [comment]
Thanks. Sorry for disturbing you.
