### ISSUE TITLE
Potential leak of an object in CCColor.m

### ISSUE THREAD

**Issue by iSevenDays** [cocos2d/cocos2d-objc#690]
line 173
- (CGColorRef) CGColor
  {
  CGFloat components[4] = {(CGFloat)_r, (CGFloat)_g, (CGFloat)_b, (CGFloat)_a};
  return CGColorCreate(CGColorSpaceCreateDeviceRGB(), components);
  }

CGColorSpaceCreateDeviceRGB() returns a Core Foundation object with +1 retain count and this object is not referenced later and has a retain count of +1.

**Comment by kalo** [comment]
this is more than likely a leak.

the CGColorSpace should either be saved to a reference and released after the creation of CGColor or bridge released.

**Comment by iSevenDays** [comment]
I sent a pull request.
https://github.com/cocos2d/cocos2d-iphone/pull/691
