### ISSUE TITLE
[TMX ERROR] an empty layer, all display blank 

### ISSUE THREAD

**Issue by EarthAlchemist** [cocos2d/cocos2d-objc#693]
When make a tmx file by tiled map editor, I create an empty layer to contain a player ccSprite in runtime, but when I add the tmx to scence, all display blank...

when I fill some tile to the empty layer, the tmx is display in the scence.

In the code, CCTileMap.m line 87, the empty layer will make the contentsize.width and height to +INF, and this is error...

**Comment by smklinger** [comment]
I traced the problem to CCTileMapLayer.m line 120. If the layer doesn't have a tileset, pixelsToPoints is 1/0 = INF which causes the layer's contentSize to be INF, INF

I've submitted pull request #694
