### ISSUE TITLE
setSprite: in CCProgressNode doesn't work!

### ISSUE THREAD

**Issue by FuriouZz** [cocos2d/cocos2d-objc#698]
When I set a new sprite, the CCProgressNode sprite display nothing.

My solution is to add `[self updateProgress];` at the end of the second condition of the `setSprite:` like in `setType:`.

**Comment by kalo** [comment]
i just made a pull for this.

`setReverseDirection:` also created the same problem.

**Comment by FuriouZz** [comment]
Thanks a lot for your reaction. I'm waiting your pull.

**Comment by slembcke** [comment]
@kalo's pull request was merged (finally). Thanks everyone!
