### ISSUE TITLE
CCEffects (list of desirable effects)

### ISSUE THREAD

**Issue by osinoleg** [cocos2d/cocos2d-objc#708]
List of effects we want to add to our CCEffect library
- Motion Blur 
- Glow/Bloom - [screenshot](http://i39.tinypic.com/23hku4m.png)
- Pixelate
- Toon Shade
- Color Pulse
- Outline
- Color
- Spiral
- Lighting - [screenshot](http://cdn.highwinds.steamstatic.com/steam/apps/214560/ss_152fb144da101f023f0440b2755b0a9f9e3847ce.1920x1080.jpg?t=1379624521)

Note: screen shots coming soon

**Comment by vlidholt** [comment]
A few more that I'd like to see:

_Color Controls like Photoshop_
A possibility would be to split these up in more filters if that is faster.
- Hue/saturation/lightness
- Brightness/contrast

_Blur_
Lots of different blurs here (pick the two best ones for basic blur?): https://github.com/BradLarson/GPUImage
- Gaussian blur
- Quick (box) blur
- Tilt shift blur
- Zoom blur

_Lighting_
- SpriteLamp style lighting (see Lars' example)

_Transforms_
- 3D Transform (vertex shader)

_Combined Effects for transisitions_
- Page flip (vertex + fragment shader?)
- Other fancy transitions (e.g. see Keynote for ideas)
