### ISSUE TITLE
Scheduler immediately calls scheduled method

### ISSUE THREAD

**Issue by Birkemose** [cocos2d/cocos2d-objc#722]
The code
[self schedule:@selector(timer:) interval:5];
will immediately call timer: and then recall it 5 seconds later:

In V2, timer: was called the first time after 5 seconds, which I think is the most logic behaviour

**Comment by slembcke** [comment]
Easy fix. Knew right where to look for that one.
https://github.com/cocos2d/cocos2d-iphone/commit/e9099b56e8fbc499fe635f4e01a13780a4b1a146
