### ISSUE TITLE
Improved particle systems

### ISSUE THREAD

**Issue by vlidholt** [cocos2d/cocos2d-objc#729]
The particle systems in Cocos2D is starting to feel a little bit dated. We should add more features or rewrite them. Some suggestions:
- Instead of the positioning type add a targetNode property, similar to how SKEmitterNode does it. This could probably be made to be backwards compatible with the old positioning types which should be deprecated. This approach is much clearer and flexible than what we currently have.
- Make it possible to adjust the angle of a single particle depending on the direction it is moving. This angle should be added to the angle defined by start/end/var spin properties.
- Allow a gradient of colors, rather than just a start/end color. Each color should also have support for variations.
- Allow keyframes for the size property, not just a start/end value, the keyframes would each have a variance. Possibly this could be added to every sort of property (but size is the most important one).
- Make it possible to override the method for updating a particle (or possibly use a pointer to a c function if that is faster).
- Being able to use multiple sprite frames from the same sprite sheet.
- Support "fast forwarding" or particles, if the user needs them to start with a fixed set of particles already on the screen.

**Comment by vlidholt** [comment]
Also:
- Particles that can be affected / bouncing off physics bodies. Ideally, they should also be able to change characteristics when bouncing.

**Comment by vlidholt** [comment]
More:
- Support for overall opacity changes would make it possible to fade in and out particle systems.

**Comment by hakonber** [comment]
Sounds like really good suggestions! I know we would greatly appreciate the following features in our project:

> - Instead of the positioning type add a targetNode property, similar to how SKEmitterNode does it. 
> - Make it possible to adjust the angle of a single particle depending on the direction it is moving.

**Comment by slembcke** [comment]
Pinging this issue for #1163
