### ISSUE TITLE
_displayColor not updated in [CCNodeColor setColor]

### ISSUE THREAD

**Issue by jpswensen** [cocos2d/cocos2d-objc#734]
I could be wrong, but I think that in the [CCNodeColor setColor] that the _displayColor should be set as in the constructor as

-(void) setColor:(CCColor*)color
{
    [super setColor:color];
    _displayColor = _color = color.ccColor4f;
    [self updateColor];
}

I did a quick test and can confirm that this fixed my problem of not being able to set the CCNodeColor after it had been created. Is there a more correct way of setting the color of the CCNodeColor, or was this really a bug?

**Comment by jpswensen** [comment]
Sorry, I was looking at my code from the 3.0 branch. I see that in the develop branch that this is no longer an issue, so you can delete this issue. I apologize for the clutter.

**Comment by slembcke** [comment]
It was probably fixed in 3.1 (develop) as a side effect of rewriting some of the rendering code. Still sounds like something we should fix in 3.0.1 so it gets into a stable release sooner. Sounds like it should be an easy fix.

**Comment by slembcke** [comment]
Uncertain if this ever got fixed.
