### ISSUE TITLE
CCPhysicsBody: sleeping property can not be changed

### ISSUE THREAD

**Issue by LearnCocos2D** [cocos2d/cocos2d-objc#738]
It is not possible to force a CCPhysicsBody to sleep. Not even after zeroing velocity and angularVelocity. The body in question is not colliding with anything, and is dynamic. 

Based on my Box2D experience and the property not being readonly I expected sleeping to be modifiable.

This code has no effect on the `sleeping` property:

```
        node.physicsBody.sleeping = YES;
        NSLog(@"sleeping: %d (node: %@, body: %@)", node.physicsBody.sleeping, node, node.physicsBody);
```

Log output:

```
sleeping: 0 (node: <CCNodeColor = 0x10a611840 | Name = >, body: <CCPhysicsBody: 0x10a611ec0>)
```

Note: the sleeping property auto-synthesizes a `_sleeping` ivar that is never used in the implementation, the overridden property getter always returns the body's sleeping flag.

**Comment by LearnCocos2D** [comment]
Addendum: I've since tried this again, with rope/chain bodies consisting of multiple bodies connected with joints. If I set them all to sleeping the sleeping flag is set to YES but the body is moving nevertheless.

**Comment by slembcke** [comment]
Fixed + tests here:
https://github.com/cocos2d/cocos2d-swift/commit/985467a6ec62547419b5fe4c8f317f777ba00044
