### ISSUE TITLE
Tilemap -hd issues.

### ISSUE THREAD

**Issue by slembcke** [cocos2d/cocos2d-objc#744]
More information here:
http://forum.cocos2d-iphone.org/t/v3-1-beta-retina-tilemap-doesnt-appear-correctly/13304/2

**Comment by aryelevin** [comment]
fix by changing line number 394 to:
float scale = tex.contentScale;
instead:
float scale = 1.0/tex.contentScale;
and line number 404 to:
int tilesPerSheetRow = (_tileset.imageSize.width - tilesetMargin_2 + tilesetSpacing) / (_tileset.tileSize.width_scale + _tileset.spacing);
instead:
int tilesPerSheetRow = (_tileset.imageSize.width - tilesetMargin*2 + tilesetSpacing) / (_tileset.tileSize.width + _tileset.spacing);

works fine on iphone retina and ipad and ipad retina...
thanks.

**Comment by slembcke** [comment]
Got a good test case set up this afternoon. I'm also going to make the TMX files resolution aware. Then one wouldn't even need separate tilemap files if the tileset texture is properly rescalable.

**Comment by chadwyk** [comment]
@aryelevin's fix didn't seem to work in my test cases.  It scaled them back down to the correct size, however the tile placements were wrong, and the wrong tiles were being shown.

**Comment by slembcke** [comment]
Oops. Looks like I forgot to push my changes on Thursday night from my home computer. It should be fixed in the latest 'develop' branch.

I did implement the TMX scale issue as well so you don't need a separate -hd tilemap as long as it's a trivially resized version of the non-hd tilemap. (2x the width/height, double the margin and spacing, etc)
