### ISSUE TITLE
OpenGL error in 3.1

### ISSUE THREAD

**Issue by hakonber** [cocos2d/cocos2d-objc#748]
See attached screenshot from an OpenGL ES frame capture in Xcode (from Cocos2D project template). Apparently Cocos2D enables depth testing even when the app isn't using a depth buffer. It doesn't appear to have any consequences, but it would be nice to clean it up.
![screen shot 2014-05-10 at 19 37 56](https://cloud.githubusercontent.com/assets/873092/2936670/305c5d34-d86a-11e3-96e5-6793eb58ea15.png)

**Comment by slembcke** [comment]
Whoops. Left over hard coded settings from some testing. Nice catch.
