### ISSUE TITLE
Touches outside the CCTableview shouldn't be passed

### ISSUE THREAD

**Issue by mattcn** [cocos2d/cocos2d-objc#760]
See the screenshot attached, the red line area indicates the background view of the cctableview. The outside view can be hidden via CCClippingNode, however, the touch event still works when it is hidden. any ideas how to fix it?
![cctableview](https://cloud.githubusercontent.com/assets/772040/3004930/a9e7c05c-ddc5-11e3-8dd3-262a023231bf.png)

**Comment by richardgroves** [comment]
Issue 686 is about the same problem.

On Sat, May 17, 2014 at 2:18 PM, mattcn notifications@github.com wrote:

> See the screenshot attached, the red line area indicates the background
> view of the cctableview. The outside view can be hidden via CCClippingNode,
> however, the touch event still works when it is hidden. any ideas how to
> fix it?
> [image: cctableview]https://cloud.githubusercontent.com/assets/772040/3004930/a9e7c05c-ddc5-11e3-8dd3-262a023231bf.png
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/cocos2d/cocos2d-iphone/issues/760
> .

## 

Richard Groves
Technical Director | NoodlFroot

M: +44 (0)7962 054 163

www.noodlfroot.com

NoodlFroot Limited is a company registered in England and Wales with
registration number 07245048.
Registered office: 145-157 St John Street, London, EC1V 4PY.

**Comment by Birkemose** [comment]
I think this is the same issue as answered here
http://forum.cocos2d-iphone.org/t/how-to-limit-the-visible-area-and-touchable-area-of-ccscrollview-v3/13242

**Comment by slembcke** [comment]
This will be fixed in v4.
