### ISSUE TITLE
CCProgressNode is flipped vertically in 3.1beta

### ISSUE THREAD

**Issue by thomashempel** [cocos2d/cocos2d-objc#761]
Hi,

I just updated a project from 3.0 to 3.1beta and it looks good so far.

But the CCProgressNode is now flipped perfectly around the y axis. So what was on the left is now on the right and vice versa.

It's not only the sprite, but the whole thing. The progress runs from right to left now instead of left to right.

Greets,
Thomas

P.S.: Is this even the right place to report issues? If not, what is the best way to give feedback like this?

**Comment by slembcke** [comment]
Yup. This is the correct place. The issue was fixed a couple days ago on the `develop` branch though: https://github.com/cocos2d/cocos2d-iphone/issues/745
