### ISSUE TITLE
Please merge 3.0 pull request into 3.1

### ISSUE THREAD

**Issue by NickyWeber** [cocos2d/cocos2d-objc#762]
Refering to this pull request: https://github.com/cocos2d/cocos2d-iphone/pull/753

Fixing SpriteBuilder bug "Dragging CCButton to a CCLayoutBox doesn't work correctly" https://github.com/spritebuilder/SpriteBuilder/issues/465

**Comment by slembcke** [comment]
I merged it on the 15th, but forgot to push on that machine until the 17th. 0c585e0c0f02e37e3a7ec956ce80fafd98d2c2e7

Is there something missing?

**Comment by NickyWeber** [comment]
Looks good, thanks for looking that one up, it seems as if SpriteBuilder is pointing to an older revision. Will check that first next time, sorry.
