### ISSUE TITLE
Node addition/removal performance discrepancy.

### ISSUE THREAD

**Issue by slembcke** [cocos2d/cocos2d-objc#776]
Forum post detailing v2 -> v3 performance discrepancies with the addition and removal of nodes:
http://forum.cocos2d-iphone.org/t/ccspritebatchnode-lag-issue-with-v3/13538/2

Worth looking into.

**Comment by iMobCoding** [comment]
Maybe the performance difference between NSArray and old CCArray?

**Comment by slembcke** [comment]
Unlikely. CCArray used a macro to inline iteration and speed that up mildly, but it was a slower collection overall.
