### ISSUE TITLE
Initialising OpenAL causes other Audio Managers not te be able to create devices

### ISSUE THREAD

**Issue by TimPelgrim** [cocos2d/cocos2d-objc#777]
In the CCAppDelegate in the method `- (void) setupCocos2dWithOptions:(NSDictionary*)config` on line:243 an unused singleton of the OALSimpleAudio gets initialised. This on it's turn creates a device, context and channels. 
`[OALSimpleAudio sharedInstance];`

This however causes a problem in my code because I would like te manage my own channel and device. I currently have 2 ways to work around this problem, the first is to override setupCocos2dWithOptions: but this might cause problems later on when this function changes. The other is to use the device and context of the OALSimpleAudio instance but because I won't be using the rest of this Class this seems wasteful. 

Is this a bug or do I need to change something in my code to get this to work properly?

n.b. The errors getting thrown by initialising a second device:
`OAL Error: +[ALWrapper openDevice:]: Could not open device (null)`

**Comment by s1ddok** [comment]
OAL is not shipped with cocos2d anymore.
