### ISSUE TITLE
CCSprite spriteWithCGImage flips over the y axis in v3.1

### ISSUE THREAD

**Issue by fgeorg** [cocos2d/cocos2d-objc#783]
```
CCRenderTexture renderTexture = [CCREnderTexture renderTextureWithWidth: height:];
[renderTexture begin];
[origSprite visit];
[renderTexture end];
CGImage *anImage = [renderTexture newCGImage]
[CCSprite spriteWithCGImage:anImage key:nil];
```

will generate a sprite that is upside-down. I'm having to set scaleY = -1 to compensate. This was not the case in cocos2d 3.0

**Comment by slembcke** [comment]
Cocos2D has always loaded texture upside down compared to OpenGL's and it's own coordinate convention. It makes for some mildly confusing math when writing shaders or custom drawing functions. I'm fixing this in 3.1 finally. I thought I handled creating textures from CGImages properly, but apparently not.

More info here:
http://forum.cocos2d-iphone.org/t/looking-for-input-on-3-1-custom-shaders-and-drawing/13301

**Comment by slembcke** [comment]
Oooh! Just as I hit the reply button it occurred to me that it might be the CGImage out of the render texture is flipped instead. This was fixed a couple days ago on the `develop` branch. Are you using the last .zip beta release or the latest from GitHub?

**Comment by fgeorg** [comment]
I'm on 1d6e5a5

**Comment by slembcke** [comment]
Hmm. Must be something else then. I'll look into it soon.

**Comment by jtwigg** [comment]
I was seeing this too in SpriteBuilder: The preview images on CCB's started to appear upside down. I fixed by a scale.x *= -1 but I suspect the error might be in the CCRenderTexture itself.

**Comment by slembcke** [comment]
Fixed and added tests.

Found a sort-of-a-bug with [CCSprite spriteWithCGImage:] in that it doesn't take a content scale and assumes 1.0. Should make an alternate method that exposes that: https://github.com/cocos2d/cocos2d-iphone/issues/796
