### ISSUE TITLE
CCScheduler Release in CCBAnimationManager

### ISSUE THREAD

**Issue by cocojoe** [cocos2d/cocos2d-objc#785]
Under typical usage (SpriteBuilder) when a CCB is loaded, an instance of CCBAnimationManager is attached to the node (which will be added to the scene) userObject, so when it comes to teardown this all gets handled gracefully as part of the node cleanup (e.g. remove scheduler from CCBAnimationManager)

However if you simply alloc this class and do not assign to scene node's userObject then it will never be cleaned up properly and released.  The scheduler doesn't like to let things go :) So best case memory leak, worst case is a crash due to actions on targets that no longer exist.

Suppose it is similar to textures and proxy however is there a simpler way?

**Comment by jtwigg** [comment]
I'm working in the CCBAnimationManager system. I'll look into this.

**Comment by slembcke** [comment]
@jtwigg  This was fixed in https://github.com/cocos2d/cocos2d-iphone/pull/792 correct?

**Comment by jtwigg** [comment]
@slembcke   I checked things pretty thoroughly and CCBAnimationManager's were, pausing, resuming, dealloc'ing.

**Comment by cocojoe** [comment]
Yeah it will always dealloc when added to a scene via CCBReader, however do a simple `CCAnimationManager *manager = [CCAnimationManager alloc] init]` in a scene init, it will never be released by the scheduler.  Was wondering if it shouldn't be added to the scheduler until it get's a rootNode, could assert.  Thoughts @slembcke ?

**Comment by slembcke** [comment]
Hmm. I didn't catch that. I guess the simple solution here is to wait to schedule the animation manager for a node until onEnter. Would that break anything with the manager?

**Comment by jtwigg** [comment]
> Would that break anything with the manager?

Not that I can see. 

Is something we intend on doing; creating and populating CCAnimationManager's outside of the CCBReader context? We've moved much of the creation/populating API's to be private for the reason that its very complex code.

**Comment by cocojoe** [comment]
Well that is a good point, I hadn't realised the manual creation methods had been made private.  Typically as it stands you would only expect it to be used via CCBReader.  However there is support in the FrameAnimation category to support sprite frame animation loading like CCAnimation in 2.x which would be invoked manually.  It also kind of annoys me lol

**Comment by cocojoe** [comment]
#854 Fixes this.
