### ISSUE TITLE
[v3.1] CCSetupTabletScale2X rendering bug if position on negative values.

### ISSUE THREAD

**Issue by davilca** [cocos2d/cocos2d-objc#787]
Hello people!

I'm using the latest v3.1 from develop branch. I'm making a pixel art project with retina disabled, so the device uses 4 actual display pixels to represent a pixel of my images.

The problem is that, when you place a sprite in a negative X or Y position (ex: (-4,35) or (16,-20)), then it appears displaced 1 actual display pixel to the left or bottom. Please, see this zoomed in in-game capture:

![bad-rendering](https://cloud.githubusercontent.com/assets/371049/3075161/cde6f57a-e367-11e3-9186-aaa40e28b66c.png)

Each white square represents 4 actual display pixels on non-retina. The top sprite has a positive Y position, the rendering is correct. On the other hand, the bottom sprite has a negative Y position, and then it's displaced 1 actual pixel to the bottom (so a 1 actual pixel line gap appears).

I use CCSetupTabletScale2X = YES, so maybe this has something to do with the bug.

Thanks in advance.

**Comment by slembcke** [comment]
Are you setting nearest neighbor filtering? Did it work the way you expected in 3.0? Since negative absolute coordinates are offscreen, you must mean negative parent coordinates? Does it matter at all how the parent is moved around?

**Comment by davilca** [comment]
- I'm using Antialiasing = NO on the texture (a sprite sheet).
- Haven't tryed this in v3.0.
- The scene contains a node with the size of the screen (node.contentSize = viewSize). Said node contains the two sprites.
- The top sprite is placed in a positive Y position (suppose 160,74).
- The bottom sprite is placed in a negative Y position (suppose 160,-50) so half of it is offscreen (and the position is offscreen because it has anchor point 0,0).
- Both sprites have anchor point (0,0).
- Both sprites use the same sprite sheet texture.

As far as I understand, CCSetupTabletScale2X option tells the engine to scale up all sprites, and in case of an iPhone 5, it uses 4 actual pixels to represent 1 sprite pixel (a 2x scale up). The case is that this scale up has a starting point (something like an anchor point, I guess), and in the negative space, this starting point seems to be displaced one Actual pixel to the bottom.

I'm going to prepare a test case later and upload it somewhere.

**Comment by davilca** [comment]
Well, made the test, and the case is very complicated. In fact, maybe negative space has nothing to do. Download the test here:

http://dyabitgames.com/files/tests/setupTabletScale2XTest.zip

The test uses squared 64x64 px images, with a pixel pattern to easy recognize pixels and artifacts, if occur:

![square-red](https://cloud.githubusercontent.com/assets/371049/3081275/42ad584e-e4bd-11e3-8f4e-2cb09297bb03.png)
![square-blue](https://cloud.githubusercontent.com/assets/371049/3081283/4a035cd8-e4bd-11e3-8bfe-39daf694d3de.png)

Then, I simply put some squres on screen, side to side, and some of then with their position outside screen (all squares with anchor point (0,0)). This is a screenshot taken from device (the problem occurs on simulator too):

![setuptabletscale2x-1](https://cloud.githubusercontent.com/assets/371049/3081293/76eee4f6-e4bd-11e3-8d57-b9dfb58d6b29.png)

Maybe you don't see anything there, but please, download the image and zoom in (use Photoshop and a 16x16 grid). You'll see what I'm talking about:

Case 1: a column of pixels is missing in the left side of the blue sprite.
![captura de pantalla 2014-05-26 a la s 12 00 09](https://cloud.githubusercontent.com/assets/371049/3081311/a2d7562a-e4bd-11e3-8970-7dd4a3ed5db6.png)

Case 2: a column of pixels is missing at the center of the blue sprite.
![captura de pantalla 2014-05-26 a la s 12 00 28](https://cloud.githubusercontent.com/assets/371049/3081315/a74b98c4-e4bd-11e3-89f6-78c96a90747a.png)

Case 3: the red sprite is displaced 1 row of pixels to the bottom, and a lot of shit is going on in the blue sprite
![captura de pantalla 2014-05-26 a la s 12 01 14](https://cloud.githubusercontent.com/assets/371049/3081316/a9ed29ee-e4bd-11e3-82d8-2a3f49a5ed18.png)

Download the images, please. The squared 64x64 sprites should have now a 128x128 size, but sometimes they appear as 128x127, sometimes 127x129, etc, because some rows or cols of sprites are missing. The scale up is incorrect.

The problem appears in both the device and the simulator.

**Comment by davilca** [comment]
More tests. This happens when you fill the screen with squared sprites starting from bottom left of the screen:

![img_2489](https://cloud.githubusercontent.com/assets/371049/3081612/98c7424e-e4c2-11e3-8108-071720999291.PNG)
![img_2488](https://cloud.githubusercontent.com/assets/371049/3081618/9e6c53ba-e4c2-11e3-872b-a06b322c885e.PNG)

Zoom in to see artifacts.

**Comment by slembcke** [comment]
Ah. That's kind of what I was wondering. ;) I think you are running into floating point precision issues, and there is probably nothing that can fix it at the Cocos2D level.

Problems like this tend to show up when you use nearest neighbor filtering because by the time all of the matrix, vertex and interpolation happens, you end up with numbers like 3.00001 and 2.9999 when you really meant 3. The texture sampler then rounds this value down to the nearest pixel and grabs that. Not a problem you can ignore even on desktop GPUs with much higher precision.

A couple possible solutions are to offset your scene node by half a pixel to avoid the catastrophic rounding issues or to try disabling subpixel rendering in ccConfig.h. A better solution might be to set a lower resolution to begin with: http://forum.cocos2d-iphone.org/t/cocos2d-v3-setting-custom-resolution/12124

**Comment by davilca** [comment]
Ok, the problem is gone simply by ENABLING render subpixel:

#define CC_NODE_RENDER_SUBPIXEL 1

In the past, I always disabled this option in my pixel art projects and never had a problem. Maybe in v3.1 calculations are done different. But then, what is the purpose of disabling render subpixel now? I think I disabled this option for pixel projects on purpose, but can't remember why.

Thank you very much @slembcke , but I'm sure that I will face more rendering problems due to enabling render subpixel, :D

**Comment by slembcke** [comment]
Hmm. I was actually going to comment that you might actually have more problems by disabling subpixel rendering. With both it and nearest neighbor filtering enabled, you might run into issues with cracks appearing between perfectly aligned sprites instead. (if the sprites have padding around them anyway)

Unfortunately the only perfect solution is to be _very_ careful with floating point precision which might rule out using a library like Cocos where you can't control everything.
