### ISSUE TITLE
CCRectClippingNode

### ISSUE THREAD

**Issue by slembcke** [cocos2d/cocos2d-objc#788]
@Birkemose brought this up since it's come up on the forums so much. (Probably been mentioned before that too.)

A simpler, faster, less hack-ish version of CCClippingNode when you only want a screen aligned clipping rectangle using the content size of a node. If we used CGRectApplyAffineTransform() to implement it, that gives us a reasonable fallback behavior if the node is rotated or skewed. Could maybe log a warning too?

This would also be an easy way add a clipping option to scroll views and tables since that has been a common request.

**Comment by Birkemose** [comment]
We also need to implement filtered touch, based on the clipping region. It probably has to grab touches from the entire screen, so that it can be used for ex. dialog touch filtering.

**Comment by slembcke** [comment]
Hmm. Yeah I suppose. I was thinking that scroll/table views would handle clipping their input, but it makes more sense to handle that at the scissor node level.

You had posted an idea for a generic solution on the forums. Do you think it could be implemented easily?

**Comment by Birkemose** [comment]
Hmm …maybe it was an idea to make one “clipping” node, and then let the user decide if it should clip touches, graphics or both. IIRC, OpenGL clipping coordinates are always in default portrait mode, so that would require some conversion, but the touch part should be fairly straightforward.

I guess I would have called that a CCClippingNode, and then rename the current clipping node to CCStencilNode.

Den 27 May 2014 kl. 15:18 skrev Scott Lembcke notifications@github.com:

**Comment by slembcke** [comment]
Having flags for clipping touch and rendering separately is a good idea.

glScissor() uses viewport coordinates which rotate with the screen orientation. In old iOS versions (< 4.x I think?), it was really slow to use UIKit to rotate the viewport, but that's not the case anymore. Just need to convert the rect to absolute coordinates and multiply by the content scale.

We don't really want to rename an existing class for a minor version do we? I'm not attached to CCRectClippingNode as a name though.

**Comment by Nixarn** [comment]
This sounds great, it's a bit of a pain to do dialogs with scrollable lists now. The ClippingNode is great for the scrollable content but then you need to hack around it to ensure touch keeps within the dialog.

**Comment by slembcke** [comment]
The viewport node in v4 (currently in review) should handle everything discussed here and more.

**Comment by andykorth** [comment]
Yeah, I think everything is covered here: https://github.com/cocos2d/cocos2d-swift/pull/1129
