### ISSUE TITLE
Clean up the CCBAnimationManager API

### ISSUE THREAD

**Issue by vlidholt** [cocos2d/cocos2d-objc#793]
- [ ] Rename the CCBAnimationManager to CCAnimationManager, needs to have a #define so it is backwards compatible.

Move the following methods and properties to a private API:
- [ ] sequences
- [ ] autoPlaySequenceId
- [ ] rootNode
- [ ] owner
- [ ] rootContainerSize
- [ ] containerSize:
- [ ] addNode:andSequences:
- [ ] moveAnimationsFromNode:toNode:
- [ ] setBaseValue:forNode:propertyName:
- [ ] runAnimationsForSequenceId: tweenDuration:
- [ ] timeSeekForSequenceId:time:
- [ ] addKeyFramesForSequenceName:propertyType:frameArray:node:loop:

Rename
- [ ] timeSeekForSequenceNamed:time: to jumpToSequenceNamed:time:

**Comment by slembcke** [comment]
You might want to consider making an empty subclass with a deprecated marker on it instead of using a define. That way people know to start using the new name and it doesn't break reflection.

**Comment by jtwigg** [comment]
on it

**Comment by jtwigg** [comment]
Additionally : 
Renamed CCBAnimationManager+FrameAnimation.h -> CCAnimationManager+FrameAnimation.h

Didn't make it backwords compatible. It was dated April 14 2014.

**Comment by jtwigg** [comment]
Pending pull request: https://github.com/cocos2d/cocos2d-iphone/pull/802
@vlidholt  @slembcke
