### ISSUE TITLE
Probable bug on responder manager breaking the child CCNode

### ISSUE THREAD

**Issue by kid143** [cocos2d/cocos2d-objc#795]
When I'm dealing with CCNode touch event handling. I found CCNode object's touchBegan:withEvent: method not working. So I track down the source code and found something.

The original code in CCResponderManager class's buildbuildResponderList:(CCNode *)node begins from line 116:
for (CCNode *child in node.children)
        {
            if ((child.zOrder >= 0) && (!nodeAdded) && (node.isUserInteractionEnabled))
            {
                [self addResponder:node];
                nodeAdded = YES;
            }
            [self buildResponderList:child];
        }

Should the "node" should be "child" here? 

This problem comes with v3.0

**Comment by kalo** [comment]
you seem to be using an older release of v3. this should be updated already.

the operation was correct but the semantic was flawed.

the issue was that the `node` would not be added to the responder list if it contained only children with negative z-indexes. perhaps this was related to your issue.

**Comment by kid143** [comment]
Thanks, I got it, there is some semantic flaws that confused me. I'll get a newer release.
