### ISSUE TITLE
[CCSprite spriteWithCGImage:key:] needs a variant with an explicit content scale.

### ISSUE THREAD

**Issue by slembcke** [cocos2d/cocos2d-objc#796]
`[CCSprite spriteWithCGImage:key:]` is hardcoded for a content scale of 1.0. Not overly useful.

**Comment by slembcke** [comment]
There was never a very good fix for this problem due to conflicting designs in the API. This method will either be deprecated or removed in 4.0 and probably replaced with a CCImage variant since those carry explicit content scales.

**Comment by jonnyijapan** [comment]
This can be used:

```
CCTexture* texture = [[CCTexture alloc] initWithCGImage:uiimage.CGImage contentScale:uiimage.scale];
```

**Comment by richardgroves** [comment]
@jonnyijapan - that will work for making a texture but wont add it to the CCTextureCache for easy reuse later in the app.

I use a category on CCTextureCache - https://gist.github.com/richardgroves/a79320ce8557fcb17ba3 that adds the method

```
-(CCTexture*) addCGImage: (CGImageRef) image contentScale: (CGFloat)contentScale forKey: (NSString *)key;
```

to enable me to create textures with a specific key and content scale in the texture cache.

**Comment by jonnyijapan** [comment]
That's nice. Now I loaded my uiimage from file (cache), so I guess I have to check the cache first...

**Comment by richardgroves** [comment]
Yeah - little odd, but I do something like:

```
NSString* key =<some key for the image>;
CCTexture* texture = [[CCTextureCache sharedTextureCache] textureForKey:key];
if (texture == nil)
{
UIImage* image = <load image from whereever>;
CGFloat imageScale = <content scale for this image>;
texture =  [[CCTextureCache sharedTextureCache] addCGImage:image.CGImage contentScale:imageScale forKey:key];
}

// Use the texture...

```

Mine's all a bit more complicated as the image source is a Parse.com backend file, that might have been cached to local disk or might need downloading from a server, and I need to be be loading async if not already in the T-cache....fun & games....

Needed the content scale as I have user-created images that might (or might not) be at retina scale, depending on the device used to create them.

**Comment by jonnyijapan** [comment]
So we both use this 2-step. Maybe it can be rewritten into a "one-liner" by adding a block parameter for loading to the fetcher `textureForKey:`. Maybe like `textureForKey:loadblock:`. Not sure it could work synchronously however.

**Comment by richardgroves** [comment]
That's a nice idea - you should write that up and make a PR or discuss with @Birkemose if he's be interested at least. Would also need a second 'completion' block for when it had the texture\* to be used.
