### ISSUE TITLE
Documentation Updates

### ISSUE THREAD

**Issue by cocojoe** [cocos2d/cocos2d-objc#804]
Noticed a few warnings on last documentation build.  Will be a few files that need to be hidden and a few classes that need to be updated and of course brand new document for CCEffect and anything else?

**Comment by Ben-G** [comment]
@cocojoe @vlidholt Is the current plan to keep the documentation in SpriteBuilder and on makegameswith.us/docs separately?

**Comment by cocojoe** [comment]
Probably needs another pass for apple doc generator, last time I ran there were a lot of warnings etc
