### ISSUE TITLE
Body's mass and moment must be positive to simulate in v3.1

### ISSUE THREAD

**Issue by tanis2000** [cocos2d/cocos2d-objc#817]
I'm experiencing the following error with the v3.1 branch and the included version of Chipmunk:

```
Aborting due to Chipmunk error: Body's mass and moment must be positive to simulate. (Mass: 0.000000 Moment: inf)
    Failed condition: body->m > 0.0f && body->i > 0.0f
    Source:/Users/tanis/Documents/platfromer-v3-sb/platformer.spritebuilder/Source/libs/cocos2d-iphone/external/Chipmunk/src/cpBody.c:498
```

I haven't set the mass or moment by hand and that sprite is being read from SpriteBuilder. It could be a problem with the version of SpriteBuilder that I'm using (it's the one @slembcke gave me some time ago while trying the v3.0 branch as the file format has changed but it looks the same as v3.1: the original SB is version 6 while this one is version 8).

**Comment by tanis2000** [comment]
After some time spent trying to figure out about this issue, I ended up with the theory that it's due to enabling physics on a CCSprite instead of doing it on a CCNode and adding the CCSprite as a child of the CCNode. If anybody has an explanation of why it behaves that way, it'd be nice :)

**Comment by buddard** [comment]
I'm also stuck with this issue since updating my project to Spritebuilder 1.1, my game was working perfectly before upgrading... Were you able to get it to work?

**Comment by slembcke** [comment]
Hmm. I think it's a SpriteBuilder bug. The physics body is created with no shapes on it.

If you open the object up in SB, edit it's physics settings and re-save, it will work.

**Comment by buddard** [comment]
Woah, you're right, editing and re-saving did the trick! Thanks!

**Comment by rursache** [comment]
i can confirm this bug and the solution above. thank you!
