### ISSUE TITLE
CCScheduler crash due to accessing invalid objects

### ISSUE THREAD

**Issue by mctenny** [cocos2d/cocos2d-objc#823]
The loop InvokeMethods in CCScheduler.m may access to an already invalidated object, if a CCNode in [methods copy] was dealloc from another CCNode update: event. And later access in the loop within the same cycle.

To fix:
In @implementation CCScheduleTarget, change __unsafe_unretained to __weak.
In InvokeMethods if(!scheduledTarget->_paused) change to if(scheduledTarget->_target && !scheduledTarget->_paused)

**Comment by slembcke** [comment]
This was fixed in 3.3 I believe?
