### ISSUE TITLE
CCSpriteFrameCache addSpriteFramesWithFile does not load pvr.ccz files

### ISSUE THREAD

**Issue by AlexNolasco** [cocos2d/cocos2d-objc#825]
CCSpriteFrameCache addSpriteFramesWithFile does not load sprites in pvr.ccz, but it does load if the sprite sheet is a PNG file.

**Comment by YvesLeBorg** [comment]
They load, but are improperly decoded. This is a v2 .pvr.gz 

with 3.1 yields : 

![screen shot 2014-08-18 at 6 03 44 pm](https://cloud.githubusercontent.com/assets/8483908/3958840/4290fb32-2724-11e4-8a65-12991b1f33fa.png)

and with 2.1 yields 

![screen shot 2014-08-18 at 5 57 06 pm](https://cloud.githubusercontent.com/assets/8483908/3958852/502748aa-2724-11e4-8544-af6b839a5921.png)
