### ISSUE TITLE
CCParallaxNode hides interface for CGPointObject

### ISSUE THREAD

**Issue by dionlarson** [cocos2d/cocos2d-objc#832]
CCParallaxNode hides the interface for CGPointObject within CCParallaxNode.m but allows access to _parallaxArray which contains only CGPointObjects.

It would be nice to be able to change the offset of CGPointObjects so that you can easily create infinitely scrolling parallax backgrounds. You can currently work around this by copying the CGPointObject interface to the beginning of the file you want to control parallax backgrounds from but this seems like unnecessary extra work.

**Comment by slembcke** [comment]
Parallax nodes are going to be deprecated or removed in v4. Instead we will be providing parallax projections that will be able to fix a lot of the problems associated with the parallax node.
