### ISSUE TITLE
CCNode Scheduling Every Frame (Interval of 0)

### ISSUE THREAD

**Issue by ghost** [cocos2d/cocos2d-objc#840]
I feel like there's a fundamental problem in the current build (or at least the 3.1.0 version; haven't looked at the 3.1.1 code yet).

The header file for CCNode claims:

// Schedules a custom selector with an interval time in seconds.
// If time is 0 it will be ticked every frame.
// In that case, it's recommended to override update: instead.
-(CCTimer *) schedule: (SEL) s interval:(CCTime)seconds;

BUT the implementation is not allowing zero as a valid parameter at all:

-(CCTimer *) schedule:(SEL)selector interval:(CCTime)interval... etc.
NSAssert(interval > 0.0, @"Scheduled method interval must be positive.");

Which contradicts its own documentation, and causes immediate app crash of you try to use an interval of 0.

I think we should still have the option of scheduling a custom selector to run every frame (in perfect sync with the engine's renderer) that we can later unschedule at some arbitrary time. I don't see how overriding "Update:" is suitable enough for every use case. Maybe we want to use Update for things that are indefinitely ongoing, but we still want to have things that can be turned on and off at will by scheduling and un-scheduling them.

Thanks for looking into this! :-)

**Comment by ghost** [comment]
I agree. I'm working on porting a v2 project to v3.1.

I noticed this during the port. In v2, I have certain methods scheduled temporarily (with no interval) and I unschedule them when certain conditions are met so they are only scheduled during key points of the game loop (only when they are needed). There is only a couple of places in the game where I do this, but when they are scheduled, they should fire every frame (there should be no interval).

Now it appears that you cannot schedule a selector and pass 0 in the interval parameter (though this contradicts the comments in the header file). 

The alternative is, I suppose, to override the update method and set a BOOL to conditionally update certain things every frame, though I think I'd like to have the flexibility to schedule/unschedule a custom method every frame.

**Comment by Birkemose** [comment]
You can pause the node, that will stop any updates.
If that for some reason doesn’t fit your needs, you will have to add a custom BOOL or something, to branch your update code.

**Comment by ghost** [comment]
Yeah, I guess I'll end up using a BOOL. I have a  fairly complex game loop where I'd have to fire a method after a certain condition is met, but that condition could be rare. I had a little CCNode subclass extension that made it easy:

 -(void)scheduleSelectorOnce:(SEL)selector afterConditionalBlockReturnsYES:(BOOL(^)())conditionalBlock
{
    __weak ATNode *weakSelf = self;

```
self.conditonalBlock = ^BOOL() {
    BOOL isConditionMet = conditionalBlock();
    if (isConditionMet)
    {
        [weakSelf scheduleOnce:selector delay:0];
        return YES;
    }
    else
    {
        return NO;
    }
};

[self schedule:@selector(fireConditonal:)];
```

}
 -(void)fireConditonal:(ccTime)delta
{
    if (self.conditonalBlock != nil)
    {
        BOOL isConditionMet = self.conditonalBlock();
        if (isConditionMet)
        {
            self.conditonalBlock = nil;
            [self unschedule:_cmd];
        }
    }
    else
    {
        ATLog(@"Conditional Block is nil. Unscheduling %@",NSStringFromSelector(_cmd));
        [self unschedule:_cmd];
    }
}

I'll have to think about how I redesign this code, a bit.
