### ISSUE TITLE
Problems installing Cocos2D with the installer app and with the sh script

### ISSUE THREAD

**Issue by baxterdog** [cocos2d/cocos2d-objc#847]
Problems installing Cocos2D with the installer app and with the sh script

HERE IS THE ERROR LOG***************************
rsync: link_stat "/cocos2d" failed: No such file or directory (2)
rsync error: some files could not be transferred (code 23) at /SourceCache/rsync/rsync-42/rsync/main.c(992) [sender=2.6.9]

I have had no success installing the cocos2d template on my computer with the installer app. I run the app and it says that everything is ok but nothing is installed and the template are not there when go to create from the templates in xCode

I have installed this on another computer so I am doing it correctly.

I am using a MacBookAir  2.13 Core Duo on a fresh install of OS 10.9.3 and I have downloaded the most recent 3.1.0 version of cocos 2D. xCode is version 5.1.1. There are no folders created on the computer at all when I run the app version of the installer but the installer.sh give errors.

I ran it using the terminal using the command below and you can see the results. I got an error, but it did install a "Templates" folder and in that it created a "cocos2d v3.x" folder and a "File Templates folder". In the "cocos2d v3.x" is created a support folder but it did not contain all the elements of the support folder that are in the templates folder in the zip file.

I tried moving over everything manually and the templates are there but they won't compile. The compiler has several errors that say errors like:

"Cannot find interface declaration for "CCScene", superclass of Helloworld..."

Here is the Terminal ************************************************

mlonglaptop:~ mike long$ /Users/<username>/Desktop/install/install.sh 
usage: dirname path

Cocos2D Template Installer (Cocos2D-v3.0.0)

> > > Installing project templates
> > > ...copying cocos2d files ✖︎

Installation failed!
Please, send an email containing your error.log on the support email (written in the --help).
It would make it easier for us to improve this script and fix the issues immediately.

Your error log is located at: /Users/<username>/Desktop/cocos2d-install.log

HERE IS THE ERROR LOG***************************
rsync: link_stat "/cocos2d" failed: No such file or directory (2)
rsync error: some files could not be transferred (code 23) at /SourceCache/rsync/rsync-42/rsync/main.c(992) [sender=2.6.9]

Can you please let me know what my next step should be.

Thanks

**Comment by vkaramov** [comment]
Try edit "Cocos2D Installer 3.1.0.app/Contents/Resources/script" and add the following lines:

#Fix permissions
chown -R $USER: $TARGET_DIR

just after

mkdir -p $TARGET_DIR && tar zxf $INSTALL_FILE -C $TARGET_DIR

and run installer again
