### ISSUE TITLE
V3.1 CCRenderer.m nil exception in iOS5.1.1

### ISSUE THREAD

**Issue by tkjune** [cocos2d/cocos2d-objc#849]
iPhone4, iOS5.1.1
Exception happens here:
**\* Assertion failure in -[CCRenderState hash]
Source:
line 324 of CCRenderer.m
NSAssert(_mainTexture, @"Attempting to cache a renderstate without a mainTexture value.");

Tested with the sample code "GameOfLife" in tutorials on makegameswith.us, updated the project with SpriteBuilder 1.1.
Need to link GLKit.framework in Build Phases first.

**Comment by tkjune** [comment]
Temporary work around: 
    if (_mainTexture != nil) {
        NSAssert(_mainTexture, @"Attempting to cache a renderstate without a mainTexture value.");
    }

**Comment by slembcke** [comment]
!! Somebody reported this as a bug with Apportable although I was never able to reproduce it after a fair amount of effort. I wonder if it's related. Time figure out how to get the iOS 5 simulator installed on my laptop.

**Comment by tkjune** [comment]
Pity that I don't know how to install a iOS 5 simulator either. Just tested several cases:
A) Run GameOfLife on iOS 7 device => Ok
B) Create new project and run on iOS 7 device => Ok
C) Use project in (B) and run on iOS 7 device => Exception
Any more testing or information I can provide, please let me know.
Thank you.

**Comment by thatsplenty** [comment]
I have same problem with an iPad1, iOS 5.1.1

**Comment by ghost** [comment]
Getting this two on migrating a v2 to v3.1 project now. 

Wrapping the assert inside of the if statement as tkjune suggested works of course. To assert that the _mainTexture is not nil only within a if statement that already checks if the _mainTexture is not nil defeats the purpose of having the assert in there though.

**Comment by slembcke** [comment]
This was fixed in 3.3 for sure, though probably in 3.2 as well.
