### ISSUE TITLE
PSD files in smart spritesheets not found

### ISSUE THREAD

**Issue by NickyWeber** [cocos2d/cocos2d-objc#861]
**Issue:**
A psd file in a smart spritesheet is not found and therefore not displayed.

**Origin:**
http://forum.spritebuilder.com/t/psds-and-smart-sprite-sheets-sb-1-1-0-cocos-3-1-0-issue-raised/1359

**Details:**
The filelookup.plist contains the renaming rule to resolve this issue. However as soon as a renamed file is within a spritesheet the filelookup is not processed correctly.

This starts in `CCBReader` when a spriteFrame is created. A texture is then looked up in `CCSpriteFrameCache` first which won't yield anything for example `sheet1/spaceship.psd` since the file is converted to a png in the first place. If nothing is found in `CCSpriteFrameCache` the `CCFileUtils` is asked to find the file. `CCFileUtils` will resolve the filename `sheet1/spaceship.psd` with the filelookup to `sheet1/spaceship.png`  which is not on disk since it's a key in the spritesheets `sheet1` and thus can't be found either.

**Comment by ghost** [comment]
I believe we found a fix for this. The culprit is in frameWithImageNamed:

```
+(id) frameWithImageNamed:(NSString*)imageName
{
    CCSpriteFrame* frame = [[CCSpriteFrameCache sharedSpriteFrameCache] spriteFrameByName:imageName];
    if (!frame)
    {
        CCTexture* texture = [[CCTextureCache sharedTextureCache] addImage:imageName];
        frame = [texture createSpriteFrame];
    }

    return frame;
}

```

The image name is first passed to CCSpriteFrameCache which fails to locate the frame. It then sends it to CCTextureCache which does the correct lookup using fileLookup.plist via CCFileUtils.

```
-(NSString*) fullPathForFilename:(NSString*)filename contentScale:(CGFloat *)contentScale
...
// in Lookup Filename dictionary ?
    NSString *newfilename = [_filenameLookup objectForKey:filename];
    if( ! newfilename )
        newfilename = filename;
```

I added the same lookup to CCSpriteFrameCache and it correctly found the psd spriteframes.

```
-(CCSpriteFrame*) spriteFrameByName:(NSString*)name
{
    CCSpriteFrame *frame = [_spriteFrames objectForKey:name];

    if (!frame)
    {
       // Added .psd file lookup
        NSString *newfilename = [[CCFileUtils sharedFileUtils].filenameLookup objectForKey:name];
        if(newfilename)
            name = newfilename;

        // Try finding the frame in one of the registered sprite sheets
        NSString* spriteFrameFile = [_spriteFrameFileLookup objectForKey:name];


        if (spriteFrameFile) [self addSpriteFramesWithFile:spriteFrameFile];

        // Attempt to load the frame again
        frame = [_spriteFrames objectForKey:name];
    }

    if( ! frame ) {
        // try alias dictionary
        NSString *key = [_spriteFramesAliases objectForKey:name];
        frame = [_spriteFrames objectForKey:key];
    }

    return (CCSpriteFrame *)frame.proxy;
}
```

**Comment by NickyWeber** [comment]
Makes sense, can you make a pull request for this? Thanks in advance!

**Comment by ghost** [comment]
First pull request, let me know if we did it correctly :)

https://github.com/cocos2d/cocos2d-iphone/pull/892

**Comment by s1ddok** [comment]
PR is merged.
