### ISSUE TITLE
Is there podspec for cocos2d 3.1 release?

### ISSUE THREAD

**Issue by SiarheiFedartsou** [cocos2d/cocos2d-objc#875]
Hello! Is there any podspec for cocos2d 3.1 release? I've found only cocos2d (3.1.0-alpha)... Thank you!

**Comment by n-studio** [comment]
I would gladly maintain a podspec but I am really confused with the release versions.
The website has downloads for 3.0 and 3.1 versions, but there is no tag for these versions, only rc, beta and alpha versions.
There is a 3.1.1 tag but neither 3.1.0 nor 3.0. I'm kind of lost...

**Comment by Birkemose** [comment]
I do not think anybody is currently working on pods, so if you can contribute, it could be great.
There was a lot of confusion with the versioning, I am sorry for that. I will make sure that next release is consistent.

/Birkemose
