### ISSUE TITLE
Error building unedited Cocos2d-Swift project

### ISSUE THREAD

**Issue by JuJumagumbo** [cocos2d/cocos2d-objc#924]
I just downloaded and installed Cocos2d-swift and am trying to go through a tutorial on use, but the initial build (I've made no alterations to the template) is throwing errors out the wazoo. File and picture linked. Running Xcode6-Beta4 on OSX10.9.3. Cocos2d-swift is up to date. 
https://www.dropbox.com/sh/kuxxbs6w0by2nxd/AAAnq-t2Er2PKKQPPcgtV_Lba

**Comment by Birkemose** [comment]
This is either because there is a bug in beta4, or because something changed in xcode6. If you create the project in xcode5, it will load and compile in xcode6.  
You will have to add the frameworks manually, and other linker flags.
