### ISSUE TITLE
CCAnimationManager should register with CCScheduler when a CCNode enters the Stage

### ISSUE THREAD

**Issue by Ben-G** [cocos2d/cocos2d-objc#928]
Currently `CCAnimationManager` registers with `CCScheduler` in it's `init` method and unregisters in the `cleanup` method.

If a node is removed from SceneA the `CCAnimationManager` is cleaned up along with the node. If the same node is then added to a SceneB the `CCAnimationManager` does not register with the `CCScheduler` again and therefore the `CCAnimationManager` does not run any animations.

Two workarounds are possible:
- Call `removeChild:X cleanup:NO` instead of `removeChild` 
- Schedule the `CCAnimationManager` with the `CCScheduler` manually

I think it would be ideal if the `CCAnimationManager` would register with the `CCScheduler` when the `CCNode` it belongs to enters the stage.

Any thoughts on this?

**Comment by cocojoe** [comment]
Which code base are you looking at? As the `CCScheduler` registration is part of `onEnter` in `CCAnimationManager` these days.

**Comment by Ben-G** [comment]
Ups! Was looking at 3.1.1. Thanks for letting me know!
