### ISSUE TITLE
V3.1 Default Template has ARC Semantic Issue from Xcode 5.1.1

### ISSUE THREAD

**Issue by hellomaya** [cocos2d/cocos2d-objc#933]
I have installed cocos2d-iphone 3.1, and created a project from its templates. And it raise an error at CCLabelTTF.m line 341:

.../Libraries/cocos2d/CCLabelTTF.m:341:41: No visible @interface for 'CCRenderState' declares the selector 'initWithBlendMode:shader:shaderUniforms:copyUniforms:'

Here is the code : _renderState = [[CCRenderState alloc] initWithBlendMode:_blendMode shader:_shader shaderUniforms:self.shaderUniforms copyUniforms:copyUniforms];

I looked around, found that 

-(instancetype)initWithBlendMode:(CCBlendMode *)blendMode shader:(CCShader *)shader shaderUniforms:(NSDictionary *)shaderUniforms __deprecated;

And this is no declaration for initWithBlendMode:_blendMode shader:_shader shaderUniforms:self.shaderUniforms copyUniforms:copyUniforms...

So I used +(instancetype)renderStateWithBlendMode:(CCBlendMode *)blendMode shader:(CCShader *)shader shaderUniforms:(NSDictionary *)shaderUniforms copyUniforms:(BOOL)copyUniforms; instead, and it's working fine.

My question is, probably we should use +(instancetype)renderStateWithBlendMode:(CCBlendMode *)blendMode shader:(CCShader *)shader shaderUniforms:(NSDictionary *)shaderUniforms copyUniforms:(BOOL)copyUniforms in CCLabelTTF.m...

**Comment by s1ddok** [comment]
Closed due to not actual.
