### ISSUE TITLE
v3.2.0 beta 2 crash in default Newton template code

### ISSUE THREAD

**Issue by tri-nomad** [cocos2d/cocos2d-objc#939]
Opened issue# 938 for missing files in default templates. After patching those, created a project using Newton Template.

I am sure this 3.2 is beta so these are not considered bugs, but I was just wondering if there is any easy fix for it.

Running that code (without any modification) in simulator giving crash immediately. I can upload bt, if needed.

> TestPhysics_32[16740:60b] cocos2d: animation started with frame interval: 60.00
> TestPhysics_32[16740:60b] cocos2d: surface size: 960x640
> TestPhysics_32[16740:60b] -[IntroScene visit:parentTransform:]: unrecognized selector sent to instance 0x9b66df0
> TestPhysics_32[16740:60b] **\* Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[IntroScene visit:parentTransform:]: unrecognized selector sent to instance 0x9b66df0'

**Comment by lynchpin4** [comment]
anybody else encounter this? or know how to fix -

on 3.2.1 as well

**Comment by vladmiller** [comment]
Two years later still the same :)

**Comment by s1ddok** [comment]
Do you mean the problem exists in 3.5? I don't think I understand it well, can you provide more info or maybe demo project?

**Comment by vladmiller** [comment]
@s1ddok actually my fault I am using cocos2d-swift-3.2.1 and problem was related due to invalid opengl view initialization.

**Comment by s1ddok** [comment]
I think it is gone in current version, so we can close it.
