### ISSUE TITLE
CCLabelTTF STILL caches textures causing HUGE memory usage

### ISSUE THREAD

**Issue by clickstan** [cocos2d/cocos2d-objc#940]
I tried the Cocos2d v3.2 latest beta, and this bug still hasn't been patched! The issue, is explained in this forum post from here: http://forum.cocos2d-swift.org/t/cclabelttf-constant-leak/14091/2

"Not actually a memory leak, but overzealous caching of rendering states. The renderer is trying to treat labels like regular sprites, and set up a fast path to batch them. The problem is that they never share textures and can never be batched, so it's just holding onto their textures longer than it needs to. They will still be released when a memory warning happens (or if you force one) though. So you won't ever run out of memory, just use more than you need to.

In v3.1, a WORKING patch was previously added, but then later reversed for some reason. I tested the patched CCLabelTTF.m, and it solves the issue. I'd love for this annoying problem (causing my app memory usage to hit 500MB in 1 minute!) to be fixed and added to v 3.2. The fix should be quick and easy, below is the patched file from the GitHub history.

Here is a screenshot from the cocos2d v3.2 beta 2 CCLabelTTF test (run on an iphone 5s), i just hit the refresh button and the memory usage keeps climbing endlessly (it plateaued when i stopped pressing refresh):
![screen shot 2014-08-19 at 11 16 50 pm](https://cloud.githubusercontent.com/assets/8376113/3976082/a9e29bfc-2818-11e4-89aa-7ca6febf39d6.png)

Here is the Fixed Github CCLabelTTF.m link (as a starting point): https://github.com/cocos2d/cocos2d-iphone/commit/3993fbcf32417a3bea8c5243aea73304b6fa3410

 Thanks :)

**Comment by slembcke** [comment]
Looks like the [CCLabelTTF renderState] method was removed a few weeks ago when some other changes were reverted. Fixed in the `develop` branch now.
