### ISSUE TITLE
Add a CCPackageManager

### ISSUE THREAD

**Issue by vlidholt** [cocos2d/cocos2d-objc#941]
# CCPackageManager

SpriteBuilder 1.2 introduces a new feature called _Packages_. A package is a set of zip files for different devices (iOS/Android/different resolutions). The idea is that these zip files can provide additional content for an app that can be downloaded when needed. Content can be images, sounds, plist files, ccb-files, or any other type of resources. Resources in each zip file is saved in a format for that specific device type, thus minimizing the download size. E.g. a iPhone 3GS will only need to download lower resolution assets. A package could also be used to override the default resources in an app, this can be used to patch the app without uploading a new version to the App Store.
## Proposed interface

This outlines the proposed interface for the CCPackageManager.

```
// Returns a shared instance of the default package manager
+ (id) sharedManager; 

// Sets a delegate that can monitor completions of downloaded packages
@property (nonatomic, weak) delegate;

// The base URL is a link to the directory where packages can be found
@property (nonatomic, strong) NSURL* baseURL;

// Starts download of a package (name as it appear in SB)
- (void) downloadPackageNamed: (NSString*)packageName;

// Checks the current status of a downloaded package (not downloaded/downloaded/failed/downloading)
- (CCPackageStatus) downloadStatusForPackageNamed:(NSString*)packageName;

// Checks the percentage of a download (0 - 1)
- (float) downloadPercentageForPackageNamed:(NSString*)packageName;

// Cancel a download
- (void) cancelDownloadForPackageNamed:(NSString*)packageName;
```

In addition the delegate should have methods for getting updates of the status of the download:

```
- (void) completedDownloadingPackageNamed:(NSString*)packageName;
- (void) cancelledDownloadingPackageNamed:(NSString*)packageName;
- (void) failedDownloadingPackageNamed:(NSString*)packageName error:(NSError*)error;
```
## Implementation

CCBReader's configureCCFileUtils method is modified to add a CCPackages directory in the cache directory. This is where the unzipped files are stored. There also needs to be some way of tracking which packages have been downloaded (either a file in the cache directory or in the user defaults).

**Comment by YvesLeBorg** [comment]
I can see non other applications to such a component. For example, as support of 
- downloadable content bound to some purchasing mechanism
- continuous download of applications' primary resources for large bundle sizes.
  I feel a cocos2d implementation should be generic enough to let non SB API users do their thing, yet be easy to configure by the SpriteBuilder team to meet their specific uses for such an animal.

**Comment by slembcke** [comment]
This was added in 3.3.
