### ISSUE TITLE
App crashes when backgrounded

### ISSUE THREAD

**Issue by sridenour** [cocos2d/cocos2d-objc#944]
If the user switches away from my game while GameCenter is being shown, it crashes. In the game's code I call `[[CCDirector sharedDirector] pause]` and `[[CCDirector sharedDirector] resume]` when showing/hiding GameCenter.

I traced the problem to CCAppDelegate.m, which only calls `[[CCDirector sharedDirector] stopAnimation]` when the app gets sent to the background **_if**_ the CCDirector is the visible view controller! And since the CCDirector _isn't_ visible if GameCenter is being shown when the app gets backgrounded, CCDirector keeps trying to render while in the background, gets an invalid OpenGL context, and crashes.

Is there a reason for only stopping the CCDirector if it's "visible" (aka not showing any modal view controllers)? Or is this an oversight? I fixed it in my game by replacing the calls to `-pause` and `-resume` with calls to `-stopAnimation` and `-startAnimation` when GameCenter is shown/hidden, but it seems like CCAppDelegate should still be trying to stop the CCDirector when the app is backgrounded, regardless of whether the CCDirector is on top and "visible" or not.

**Comment by slembcke** [comment]
fixed in https://github.com/cocos2d/cocos2d-swift/pull/986
Thanks @sridenour.
