### ISSUE TITLE
Tilemap parsing issue in iOS 8.

### ISSUE THREAD

**Issue by slembcke** [cocos2d/cocos2d-objc#964]
Tilemap parsing doesn't work in iOS 8. It crashes on the assertion `NSXMLParser does not support reentrant parsing`.

The .tmx file references and attempts to load a .tsx file. The .tsx file is using a unique parser object. That seems like something that should be Ok, but digging into some [old release notes](https://developer.apple.com/library/ios/releasenotes/Foundation/RN-Foundation-iOS/Foundation_iOS5.html) I found this:

> NSXMLParser is now threadsafe. However, it is not reentrant on a given thread; don't call -parse on an NSXMLParser from within a delegate callback of another NSXMLParser.

It's mentioned in the [class docs](https://developer.apple.com/library/prerelease/ios/documentation/Cocoa/Reference/Foundation/Classes/NSXMLParser_Class/index.html) too, but it's not as clear:

> Unless used in a callback, the NSXMLParser is a thread-safe class as long as any given instance is only used in one thread.

So this has been incorrect in Cocos2D for quite some time. It's only in iOS 8 that Apple added an assertion for it. There are a number of people using a workaround where they create a new thread to run the child parser in. We should probably look into that.

**Comment by slembcke** [comment]
I'm also worried that this is going to be a retractive bug. The tilemap parsing code has changed very little for many years. This might affect all Cocos2D apps running on iOS that use tilemaps regardless of what version of Cocos2D they use.

**Comment by osinoleg** [comment]
Fixed, pull request: https://github.com/cocos2d/cocos2d-swift/pull/987

**Comment by YvesLeBorg** [comment]
apparently the same issue on OSX ?  see below

http://stackoverflow.com/questions/26621898/cocos2d-3-2-1-parallax-test-crashes-on-mac-os-x-10-10-xcode-6-1
