### ISSUE TITLE
RenderTexture ClearStencil

### ISSUE THREAD

**Issue by ksjogo** [cocos2d/cocos2d-objc#969]
https://github.com/cocos2d/cocos2d-iphone/blob/develop/cocos2d/CCRenderTexture.m#L472
Should this be GL_STENCIL_BUFFER_BIT ?

**Comment by thayerandrews** [comment]
At first glance it really looks like this should be GL_STENCIL_BUFFER_BIT and not GL_DEPTH_BUFFER_BIT. Let me dig into it a little more...

**Comment by ksjogo** [comment]
Created a pull request at #972
