### ISSUE TITLE
Portrait orientation does not work on iOS 8

### ISSUE THREAD

**Issue by christinakelly** [cocos2d/cocos2d-objc#973]
Portrait apps are misaligned on iOS 8.  Tested on an iPad Air.

**Comment by osinoleg** [comment]
looking into this now.
- (BOOL)resizeFromLayer:(CAEAGLLayer *)layer 
  is called with a layer.bounds that don't match the window bounds. - only happens on iOS8. I also noticed that if I manually set the desired orientation in the info.plist, then everything seems to work ok.

**Comment by osinoleg** [comment]
So this looks like and SDK bug. I can reproduce this bug with provided sample projects from apple (AdaptivePhotos app located here: https://developer.apple.com/wwdc/resources/sample-code/).
Here are a bunch of people having the same issue: https://devforums.apple.com/message/1044988#1044988

Note: it seems like this issue only happens on iPhone devices. 
Solution: set the desired orientation in the info.plist until apple has a fix.

Another note: If the user builds xcode5 and deploys to a ios8 devices, this bug does not show up,.

**Comment by osinoleg** [comment]
Came up with a hack around this issue, by forcing the status bar orientation. 

Pull request: https://github.com/cocos2d/cocos2d-swift/pull/987
