### ISSUE TITLE
setOpacity should clip the opacity to 1.0f

### ISSUE THREAD

**Issue by killerham** [cocos2d/cocos2d-objc#977]
Setting the opacity of a node to anything greater than 1.0f should clip it to 1.0f.

**Comment by slembcke** [comment]
Color values are clamped in the default vertex shader, but not at the CCNode API level.

It's usually considered a very bad idea to have properties be non-transitive (that might not be the right word...). I mean that if you set a property to a value, reading it back right away should return the same value.

**Comment by killerham** [comment]
Yes but when you set the alpha to 255, it multiplies the r,g,b to 255 and basically turns everything white. If setting it to greater than 1.0 didn't do this, then I would agree.
