### ISSUE TITLE
Unable to see autocomplete Cocos2d classes in Xcode

### ISSUE THREAD

**Issue by ghost** [cocos2d/cocos2d-objc#982]
Hello,
I've create the project using SpriteBuilder, I've also create the MainScene swift class in Xcode and everything seems works fine. The problem it's that i can't see the Nodes class and the autocomplete for those classes.

This is my Bridging-Header file:
# import "CCNode.h"
# import "CCNodeColor.h"
# import "CCLabelTTF.h"
# import "CCButton.h"
# import "CCLayoutBox.h"

in my init method on my MainScene if I'm doing something like this:
![screen shot 2014-09-16 at 12 19 41](https://cloud.githubusercontent.com/assets/4919254/4285789/0e686aac-3d8b-11e4-95c5-18e13a8b2d33.png)
As you can see the autocomplete doesn't show me classes like CCNode or CCNodeColor.
Where it's the problem?
Thanks

**Comment by clickstan** [comment]
i've seen the same problem, any solutions?

**Comment by cocojoe** [comment]
I believe this is currently an Xcode issue with autocompletion and swift.  Hopefully the next update of Xcode will fix.

**Comment by ghost** [comment]
here the solution;
http://stackoverflow.com/questions/25866968/unable-to-see-autocomplete-for-cocos2d-classes-in-xcode/25934561#25934561

**Comment by cocojoe** [comment]
I'm using 6.1 however it didn't work at first until I cleared out derived data.

Clear out  ~/Library/Developer/Xcode/DerivedData and restart Xcode.
