### ISSUE TITLE
SPF spike, game lag, inconsistent behaviour

### ISSUE THREAD

**Issue by cocojoe** [cocos2d/cocos2d-objc#993]
User report issue @ http://forum.spritebuilder.com/t/jerkiness-when-sprite-following-your-finger/1859/

This was 3.2.1 - I couldn't recreate as easily however if you background app for a few minutes then it would recreate for me easily and delta would spike up to 0.017 and stay at that level.
https://www.dropbox.com/sh/ng2y9hgdpp08zhi/AACq0cIS8O2C-TpdNox9Nn6ia?dl=0

I created a Develop SB 1.3/3.3 version (as of Sep 22)
https://www.dropbox.com/s/bnbfuoovq356lb5/test.spritebuilder.zip?dl=0

The issue is also present however I can recreate it more easily, sometimes just a quick background/foreground action will bring it up.  Infact first time I ran the app it went straight to higher delta.

**Comment by iMobCoding** [comment]
I also encountered this behavior with the latest game I made. But as it was Physics game I suspected it's related to physics engine. Often when I start the game for the first time it lags very much, but when exiting and re-entering scene once, everything settles down. It was v3.2.1 I used...
